### ISSUE TITLE
Release of sysbench

### ISSUE THREAD

**Issue by ScrumpyJack** [akopytov/sysbench#1]
please could you tag sysbench for release to the it may be packaged?

https://github.com/akopytov/sysbench/releases

**Comment by akopytov** [comment]
Unfortunately I don't have any plans for a release at the moment. The current model where I just commit code to the repository and everyone pulls as they see fit seems to work for most people. Except probably those who do packaging.

However, Percona provides up-to-date sysbench packages in their repositories, so packaging is still possible without any release work on my end.

I'll keep this issue open though and will close if and when there will be another release.

**Comment by graysky2** [comment]
+1 for using a simple git tag to allow packagers to supply without git requirements.  It is as simple as:
```
git tag 0.5.01 -m "0.5.01" && git push --tags
```

**Comment by kdave** [comment]
Packaging is a way for providing your software to people who may not know how to use it from git and/or it does not force them to use it that way. Automated benchmarking deployments make good use of pre-compiled binaries (suitable for the system package manager). The tagged releases are quite common practice, even if you do not plan to do any release management (feature & stability based). Time-based releases are also fine, should it be eg. every few months. It needs very little from you.

**Comment by akopytov** [comment]
Thanks. As I mentioned earlier I do understand that tags/releases are important for packagers, and I plan to do my best in creating regular releases from the git tree.

**Comment by hydrapolic** [comment]
This would really help us in Gentoo Linux too. We currently have an ancient 0.4.12 release from SF and a "live" package from git head of 1.0 branch. What we can do is to take a snapshot of the current head, name it like snapshot_20161010 and put it to the users - but we would need to store it somewhere on our side. If there is a tag on github, we simply use the archive and mirror it. It's a standard way of working with packages.

**Comment by akopytov** [comment]
sysbench 1.0.0 has been released!

**Comment by kdave** [comment]
Thank you!

**Comment by hydrapolic** [comment]
Thanks @akopytov
