### ISSUE TITLE
thread_run issue

### ISSUE THREAD

**Issue by mckobe23** [akopytov/sysbench#103]
hi

   When I use run to test, the stdout show this:
 

sysbench run stdout
-------
Initializing worker threads...

Threads started!

FATAL: failed to execute function `thread_run': [string "sysbench.lua"]:137: attempt to call global 'event' (a nil value)
------

    Then, I found the sysbench.lua:137, content is:

    131 -- ----------------------------------------------------------------------
    132 -- Main event loop. This is a Lua version of sysbench.c:thread_run()
    133 -- ----------------------------------------------------------------------
    134 function thread_run(thread_id)
    135    while sysbench.more_events() do
    136       sysbench.event_start()
    137       event(thread_id)
    138       sysbench.event_stop()
    139    end
    140 end

so, why the sysbench throw this exception? And how to fix it? thx!

**Comment by akopytov** [comment]
Does you script define an `event()` function?

**Comment by mckobe23** [comment]
o ...The sysbench.lua file has not event() function defined, but why this function was called by thread_run?

**Comment by akopytov** [comment]
sysbench.lua expects you to define event() function in your script file. The event() function describes what should be executed in your benchmark. You can find some examples in sysbench/lua/oltp_*.lua scripts.

**Comment by akopytov** [comment]
oltp_common.lua should not be used directly. It is meant to be included by other OLTP scripts. Use `--test=/root/sysbench_new/sysbench/lua/oltp_point_select.lua`, for example.

**Comment by mckobe23** [comment]
👍 OK! I get it from oltp_*.lua, thank you very much!!
 
btw:I used one spescial script(the olpt_common.lua,haha~) to test,the script has not event()  :)
