### ISSUE TITLE
Add ability to sysbench doc store (5.7 features)

### ISSUE THREAD

**Issue by ManjotS** [akopytov/sysbench#104]
In order to avoid functional overhead provide option for concated string ie 

`rs = db_query("INSERT INTO " .. table_name ..  " (doc) VALUES " .. string.format("('{\"_id\" : \"%d\", \"k\":\"%d\", \"c\":\"%s\",\"pad\":\"%s\" }')",i, k_val, c_val, pad_val))

INSERT INTO sbtest_json1 (doc) 
VALUES ('{"_id" : "47483648", "k":"59263672", "c":"24912351166-62227201466-48573979646-46226163775-05759394754-70094713410-97360717151-61106334505-35565977631-88288836923","pad":"51140030063-90587585668-02097351492-82961843495-96942957620" }');`

Also provide with JSON functions (controlled by flags?)

**Comment by akopytov** [comment]
I'm not sure I understand this report. That code can be rewritten as follows:

``` lua
rs = db_query(string.format([[INSERT INTO %s (doc) VALUES ('{"_id" : "%d", "k":"%d", "c":"%s","pad":"%s" }')]], table_name, i, k_val, c_val, pad_val))
```
I.e. use one `string.format()` call. Which is a bit cleaner and probably faster than the original one.

Regarding JSON encoding/decoding functions, would using something like https://www.kyne.com.au/~mark/software/lua-cjson-manual.html work for you?

**Comment by akopytov** [comment]
Closing, feel free to reopen if can provide more details.
