### ISSUE TITLE
Support MariaDB 10.2 protocol enhancement

### ISSUE THREAD

**Issue by svaroqui** [akopytov/sysbench#107]
Hello,
https://jira.mariadb.org/browse/MDEV-11419
ttps://jira.mariadb.org/browse/MDEV-9114

Thanks for keeping the project alive !

**Comment by akopytov** [comment]
Stephane,

I'd love to add support for that feaure, but from the linked JIRA issue it's not clear what exactly should be done on the sysbench side to support it. Is there a more formal description anywhere?

**Comment by akopytov** [comment]
Closing, feel free to reopen if can provide more details.
