### ISSUE TITLE
Make fails on CentOS 6.7

### ISSUE THREAD

**Issue by ilenghel** [akopytov/sysbench#108]
Hi, 

I was trying to install sysbench on CentOS 6.7, after running the make command, i got the following output:
http://paste.openstack.org/show/597870/

I tried installing it on RedHat 6.1 and 6.9, and it works perfectly.
Do you have any idea why would it not work on CentOS 6.7?

Thanks!

**Comment by akopytov** [comment]
From https://gcc.gnu.org/bugzilla/show_bug.cgi?id=57017 it sounds like it might be a problem with old binutils version. Can you check if upgrading binutils does the trick for you?

**Comment by ilenghel** [comment]
Yes, you are right. Updating the binutils did the trick for me.

Thanks!
