### ISSUE TITLE
Sysbench fail to execute on ARM64 due to undefined symbol

### ISSUE THREAD

**Issue by sjtuhjh** [akopytov/sysbench#109]
Hi, 

The sysbench fails to start as follows.  It seems that the luajit could not work properly. Would you please provide any suggestions to resolve this issue?

#sysbench 
sysbench 1.0.0-69ae2c7 (using bundled LuaJIT 2.1.0-beta2)

Reading the script from the standard input

PANIC: unprotected error in call to Lua API([string "sysbench.sql.lua"]:207 : sysbench: undefined symbol : db_destroy)

**Comment by akopytov** [comment]
Hi @sjtuhjh. I noticed you closed the issue. Is the problem solved now? If so, may I know what was wrong in your setup, so I know what to recommend to other users if they hit the same problem?

Thank you.
