### ISSUE TITLE
oltp_legacy/parallel_prepare.lua may skip tables if threads outnumber tables

### ISSUE THREAD

**Issue by amc1804** [akopytov/sysbench#110]
I don't know if legacy_oltp is still supported, but the same bug could
exist elsewhere too (I haven't tried the new tests).

If the worker threads outnumber the tables, then some worker threads
will have nothing to do and finish immediately, and it looks like those
threads get recycled and receive events intended for other threads,
causing htose other threads to never receive any event and never
initialize their tables.

Here's a run with 1 table and 16 threads:

---quote---{

sysbench 1.0-74d14e7 (using bundled LuaJIT 2.1.0-beta2)

Running the test with following options:
Number of threads: 16
Initializing random number generator from current time

Initializing worker threads...

Threads started!

thread prepare9
thread prepare3
thread prepare9
thread prepare3
thread prepare9thread prepare3
thread prepare3
thread prepare3

thread prepare8thread prepare9thread prepare6thread prepare4

thread prepare2

thread prepare3
thread prepare10
thread prepare4

General statistics:
    total time:                          0.0011s
    total number of events:              16
    total time taken by event execution: 0.0007s

Latency statistics:
         min:                                  0.00ms
         avg:                                  0.04ms
         max:                                  0.15ms
         approx.  95th percentile:             0.11ms

Threads fairness:
    events (avg/stddev):           1.0000/1.66
    execution time (avg/stddev):   0.0000/0.00

}---unquote---

Thread 0 is the only thread with work to do, but "thread prepare0" is
never output.  Instead, thread 3 gets six events, thread 9 gets four
events, thread 4 gets two events, threads 2, 6, 8 and 10 get one event
each.  That makes 16 events total, but threads 0, 1, 5, 7, 11, 12, 13,
14, and 15 get no events.

Even if the worker threads don't outnumber the tables, the same thing
could happen in theory, though it may be very unlikely in practice.

Would it be possible to ignore the thread ID and use some other
mechanism to partition the tables?

**Comment by akopytov** [comment]
Right, parallel_prepare.lua is non-deterministic if the number of worker threads is greater than the number of tables.

However, legacy OLTP scripts are only kept in the tree fore regression tests to test legacy API, i.e. the scripts themselves are not supported.

New OLTP scripts support parallel prepare "natively", i.e. one can do `sysbench --threads=N --tables=M oltp_read_write.lua prepare` and it will do the right thing regardless of how N and M relate to each other.
