### ISSUE TITLE
building sysbench on Windows

### ISSUE THREAD

**Issue by peterbandi** [akopytov/sysbench#114]
Building sysbench on Windows is almost impossible and one finds it out only after spending 1 hour and 11 GB disk space for installing Visual Studio 2015. The README-WIN.txt in incomplete and the listed commands fails. There are 2 major problems:

1. The cmake command fails:
```
C:\Tools\SysBench\sysbench-1.0.2\src>cmake -G "Visual Studio 9 2008"
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:23 (project):
  No CMAKE_C_COMPILER could be found.

CMake Error at CMakeLists.txt:23 (project):
  No CMAKE_CXX_COMPILER could be found.

-- Configuring incomplete, errors occurred!
See also "C:/Tools/SysBench/sysbench-1.0.2/src/CMakeFiles/CMakeOutput.log".
See also "C:/Tools/SysBench/sysbench-1.0.2/src/CMakeFiles/CMakeError.log".
```
It is possible though to get it work through CMake GUI, where it offers to choose from the available compilers manually.

2. It uses the Concurrency Kit that is not supported on Windows. I read that it is probably possible to build it with MinGW but I have not tried it. The generated VS2015 solution does not contain it, therefore it is a prerequisite.

Please let me know if missed something or update the README-WIN.txt file.

**Comment by akopytov** [comment]
Sorry, this has slipped through the cracks. There's no Windows support in sysbench 1.0. I'll update documentation to make it clear.

**Comment by Marc-T** [comment]
Hello,

As it as been mentioned in #102, i confirm that WSL is probably the best & easy way to run sysbench on Windows.

Marc.
