### ISSUE TITLE
Linking libraries

### ISSUE THREAD

**Issue by dataindataout** [akopytov/sysbench#116]
I was having a hard time getting make to complete without error. Here were the errors:

/usr/bin/ld: cannot find -lssl
/usr/bin/ld: cannot find -lcrypto
/usr/bin/ld: cannot find -lz

Here's the hack way I got it to work. Is there a better, more repeatable way to do this you could recommend?

[root@centosbase sysbench]# ln -s /usr/lib64/libcrypto.so.1.0.1e /usr/lib64/libcrypto.so
[root@centosbase sysbench]# ln -s /usr/lib64/libssl.so.1.0.1e /usr/lib64/libssl.so
[root@centosbase sysbench]# ln -s /usr/lib64/libz.so.1.2.7 /usr/lib64/libz.so

I'm using Centos 7 and MariaDB 10.1, but I also had the issue with MariaDB 10.0 and Percona 5.6.

**Comment by akopytov** [comment]
Yes, the `.so` symlinks (as opposed to numbered file names) are installed by the -dev versions of the corresponding packages. I.e. you probably want to install `libssl-dev` and `zlib1g-dev`, but package exact names may be different on your system.

**Comment by dataindataout** [comment]
Thank you! This worked.
