### ISSUE TITLE
does sysbench 1.1.0  support --oltp-skip-trx?

### ISSUE THREAD

**Issue by gaoquan84** [akopytov/sysbench#117]
hi,akopytov!

     Does sysbench 1.1.0  support --oltp-skip-trx? or the default oltp-skip-trx is on?
when I use sysbench to benchmark proxysql,i found select sql route to slave. and use sysbench 0.4.x,select sql route to master

**Comment by akopytov** [comment]
Yes, the option is now called --skip-trx, but I guess you have figured that out yourself. In general, you can use 'sysbench _scriptname_ help'.
