### ISSUE TITLE
fileio tests show output in bits but numbers are byte values

### ISSUE THREAD

**Issue by leonroy** [akopytov/sysbench#12]
For example running the following over a Gibabit link:

    sysbench --test=fileio --file-total-size=4G --file-test-mode=seqwr --max-time=240 --max-requests=0 --file-block-size=1M --num-threads=4 --file-fsync-all run

Output:

	sysbench 0.4.12:  multi-threaded system evaluation benchmark

	Running the test with following options:
	Number of threads: 4

	Extra file open flags: 0
	128 files, 32Mb each
	4Gb total file size
	Block size 1Mb
	Calling fsync() after each write operation.
	Using synchronous I/O mode
	Doing sequential write (creation) test
	Threads started!
	Done.

	Operations performed:  0 Read, 4096 Write, 4096 Other = 8192 Total
	Read 0b  Written 4Gb  Total transferred 4Gb  (91.604Mb/sec)
	   91.60 Requests/sec executed

	Test execution summary:
	    total time:                          44.7140s
	    total number of events:              4096
	    total time taken by event execution: 175.7213
	    per-request statistics:
	         min:                                 25.53ms
	         avg:                                 42.90ms
	         max:                                174.82ms
	         approx.  95 percentile:              51.47ms

	Threads fairness:
	    events (avg/stddev):           1024.0000/0.71
	    execution time (avg/stddev):   43.9303/0.00

Note that the file sizes are in Mb, Gb, Kb, whereas the numerical values are the actual MB value. Is this a bug in sysbench? Has it been fixed?

**Comment by akopytov** [comment]
Yes, it's a known issue which has not been fixed yet. Generally, is neither consistent, nor standards compliant with respect to reporting size units. Sometimes Kb/Mb/Gb are used as units, and sometimes KB/MB/GB. In both cases they actually mean KiB/MiB/GiB as defined by IEC: http://physics.nist.gov/cuu/Units/binary.html

**Comment by leonroy** [comment]
Thanks for the info. And really appreciate the tool, it's awesome. Just wrote a post on how to use it:
http://www.leonroy.com/blog/2015/10/storage-benchmarking/

**Comment by akopytov** [comment]
Fixed in 1.0 with https://github.com/akopytov/sysbench/pull/32.
