### ISSUE TITLE
make buildhost cpudetection optional

### ISSUE THREAD

**Issue by olafhering** [akopytov/sysbench#121]
Per default sysbench tries to guess the cputype on the buildhost with AX_GCC_ARCHFLAG.
The docs of the macro indicate that --without would disable the feature and leave CFLAGS alone. But in practice this does not seem to work.

This prevents proper packaging into a generic sysbench.rpm because depending on the used compile host the resulting binary package will most likely crash with SIGILL because the cpu used at runtime does not understand the generated opcodes. So far the way to fix it is to wipe AX_GCC_ARCHFLAG from configure.ac.

**Comment by akopytov** [comment]
The reason `--without-gcc-arch` doesn't work is that I wanted configure to fail when autodetection fails in certain (rather exotic) environments, and `AX_GCC_ARCHFLAG` does not make it easy to distinguish between failed and disabled autodetection.

I think failing on disabled autodetection and even on failed autodetection is too strong, and I'm going to remove it.

Meanwhile, it is possible to specify a "generic" architecture with an explicit value to either `CFLAGS` or `--with-gcc-arch` as a workaround, e.g. `./configure --with-gcc-arch=i386`.
