### ISSUE TITLE
With PXC, oltp_read_write.lua run is always trigger FATAL: mysql_stmt_execute() returned error 1317.

### ISSUE THREAD

**Issue by rameshvs02** [akopytov/sysbench#122]
With PXC, oltp_read_write.lua run is always trigger `FATAL: mysql_stmt_execute() returned error 1317`.

This issue is not happening with older sysbench version 0.5.

sysbench 0.5 read write run
```
$ /usr/bin/sysbench --test=/usr/share/doc/sysbench/tests/db/oltp.lua --oltp-auto-inc=off --mysql-table-engine=innodb --oltp-table-size=100 --oltp_tables_count=10 --max-time=20 --report-interval=1 --max-requests=0 --mysql-db=test --mysql-user=root --num-threads=4 --db-driver=mysql --mysql-socket=/home/ramesh/work/pxc57/node0/socket.sock,/home/ramesh/work/pxc57/node2/socket.sock run
sysbench 0.5:  multi-threaded system evaluation benchmark

Running the test with following options:
Number of threads: 4
Report intermediate results every 1 second(s)
Random number generator seed is 0 and will be ignored


Threads started!

[   1s] threads: 4, tps: 10.00, reads: 196.07, writes: 52.02, response time: 643.43ms (95%), errors: 0.00, reconnects:  0.00
[   2s] threads: 4, tps: 7.00, reads: 98.00, writes: 32.00, response time: 693.63ms (95%), errors: 1.00, reconnects:  0.00
[..]

Threads fairness:
    events (avg/stddev):           31.7500/5.40
    execution time (avg/stddev):   20.3746/0.15

$ 
```
sysbench 1.0.2 read write run
```
$  /usr/bin/sysbench /usr/share/sysbench/oltp_read_write.lua --auto_inc=off --mysql_storage_engine=innodb  --table-size=100 --tables=10 --mysql-db=test --mysql-user=root --threads=4 --time=20 --report-interval=1 --events=0 --db-driver=mysql --mysql-socket=/sda/pquery/pxc57/node0/socket.sock,/sda/pquery/pxc57/node2/socket.sock  run
sysbench 1.0.2 (using bundled LuaJIT 2.1.0-beta2)

Running the test with following options:
Number of threads: 4
Report intermediate results every 1 second(s)
Initializing random number generator from current time


Initializing worker threads...

Threads started!

[ 1s ] thds: 4 tps: 5.99 qps: 283.49 (r/w/o: 209.62/52.90/20.96) lat (ms,95%): 450.77 err/s: 4.99 reconn/s: 0.00
[ 2s ] thds: 4 tps: 5.00 qps: 142.04 (r/w/o: 98.03/32.01/12.00) lat (ms,95%): 1973.38 err/s: 2.00 reconn/s: 0.00
[ 3s ] thds: 4 tps: 6.00 qps: 139.01 (r/w/o: 98.01/28.00/13.00) lat (ms,95%): 2362.72 err/s: 2.00 reconn/s: 0.00
FATAL: mysql_stmt_execute() returned error 1317 (Query execution was interrupted) for query 'UPDATE sbtest3 SET k=k+1 WHERE id=?'
FATAL: `thread_run' function failed: /usr/share/sysbench/oltp_common.lua:447: SQL error, errno = 1317, state = '70100': Query execution was interrupted
[ 4s ] thds: 2 tps: 2.00 qps: 55.00 (r/w/o: 42.00/8.00/5.00) lat (ms,95%): 475.79 err/s: 5.00 reconn/s: 0.00
Error in my_thread_global_end(): 1 threads didn't exit
$
```

**Comment by rameshvs02** [comment]
This issue is only happening with multiple socket.

**Comment by akopytov** [comment]
It must be something PXC-specific. I have no problems running oltp_read_write.lua over multiple regular MySQL instances. 

```
$ src/sysbench --threads=512 --tables=10 --table-size=1000000 --rand-type=uniform --report-interval=1 --time=60 --mysql-host=10.7.35.165,10.7.34.169 --mysql-user=root src/lua/oltp_read_write.lua run
sysbench 1.0.4-75ad51a (using bundled LuaJIT 2.1.0-beta2)

Running the test with following options:
Number of threads: 512
Report intermediate results every 1 second(s)
Initializing random number generator from current time


Initializing worker threads...


Threads started!

[ 1s ] thds: 512 tps: 14175.58 qps: 288991.29 (r/w/o: 203279.30/56859.25/28852.74) lat (ms,95%): 41.85 err/s: 0.00 reconn/s: 0.00
[ 2s ] thds: 512 tps: 14404.41 qps: 287927.19 (r/w/o: 201487.73/57634.64/28804.82) lat (ms,95%): 56.84 err/s: 1.00 reconn/s: 0.00
[ 3s ] thds: 512 tps: 14466.46 qps: 289129.31 (r/w/o: 202376.52/57812.86/28939.93) lat (ms,95%): 55.82 err/s: 0.00 reconn/s: 0.00
[ 4s ] thds: 512 tps: 14133.76 qps: 283195.32 (r/w/o: 198375.73/56553.06/28266.53) lat (ms,95%): 57.87 err/s: 0.00 reconn/s: 0.00
[ 5s ] thds: 512 tps: 14101.07 qps: 281748.33 (r/w/o: 197145.93/56397.26/28205.13) lat (ms,95%): 62.19 err/s: 0.00 reconn/s: 0.00
[ 6s ] thds: 512 tps: 14473.53 qps: 289464.58 (r/w/o: 202567.40/57953.12/28944.06) lat (ms,95%): 58.92 err/s: 0.00 reconn/s: 0.00
[ 7s ] thds: 512 tps: 14120.62 qps: 282739.48 (r/w/o: 198019.73/56478.50/28241.25) lat (ms,95%): 46.63 err/s: 0.00 reconn/s: 0.00
[ 8s ] thds: 512 tps: 15256.83 qps: 304603.73 (r/w/o: 213057.72/61042.34/30503.67) lat (ms,95%): 61.08 err/s: 0.00 reconn/s: 0.00
[ 9s ] thds: 512 tps: 14395.64 qps: 288175.71 (r/w/o: 201853.91/57524.54/28797.27) lat (ms,95%): 58.92 err/s: 0.00 reconn/s: 0.00
```

The difference between sysbench 0.5 and 1.0 is that the latter uses prepared statements by default. You can try if `--db-ps-mode=disable` fixes the problem.

But in general, you should talk to PXC devs and ask them if PXC would throw ER_QUERY_INTERRUPTED errors in situations when a regular server would not.

**Comment by rameshvs02** [comment]
Thank you very much Alexey. I will check with PXC dev team.

**Comment by rameshvs02** [comment]
Dont not see this issue with `--db-ps-mode=disable` 

```
$  /usr/bin/sysbench /usr/share/sysbench/oltp_read_write.lua --auto_inc=off --mysql_storage_engine=innodb  --table-size=100 --tables=10 --mysql-db=test --mysql-user=root --threads=4 --time=20 --report-interval=1 --events=0 --db-driver=mysql --mysql-socket=/sda/pquery/pxc57/node0/socket.sock,/sda/pquery/pxc57/node2/socket.sock  --db-ps-mode=disable run
sysbench 1.0.2 (using bundled LuaJIT 2.1.0-beta2)

Running the test with following options:
Number of threads: 4
Report intermediate results every 1 second(s)
Initializing random number generator from current time


Initializing worker threads...

Threads started!

[ 1s ] thds: 4 tps: 4.99 qps: 243.57 (r/w/o: 181.68/43.92/17.97) lat (ms,95%): 846.57 err/s: 3.99 reconn/s: 0.00
[ 2s ] thds: 4 tps: 5.00 qps: 99.03 (r/w/o: 70.02/19.01/10.00) lat (ms,95%): 1013.60 err/s: 0.00 reconn/s: [..]
    events (avg/stddev):           28.7500/21.78
    execution time (avg/stddev):   21.2881/1.02

$
```

**Comment by akopytov** [comment]
OK, so PXC doesn't like prepared statements it seems. Though I don't see how ER_QUERY_INTERRUPTED might be relevant.

By the way, *if* ER_QUERY_INTERRUPTED turns out to be a valid response, you have two options:

- add `1317` to `--mysql-ignore-errors`
- create your own report hook. You can find examples in https://github.com/akopytov/sysbench/blob/master/tests/include/api_sql_common.sh#L145

**Comment by rameshvs02** [comment]
Yes, Galera do not fully support prepared statements. There are multiple known issues.
Thank you for the tips.

**Comment by leeparayno** [comment]
I've been getting these 1317 errors with sysbench 1.0.7, running the oltp_read_write.lua workload almost immediately after starting (hitting a Percona Server 5.6.35-81 instance):

```5.6FATAL: `thread_run' function failed: /usr/share/sysbench/oltp_common.lua:426: SQL error, errno = 1317, state = '70100': Query execution was interrupted
FATAL: mysql_stmt_store_result() returned error 1317 (Query execution was interrupted)
FATAL: `thread_run' function failed: /usr/share/sysbench/oltp_common.lua:426: SQL error, errno = 1317, state = '70100': Query execution was interrupted
FATAL: mysql_stmt_store_result() returned error 1317 (Query execution was interrupted)
FATAL: `thread_run' function failed: /usr/share/sysbench/oltp_common.lua:426: SQL error, errno = 1317, state = '70100': Query execution was interrupted
FATAL: mysql_stmt_store_result() returned error 1317 (Query execution was interrupted)
FATAL: `thread_run' function failed: /usr/share/sysbench/oltp_common.lua:426: SQL error, errno = 1317, state = '70100': Query execution was interrupted
FATAL: mysql_stmt_store_result() returned error 1317 (Query execution was interrupted)
FATAL: `thread_run' function failed: /usr/share/sysbench/oltp_common.lua:426: SQL error, errno = 1317, state = '70100': Query execution was interrupted
FATAL: mysql_stmt_store_result() returned error 1317 (Query execution was interrupted)
(last message repeated 1 times)
FATAL: `thread_run' function failed: /usr/share/sysbench/oltp_common.lua:426: SQL error, errno = 1317, state = '70100': Query execution was interrupted
(last message repeated 1 times)
FATAL: mysql_stmt_store_result() returned error 1317 (Query execution was interrupted)
FATAL: `thread_run' function failed: /usr/share/sysbench/oltp_common.lua:426: SQL error, errno = 1317, state = '70100': Query execution was interrupted
FATAL: mysql_stmt_store_result() returned error 1317 (Query execution was interrupted)
FATAL: `thread_run' function failed: /usr/share/sysbench/oltp_common.lua:426: SQL error, errno = 1317, state = '70100': Query execution was interrupted
FATAL: mysql_stmt_store_result() returned error 1317 (Query execution was interrupted)
FATAL: `thread_run' function failed: /usr/share/sysbench/oltp_common.lua:426: SQL error, errno = 1317, state = '70100': Query execution was interrupted
FATAL: mysql_stmt_execute() returned error 1317 (Query execution was interrupted) for query 'UPDATE sbtest1 SET k=k+1 WHERE id=?'
FATAL: `thread_run' function failed: /usr/share/sysbench/oltp_common.lua:452: SQL error, errno = 1317, state = '70100': Query execution was interrupted
FATAL: mysql_stmt_execute() returned error 1317 (Query execution was interrupted) for query 'UPDATE sbtest1 SET k=k+1 WHERE id=?'
FATAL: `thread_run' function failed: /usr/share/sysbench/oltp_common.lua:452: SQL error, errno = 1317, state = '70100': Query execution was interrupted
FATAL: mysql_stmt_execute() returned error 1317 (Query execution was interrupted) for query 'UPDATE sbtest1 SET k=k+1 WHERE id=?'
FATAL: `thread_run' function failed: /usr/share/sysbench/oltp_common.lua:452: SQL error, errno = 1317, state = '70100': Query execution was interrupted
FATAL: mysql_stmt_execute() returned error 1317 (Query execution was interrupted) for query 'UPDATE sbtest1 SET k=k+1 WHERE id=?'
FATAL: `thread_run' function failed: /usr/share/sysbench/oltp_common.lua:452: SQL error, errno = 1317, state = '70100': Query execution was interrupted
FATAL: mysql_stmt_execute() returned error 1317 (Query execution was interrupted) for query 'UPDATE sbtest1 SET k=k+1 WHERE id=?'
FATAL: `thread_run' function failed: /usr/share/sysbench/oltp_common.lua:452: SQL error, errno = 1317, state = '70100': Query execution was interrupted
FATAL: mysql_stmt_execute() returned error 1317 (Query execution was interrupted) for query 'UPDATE sbtest1 SET k=k+1 WHERE id=?'
FATAL: `thread_run' function failed: /usr/share/sysbench/oltp_common.lua:452: SQL error, errno = 1317, state = '70100': Query execution was interrupted
FATAL: mysql_stmt_execute() returned error 1317 (Query execution was interrupted) for query 'UPDATE sbtest1 SET k=k+1 WHERE id=?'
FATAL: `thread_run' function failed: /usr/share/sysbench/oltp_common.lua:452: SQL error, errno = 1317, state = '70100': Query execution was interrupted
FATAL: mysql_stmt_execute() returned error 1317 (Query execution was interrupted) for query 'UPDATE sbtest1 SET k=k+1 WHERE id=?'
FATAL: `thread_run' function failed: /usr/share/sysbench/oltp_common.lua:452: SQL error, errno = 1317, state = '70100': Query execution was interrupted
FATAL: mysql_stmt_execute() returned error 1317 (Query execution was interrupted) for query 'UPDATE sbtest1 SET k=k+1 WHERE id=?'
FATAL: `thread_run' function failed: /usr/share/sysbench/oltp_common.lua:452: SQL error, errno = 1317, state = '70100': Query execution was interrupted
FATAL: mysql_stmt_execute() returned error 1317 (Query execution was interrupted) for query 'UPDATE sbtest1 SET k=k+1 WHERE id=?'
FATAL: `thread_run' function failed: /usr/share/sysbench/oltp_common.lua:452: SQL error, errno = 1317, state = '70100': Query execution was interrupted
FATAL: mysql_stmt_execute() returned error 1317 (Query execution was interrupted) for query 'UPDATE sbtest1 SET k=k+1 WHERE id=?'
FATAL: `thread_run' function failed: /usr/share/sysbench/oltp_common.lua:452: SQL error, errno = 1317, state = '70100': Query execution was interrupted
FATAL: mysql_stmt_execute() returned error 1317 (Query execution was interrupted) for query 'UPDATE sbtest1 SET k=k+1 WHERE id=?'
FATAL: `thread_run' function failed: /usr/share/sysbench/oltp_common.lua:452: SQL error, errno = 1317, state = '70100': Query execution was interrupted
FATAL: mysql_stmt_execute() returned error 1317 (Query execution was interrupted) for query 'UPDATE sbtest1 SET k=k+1 WHERE id=?'
FATAL: `thread_run' function failed: /usr/share/sysbench/oltp_common.lua:452: SQL error, errno = 1317, state = '70100': Query execution was interrupted
Error in my_thread_global_end(): 111 threads didn't exit
```

Using the --db-ps-mode=disable parameter appears  to resolve it.

```
sysbench 1.0.7 (using bundled LuaJIT 2.1.0-beta2)

Running the test with following options:
Number of threads: 128
Initializing random number generator from current time


Initializing worker threads...

Threads started!

SQL statistics:
    queries performed:
        read:                            805994
        write:                           193095
        other:                           100969
        total:                           1100058
    transactions:                        43398  (144.37 per sec.)
    queries:                             1100058 (3659.39 per sec.)
    ignored errors:                      14173  (47.15 per sec.)
    reconnects:                          0      (0.00 per sec.)

General statistics:
    total time:                          300.6106s
    total number of events:              43398

Latency (ms):
         min:                                 25.10
         avg:                                885.83
         max:                               6604.95
         95th percentile:                   2279.14
         sum:                            38443089.78

Threads fairness:
    events (avg/stddev):           339.0469/14.34
    execution time (avg/stddev):   300.3366/0.18
```

Perhaps it is something with the way connections queries are being terminated?

**Comment by akopytov** [comment]
@leeparayno here is a detailed answer: https://www.percona.com/blog/2017/07/05/difference-error-handling-prepare-statement-binary-text-protocol-percona-xtradb-cluster-galera/

Basically, you want to add `1317` to `--mysql-ignore-errors`, i.e.

```shell
sysbench oltp_read_write --mysql-ignore-errors=1213,1020,1205,1317 ... run
```

**Comment by leeparayno** [comment]
@akopytov Is that the case even with Percona Server (standalone)?  This references Percona XtraDB Cluster (PXC).

**Comment by akopytov** [comment]
@leeparayno I have never observed error 1317 with a standalone, non-Galera server. I have also never received any bug reports. This is the only one, but as you can see it is specific to PXC, so I got confused about your question.
