### ISSUE TITLE
Unrecognized command line argument: run

### ISSUE THREAD

**Issue by JohnGW05** [akopytov/sysbench#124]
hi
   i first created database use prepare comand,then when i use run command to run as following scripts shows, it error:Unrecognized command line argument: run. do you know why and how to run correctly?thank you very much

================================read_only.sh=======================
/usr/bin/mysql -uroot -proot -S /var/run/mysqld/mysqld.sock <<EOF
CREATE DATABASE IF NOT EXISTS sbtest;
CREATE USER IF NOT EXISTS sbtest@localhost;
GRANT ALL PRIVILEGES ON sbtest.* to sbtest@localhost identified by 'test';
EOF
HOST=127.0.0.1
PORT=3306
TABLES=5
SIZE=1000000 #24 Bytes each item 24MB each table;120MB in all of the database sbtest

for nthreads in 24 48 64 96 128 200 500 ; do
./sysbench_output/bin/sysbench --oltp-read-only=on --mysql-user=root --mysql-password=root  -oltp-tables-count=$TABLES --oltp-table-size=$SIZE --oltp-dist-type=uniform --report-interval=1 --max-requests=0 --max-time=60 --num-threads=$nthreads --db-driver=mysql sysbench_output/share/sysbench/tests/include/oltp_legacy/oltp.lua run
done

**Comment by akopytov** [comment]
The command line syntax differs between 0.5 and 1.0. I assume you are using 0.5. If that's correct, you have to add `--test=` before the test name (`sysbench_output/share/sysbench/tests/include/oltp_legacy/oltp.lua`).

**Comment by JohnGW05** [comment]
no，i m use the following version：
root@huawei-ubuntu:~/gw05/x86_64# ./sysbench_output/bin/sysbench --version
sysbench 1.0.1

**Comment by akopytov** [comment]
Oh, I see what's wrong now. -oltp-tables-count is missing a '-'.

**Comment by JohnGW05** [comment]
ok，thanks ，it worked
