### ISSUE TITLE
"Pi" returning no decimal places

### ISSUE THREAD

**Issue by lschapker** [akopytov/sysbench#125]
I have a very simple lua script where I put a single print statement in the event function:

```
function event(thread_id)
    print("pi: " .. string.format("%.7f", math.pi))
end

```
and then execute sysbench:
```
sysbench 0.5:  multi-threaded system evaluation benchmark

Running the test with following options:
Number of threads: 1
Random number generator seed is 0 and will be ignored

Threads started!

pi: 3.0000000
OLTP test statistics:
...
```

Is this expected?  Is there any way I can change this functionality? without a recompile?

I'm wanting to use "os.clock()" function to get "0.01" time resolution (I'm trying to insert a millisecond epoch timestamp), but I've failed all of my attempts...

Any assistance would greatly be appreciated!  Thank you.

**Comment by akopytov** [comment]
sysbench 0.5 redefined `LUA_NUMBER` to integer, since integer arithmetic and data types are more common in database benchmarks. That change has been reverted in sysbench 1.0, where the LuaJIT FFI interface removes most problems with numeric data types.

Is using a more recent sysbench version feasible?

**Comment by lschapker** [comment]
I'm not sure whether I can or not (I'm being dictated what version to use).  If I cannot, what might be the recourse?

Thanks for the input!!!

**Comment by akopytov** [comment]
If you are stuck with version 0.5, then recompiling with `LUA_NUMBER` defined to `double` is the only option. See https://github.com/akopytov/sysbench/blob/0.5/sysbench/scripting/lua/src/luaconf.h#L394

**Comment by lschapker** [comment]
Thank you!!!!

**Comment by akopytov** [comment]
You are welcome. I'm closing the issue, feel free to post here or reopen if need further help.
