### ISSUE TITLE
fail to make configure for oracle

### ISSUE THREAD

**Issue by fsoft-manhln** [akopytov/sysbench#127]
Hi,

I am trying to install sysbench to benmark mysql and oracle database.
After that, I run command "./configure --with-oracle='/usr/lib/oracle/12.1/client64'" and "make"
then it displays error as below:
------
In file included from /usr/lib/oracle/12.1/client64/include/oci.h:3488:0,
                 from drv_oracle.c:30:
/usr/lib/oracle/12.1/client64/include/ociap.h:10858:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
 void OCIThreadProcessInit();
 ^
/usr/lib/oracle/12.1/client64/include/ociap.h:10864:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
 boolean OCIThreadIsMulti();
 ^
In file included from /usr/lib/oracle/12.1/client64/include/oci.h:3491:0,
                 from drv_oracle.c:30:
/usr/lib/oracle/12.1/client64/include/ocixmldb.h:208:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
....
------
I changed to version 12.2 but nothing change.
I also installed version 4.0 and it passed this step. But when I run the oltp test it can't create threads and throw exeption "FATAL: pthread_create() for thread #0 failed. errno = 0".

**Comment by akopytov** [comment]
Sorry, the Oracle driver is not supported anymore and will likely be removed from the source tree. I'll make sure to document it properly.

**Comment by fsoft-manhln** [comment]
That news's really bad for me. I am trying to find a tool which supports benchmark for both mysql and oracle for comparison.
Sorry for my next questions, but is there any older version which can be run for both of them?
Or do you know why version 4.0 can't create threads by using pthread_create() (mysql also failed)? Function "sysbench prepare" was run without errors. 
I am using RHEL on AWS EC2 instance.
