### ISSUE TITLE
configure:3324: error: C compiler cannot create executables

### ISSUE THREAD

**Issue by wyett** [akopytov/sysbench#128]
> configure:3251: checking for C compiler default output file name
configure:3273: gcc    conftest.c  >&5
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../crt1.o: could not read symbols: File in wrong format
collect2: ld returned 1 exit status
configure:3277: $? = 1
configure:3315: result: 
configure: failed program was:
| /* confdefs.h.  */
| #define PACKAGE_NAME "sysbench"
| #define PACKAGE_TARNAME "sysbench"
| #define PACKAGE_VERSION "1.1.0"
| #define PACKAGE_STRING "sysbench 1.1.0"
| #define PACKAGE_BUGREPORT "https://github.com/akopytov/sysbench/issues"
| #define PACKAGE "sysbench"
| #define VERSION "1.1.0"
| /* end confdefs.h.  */
| 
| int
| main ()
| {
| 
|   ;
|   return 0;
| }
configure:3321: error: in `/root/sysbench-master':
configure:3324: error: C compiler cannot create executables
See `config.log' for more details.

**Comment by wyett** [comment]
when I excute "./configure", the error info above occured.

**Comment by akopytov** [comment]
It looks like the problem is not in sysbench. Just what it says: the compiler cannot create executables. Probably because of this:
```
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../crt1.o: could not read symbols: File in wrong format
```

**Comment by wyett** [comment]
thanks akopytov!
And my problem was solved by excuting
`yum install -y glibc-devel`
