### ISSUE TITLE
Mutex Benchmark Documentation 

### ISSUE THREAD

**Issue by avaitla** [akopytov/sysbench#130]
Currently the source for the Mutex Benchmark says the parameter 'mutex-loops' controls 'number of empty loops to do inside mutex lock' from https://github.com/akopytov/sysbench/blob/master/src/tests/mutex/sb_mutex.c.

When I look over the code the main logic is here:

    for (i = 0; i < mutex_req->nloops; i++)
      c++;

    pthread_mutex_lock(&thread_locks[current_lock].mutex);
    global_var++;
    pthread_mutex_unlock(&thread_locks[current_lock].mutex);

I wonder if the logic should be:

    pthread_mutex_lock(&thread_locks[current_lock].mutex);
    for (i = 0; i < mutex_req->nloops; i++)
      c++;
    global_var++;
    pthread_mutex_unlock(&thread_locks[current_lock].mutex);

Is there anything I am misunderstanding? Should the docs say "number of empty loops to do outside* mutex lock".

**Comment by akopytov** [comment]
You are right, the docs should be fixed to say "number of empty loops outside the lock". Also, the loop should be really empty by using a memory barrier instead of incrementing a local variable.

**Comment by akopytov** [comment]
Fixed, thanks!
