### ISSUE TITLE
Number of events issue.

### ISSUE THREAD

**Issue by martinarrieta** [akopytov/sysbench#131]
Hello, 

I was testing simple benchmarks for a blog post and the idea was "test an empty event". Here is the code.

```lua
#!/usr/bin/env sysbench

function prepare()
  print("Starting the benchmark")
end

function event()
end

function cleanup()
  print("Finishing... ")
end
```

When I run the sysbench with 100000000 events I get: 
```
./benchmark1.lua run --events=100000000
sysbench 1.1.0 (using bundled LuaJIT 2.1.0-beta2)

Running the test with following options:
Number of threads: 1
Initializing random number generator from current time


Initializing worker threads...

Threads started!


General statistics:
    total time:                          10.0003s
    total number of events:              42530058

Latency (ms):
         min:                                  0.00
         avg:                                  0.00
         max:                                  0.18
         95th percentile:                      0.00
         sum:                               2474.74

Threads fairness:
    events (avg/stddev):           42530058.0000/0.00
    execution time (avg/stddev):   2.4747/0.00
```

If you check, the number of events was 42530058 and not  100000000.

But when I run the same with 10000000 events:

```
./benchmark1.lua run --events=10000000
sysbench 1.1.0 (using bundled LuaJIT 2.1.0-beta2)

Running the test with following options:
Number of threads: 1
Initializing random number generator from current time


Initializing worker threads...

Threads started!


General statistics:
    total time:                          2.3899s
    total number of events:              10000000

Latency (ms):
         min:                                  0.00
         avg:                                  0.00
         max:                                  0.30
         95th percentile:                      0.00
         sum:                                593.01

Threads fairness:
    events (avg/stddev):           10000000.0000/0.00
    execution time (avg/stddev):   0.5930/0.00
```
Since event is an integer, if you run the benchmark with 2147483648 events (2147483647 int limit +1) you get an error which is expected.

```
# ./benchmark1.lua run --events=2147483648
Invalid value for the 'events' option: '2147483648'
```

So the issue are:
1- The number of events is limited by the integer data type, maybe unsigned int would be better because we will never have negative number of events.
2- I don't understand why the number of events it is not been applied for 100.000.000 events if  it is in the range of the int data type.

Thanks, 

Martin.

**Comment by akopytov** [comment]
Hi Martin,

There are 2 limits affecting benchmark execution time: time, and the total number of executed events, whichever comes first. In previous sysbench versions the defaults was `--max-time=0` (i.e. unlimited time) and `--max-requests=10000` (that was actually referring to the number of events, which was unfortunate naming, so the option has been renamed in 1.0).

In sysbench 1.0 the defaults have changed: it's now `--time=10` (10 seconds by default) and `--events=0` (which is the new name for `--max-requests`). So what happens in your case is that with  the 100,000,000 events limit, the 10 seconds time limit is reached first. You can override that with `--time=0`. And with the 10,000,000 events limit, that one is reached before the time limit.

As to the option type (signed 32-bit integer) limiting the maximum allowed value for `--events`. It is of course a limitation, the question is how important it is in reality. In my benchmarks, I almost never limit by events (i.e. use the default `--events=0` value), but limit by the total execution time in most cases. Even in those rare cases when I have to limit by the total number of events, I never have to go higher than 2.4 biliion of events. Please let me know if that limitation is important for you, and I will report it separately.

**Comment by martinarrieta** [comment]
Hi Alexey, now it make sense, the test took 22 seconds to run.

This is the output with time=0

```
# ./benchmark1.lua run --events=100000000 --time=0
sysbench 1.1.0 (using bundled LuaJIT 2.1.0-beta2)

Running the test with following options:
Number of threads: 1
Initializing random number generator from current time


Initializing worker threads...

Threads started!


General statistics:
    total time:                          22.1127s
    total number of events:              100000000

Latency (ms):
         min:                                  0.00
         avg:                                  0.00
         max:                                  0.76
         95th percentile:                      0.00
         sum:                               7028.41

Threads fairness:
    events (avg/stddev):           100000000.0000/0.00
    execution time (avg/stddev):   7.0284/0.00

```

Also, as you mentioned you can cover bigger number of events with execution time.

Thank you for your quick reply.

Martin.
