### ISSUE TITLE
fileio tests do not work well on ZFS filesystems with compression enabled

### ISSUE THREAD

**Issue by sbbeachvball** [akopytov/sysbench#132]
Have been using sysbench recently to check out filesystem performance.  Really, really like it!  I recently ran tests on a new system that we are implementing with ZFS and discovered that the final performance numbers (Mb/sec) are skewed artificially high when enabling compression on ZFS (lz4).  The numbers were on the order of 15 times faster both for creating files and testing passes.  In looking more closely at the files while creating and testing the actual usage (setting of 250Gb) I discovered some interesting items: 2Gb files were only consuming 512 bytes.  During the actual processing the zpool usage shifted around only between about 400Kb and 700Kb (for 250Gb worth of files) and the compressionratio stayed right at 1.00x.  My current guess is that the data written to the files both during creation and testing is likely highly compressible, but even that hypothesis conflicts a bit with the compressionratio staying right at 1.00x.

Curious if anyone else has seen this and/or if there are any sysbench or system flags to set to help keep those numbers more realistic.

**Comment by akopytov** [comment]
@sbbeachvball sysbench fileio test uses zero-filled buffers by default, which explains the results you see. Not sure why compression ratio stays at 1.00x though, can you double-check it?

You can make sysbench use buffers with random values by using the `--validate` option. In which case it will also store checksums on writes and validate them on reads. Can you check if that results in more realistic numbers?

**Comment by sbbeachvball** [comment]
Will try the --validate flag, thanks...   In looking at the data more closely I noticed that the skewed numbers happen only when we had an SSD ZIL.
The test size was 250Gb and the ZIL is 200Gb.  I suspect that with the compression that ZIL never needed to write to the 
actual pool.  That may be why the pool fs never reflected the usage or compression ratio.

Aaron Martin
sbbeachvball@gmail.com

**Comment by akopytov** [comment]
Closing for now. Feel free to reopen if `--validate` doesn't do what you need.

**Comment by sbbeachvball** [comment]
Thanks Alexey, 
   I finally got around to re-running the tests yesterday.
Just checked the results this morning.  
Confirming that --validate produces much more realistic numbers!

Thanks Again!!
