### ISSUE TITLE
Deadlock

### ISSUE THREAD

**Issue by seiichi1101** [akopytov/sysbench#137]
Hi akopytov,

I currently try to assess read/write throughput on Amazon Aurora Mysql  by using sysbench 1.0.7. However I faced an issue that write queries per sec was greatly decreasing along with increase of the number of threads when  I run oltp write only test.  I applied following command 

--------------------------------------------------------
sysbench --table-size=1000000 --db-driver=mysql --mysql-host=<host name> user=<user name> --mysql-password=<password> oltp_read_write prepare
--------------------------------------------------------
for i in 1 2 4 8 16 32 64 128 256 512 1024; do sysbench --time=60 --threads=$i  --db-driver=mysql --mysql-host=<hostname> mysql-user=<user name> --mysql-password=<password> oltp_write_only run; done
--------------------------------------------------------

After investigated the all results, I found out that a lot of deadlocks has occurred with increase the number of theads. I also tried write_only_test on my laptop to localhost mysql-server but same things still happened in local environment.

**Comment by akopytov** [comment]
Can you provide any details?

**Comment by seiichi1101** [comment]
I attached the result below. In particular, test at 512 threads delayed 28s to finish even though I set time 60s because of ignored error (Deadlock).  

Number of threads: 128
    queries:                             218749 (3614.85 per sec.)
    ignored errors:                      133    (2.20 per sec.)
    total time:                          60.5123s
Number of threads: 256
    queries:                             41567  (684.44 per sec.)
    ignored errors:                      4277   (70.43 per sec.)
    total time:                          60.7296s
Number of threads: 512
    queries:                             65226  (734.74 per sec.)
    ignored errors:                      33820  (380.97 per sec.)
    total time:                          88.7726s

[write_only_test.txt](https://github.com/akopytov/sysbench/files/1041514/write_only_test.txt)

**Comment by akopytov** [comment]
So the database is slow, which leads to poor performance with a high number of concurrent connections. What is the sysbench problem here?

**Comment by woonhak** [comment]
I have a similar issue on OLTP complex test against MySQL 5.6.
With increasing number of clients,
it incurs a lot of errors and low TPS rate.

The server equipped with 8 physical (16 with HT) * 4 sockets (Total 64 logical cores),
and 128GB RAM.
All database files are preloaded into MySQL buffer-pool,
and it was also ramdisk storage.
The sysbench table is also partitioned with 64.

Here's some results.
#nthreads, tps, error rate
1, 130.11 , 0.00
2, 237.08, 0.01
4, 479.05, 4.33
8, 1552.04, 0.68
16, 1741.24, 126.06
32, 1027.80, 425.34
64, 780.48, 795.21
128, 345.71, 442.83
256, 138.44, 521.52
512 ,67.50, 489.41

I checked the server status and deadlock log later,
and I assumed that ignored errors caused by deadlocks.
Is there any way to distinguish ignored errors 
and transaction returned by deadlock in statistics report?

**Comment by akopytov** [comment]
Yes, ignored errors are those listed in the `--mysql-ignore-errors` options which defaults to the following list: 1213 (`ER_LOCK_DEADLOCK`), 1205 (`ER_LOCK_WAIT_TIMEOUT`) and 1020 (`ER_CHECK_READ`). The numeric error codes are described here: https://dev.mysql.com/doc/refman/5.7/en/error-messages-server.html

If you are using InnoDB with MySQL 5.7 or below, error 1213 (`ER_LOCK_DEADLOCK`) is the only one of those three that you can encounter. You can verify that by running sysbench with only that error listed in `--mysql-ignore-errors`.

When sysbench receives one of the errors listed in `--mysql-ignore-errors`, it restarts the current transaction, but does not increment the TPS counter, as that transactions wasn't successful. Instead, it increments the "ignored errors" counter.

Generally, deadlocks are expected in the OLTP benchmark. Their frequency depends on many things: hardware (slower CPU and disk usually result in a higher rate of deadlocks), MySQL settings, dataset size (the lower is the dataset size, the higher is the chance for multiple connections to update the same data simultaneously), the number of connections/threads, and the distribution of random numbers used by sysbench (by default `--rand-type=special` is used, which generates most numbers in a rather narrow range, try using `--rand-type=uniform`, for example)

**Comment by woonhak** [comment]
thank you for your comment.
