### ISSUE TITLE
Json format has trailing comma

### ISSUE THREAD

**Issue by jnyu** [akopytov/sysbench#139]
The json format in sysbench/src/lua/internal/sysbench.lua has trailing comma
"qps": {
    "total": %4.2f,
    "reads": %4.2f,
    "writes": %4.2f,
    "other": %4.2f,
  },

It returns errors when unmarshal the result.

**Comment by akopytov** [comment]
Right, it's not valid JSON. I'll fix shortly. Thanks for reporting.
