### ISSUE TITLE
tests/db/oltp.lua sometimes reports impossible transactions/sec values

### ISSUE THREAD

**Issue by GregGTH** [akopytov/sysbench#14]
Sometimes I see an impossible number of transactions per sec (tps) from sysbench. For example:

[  11s] threads: 16, tps: 18446842801212211200.00, reads: 18446842801212035072.00, writes: 18446842801212170240.00, response time: 60.10ms (95%), errors: 0.00, reconnects:  0.00

The command I'm running is:

sysbench --test=/usr/share/doc/sysbench/tests/db/oltp.lua --mysql-host=${SERVER_IP:-127.0.0.1} --mysql-port=3306 --mysql-user=<xyz> --mysql-password=<xyz> --mysql-db=sbtest --mysql-table-engine=innodb --oltp-test-mode=complex --oltp-read-only=off --oltp-reconnect=on --oltp-tables-count=500 --oltp-table-size=1000000 --max-requests=100000000 --num-threads=16 --report-interval=1 --report-checkpoints=10 --tx-rate=1500 run

Normal data looks like:

[  12s] threads: 16, tps: 1385.03, reads: 19488.38, writes: 5540.11, response time: 15.76ms (95%), errors: 0.00, reconnects:  0.00

It seems like it only ever comes out after the "OLTP test statistics:" log line. I also run with report-interval=1, so I wonder if that contributes to some race.

**Comment by GregGTH** [comment]
The unreasonable numbers are not always the same. In a run today, I saw:

[  11s] threads: 16, tps: 18447837089609265152.00, reads: 18447837089609170944.00, writes: 18447837089609244672.00, response time: 5764.45ms (95%), errors: 0.00, reconnects:  0.00
[  11s] queue length: 8659, concurrency: 17

**Comment by akopytov** [comment]
I believe this has been fixed as a part of the major stats refactoring in the master branch. Feel free to reopen if reproducible with the recent code base.
