### ISSUE TITLE
Illegal Instruction in some cases with --validate in version 1.0.5

### ISSUE THREAD

**Issue by sbbeachvball** [akopytov/sysbench#142]
I use CentOS pretty heavily and recently EPEL's sysbench release jumped from 0.4.x to 1.0.x.  In modifying some of my sysbench testing scripts and sorting through the various changes in command line args I ran into a machine that during sysbench --validate fileio prepare throws an "Illegal instruction" error and aborts after creating the first (of 128) test files.  Getting rid of the --validate seems to prevent the issue.  But there seems to be some specificity to it.  Another system (with the same OS - CentOS-7.3.1611) runs just fine with the --validate option.  Those systems likely have slightly varying patch levels.  Running with --verbosity=5 and running via strace has not provided any obvious answers.  Doesn't appear to be SELinux related, so my best guess so far is that maybe there is a library missing?  If it's something like that, then the issue could be a packaging error and not a sysbench bug.

**Comment by sbbeachvball** [comment]
Quick update.  I have found other hosts that generate the same errors, so the issue is not specific to the one host.  Also, found that even if I am able to create the files by avoiding --validate, trying to do a run once they are created (also without --validate) results in an "Illegal Instruction" almost right away (after the "Threads started!" message).  Below is the last bit of output from an strace run.

```
mmap(NULL, 69632, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = 0x7f03a208c000
mprotect(0x7f03a208c000, 4096, PROT_NONE) = 0
clone(child_stack=0x7f03a209bd70, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f03a209c9d0, tls=0x7f03a209c700, child_tidptr=0x7f03a209c9d0) = 12375
rt_sigaction(SIGALRM, {0x407aa0, [ALRM], SA_RESTORER|SA_RESTART, 0x7f039fedb250}, {SIG_DFL, [], 0}, 8) = 0
alarm(30)                               = 0
futex(0x83187c, FUTEX_CMP_REQUEUE_PRIVATE, 1, 2147483647, 0x831850, 2) = 1
write(1, "Threads started!\n\n", 18Threads started!

)    = 18
futex(0x831850, FUTEX_WAKE_PRIVATE, 1)  = 1
alarm(0)                                = 30
+++ killed by SIGILL +++
Illegal instruction
```

**Comment by akopytov** [comment]
Illegal instruction means there was a CPU instruction in the binary that CPU did not understand. Which means the EPEL binary was built with compiler options allowing CPU-specific optimizations that are not understood on some of your hosts.

Questions:
- are we talking about x86, x86_64 or something else?
- what is the CPU model as reported by `cat /proc/cpuinfo`?
- does `readelf -p .GCC.command.line /usr/bin/sysbench` produce any output?
- can you try the CentOS RPM built by me? You can install it by following instructions at https://github.com/akopytov/sysbench#linux

**Comment by sbbeachvball** [comment]
All our systems are x86_64.  I included CPU flags 

Here is the info for the system that fails:
```
model name	: Intel(R) Xeon(R) CPU E5-2630 v2 @ 2.60GHz
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm ida arat epb pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt

[root@jojo sysbenchTesting]# readelf -p .GCC.command.line /usr/bin/sysbench
readelf: Warning: Section '.GCC.command.line' was not dumped because it does not exist!
```

Here is the info for the system that succeeds:
```
model name	: Intel(R) Xeon(R) CPU E5-2640 v4 @ 2.40GHz
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch ida arat epb pln pts dtherm intel_pt tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdseed adx smap xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local

[root@loko ~]# readelf -p .GCC.command.line /usr/bin/sysbench
readelf: Warning: Section '.GCC.command.line' was not dumped because it does not exist!
```

An install from your repo works.  Assuming that confirms that it's a build or packaging issue on the epel side.

Did a quick comparison of flags between the two systems.  The system that the epel build works on is a newer system with the following flags that are NOT on the system that fails with the epel build. 
```
3dnowprefetch
abm
adx
avx2
bmi1
bmi2
cqm
cqm_llc
cqm_mbm_local
cqm_mbm_total
cqm_occup_llc
fma
hle
intel_pt
invpcid
movbe
rdseed
rtm
smap
tsc_adjust
```

**Comment by akopytov** [comment]
I'm looking at the spec file from sysbench-1.0.5-1.el7.src.rpm from EPEL:

```
%build
export CFLAGS="%{optflags}"
autoreconf -vif
%configure --with-mysql \
           --with-pgsql \
           --with-system-ck \
           --with-system-luajit \
%ifarch %{arm} aarch64
           --with-gcc-arch=native
%endif
```

`--with-gcc-arch=native` is the problem. It means GCC will optimize for whatever CPU is used to build EPEL packages. Which is not necessarily compatible with all x86_64 CPUs. I use `--without-gcc-arch` in my packages for that very reason.

I suggest reporting it to the @xavierba, who I think is the maintainer of downstream RPM packages.

**Comment by akopytov** [comment]
Perhaps I spoke too soon, `--with-gcc-arch=native` seems to be only used for AArch64, which is still a bad idea, but that should not affect x86_64 builds. Anyway, this looks like the downstream packaging problem to me.

**Comment by sbbeachvball** [comment]
Submitted bug report: https://bugzilla.redhat.com/show_bug.cgi?id=1459356

Note that there are several other "Illegal Instruction" bugs associated with the package.
Wonder if they could all be related?  :-)    Thanks!!

**Comment by akopytov** [comment]
Thanks, I will be watching the report.

**Comment by sbester** [comment]
I hit this today in my virtualbox....

Program received signal SIGILL, Illegal instruction.
sb_options_init () at sb_options.c:77
77        SB_LIST_INIT(&options);

(gdb) disas
Dump of assembler code for function sb_options_init:
=> 0x000000000040c220 <+0>:     vmovddup 0x69de0(%rip),%xmm0        # 0x476008
   0x000000000040c228 <+8>:     xor    %eax,%eax
   0x000000000040c22a <+10>:    vmovaps %xmm0,0x4982ee(%rip)        # 0x8a4520 <options>
   0x000000000040c232 <+18>:    retq
End of assembler dump.
(gdb) list
72      /* Initialize options library */
73
74
75      int sb_options_init(void)
76      {
77        SB_LIST_INIT(&options);
78
79        return 0;
80      }


[sss@localhost ~]$ cat /proc/cpuinfo
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 58
model name      : Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
stepping        : 9
microcode       : 0x19
cpu MHz         : 0.000
cache size      : 8192 KB
physical id     : 0
siblings        : 4
core id         : 0
cpu cores       : 4
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 popcnt aes rdrand lahf_lm pti fsgsbase
bogomips        : 7380.99
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:

[sss@localhost ~]$ uname -a
Linux localhost.localdomain 3.8.13-118.20.3.el7uek.x86_64 #2 SMP Fri Feb 23 13:52:32 PST 2018 x86_64 x86_64 x86_64 GNU/Linux


solved it by doing this before building:


export CFLAGS=" -march=native -g -fno-omit-frame-pointer -w -O3 "
export CXXFLAGS=" -march=native -g -fno-omit-frame-pointer -w -O3 -std=c++11 "

**Comment by akopytov** [comment]
@sbester make sure you are not using Percona sysbench packages. CentOS repositories or my packagecloud repository should be fine.
