### ISSUE TITLE
The --mysql-port option is not being honored

### ISSUE THREAD

**Issue by tomkrouper** [akopytov/sysbench#143]
I was attempting to play with sysbench was unable to get it to work with a non-standard port. 
```
sysbench \
  --mysql-host=$MYSQL_HOST\
  --mysql-port=3307\
  --mysql-user=$SYSBENCH_USER\
  --mysql-password=$SYSBENCH_PASS\
  --mysql-db=sysbench\
  --mysql-compression=off\
  --threads=200\
  --time=20\
  --report-interval=5\
  fileio prepare
```
The above command worked, except mysqld is not listening on 3307, it is on 3306.

I'm attempting to get `sysbench` to run with proxysql which uses port 6033. This also didn't work.

**Comment by akopytov** [comment]
I see `fileio prepare` in the command line above. `fileio` is a filesystem-level benchmark, it does not create any database connections. I guess you need one of the bundled `oltp_*` benchmarks, for example:

```
sysbench \
  --mysql-host=$MYSQL_HOST\
  --mysql-port=3307\
  --mysql-user=$SYSBENCH_USER\
  --mysql-password=$SYSBENCH_PASS\
  --mysql-db=sysbench\
  --mysql-compression=off\
  --threads=200\
  --time=20\
  --report-interval=5\
  oltp_read_write prepare
```

**Comment by tomkrouper** [comment]
Doh! Sorry for the bogus issue. That'll teach me to work while tired. Thanks for the quick response.
