### ISSUE TITLE
what index should I take care for random memory test

### ISSUE THREAD

**Issue by chengweiv5** [akopytov/sysbench#145]
Hi there, 

I didn't found any such like issue so I open this one.

For fileio test, I understand throughput is the performance index for sequential IO and IOPS for random IO, is it the same for RAM test?

I see there are below output in sysbench

```
Total operations: 8388608 (1643947.92 per second)
8192.00 MiB transferred (1605.42 MiB/sec)
```

Thanks in advance!

**Comment by akopytov** [comment]
They are all referring to the same thing, just expressing it in different numbers. Each operation is read/writing a single block of `memory-block-size` bytes, which is 1024 bytes by default.

So 1643947.92 operations per second is 1643947.92 * 1024 / 1024 / 1024 megabytes per second, i.e. 1605.42 MiB/sec
