### ISSUE TITLE
Sysbench 1.1.0

### ISSUE THREAD

**Issue by Johnnie390** [akopytov/sysbench#146]
Privet Alexey,

trying to get the above running against a MariaDB 10.1.24.

I have extensively used sysbench 0.5 in the past to do CPU load comparisons between X86 and the Mainframe.

Granted that some of my Sysbench options are still 0.5 and thus deprecated, they should nevertheless still work. Here is a snippet of what I am talking about - 
.
.
Running config.sh
starting MySQL server () for run 1 ... (pid=46603)
waiting for server to come up ....................mysqld is alive
starting sysbench
WARNING: --num-threads is deprecated, use --threads instead
sysbench 1.1.0 (using bundled LuaJIT 2.1.0-beta3)

Running the test with following options:
Number of threads: 64
Initializing random number generator from current time

Initializing worker threads...

Threads started!

thread prepare5thread prepare59
thread prepare2thread prepare12thread prepare17thread prepare15
thread prepare10
thread prepare1
thread prepare32
thread prepare18
thread prepare27thread prepare45thread prepare41
thread prepare9thread prepare33thread prepare44thread prepare42thread prepare51
thread prepare37thread prepare57
thread prepare48Creating table 'sbtest58'...thread prepare62thread prepare54
Creating table 'sbtest55'...
Unknown database driver:
thread prepare7
Creating table 'sbtest2'...
Unknown database driver:
thread prepare38
Creating table 'sbtest39'...
Unknown database driver:
Creating table 'sbtest19'...
Unknown database driver:
thread prepare31thread prepare18
Creating table 'sbtest19'...
Unknown database driver:

Creating table 'sbtest13'...
Unknown database driver:
thread prepare43thread prepare12
Creating table 'sbtest13'...
Unknown database driver:
thread prepare8
Creating table 'sbtest52'...
Unknown database driver:
thread prepare11
Creating table 'sbtest12'...
Unknown database driver:
thread prepare61
Creating table 'sbtest62'...
Unknown database driver:
thread prepare60
Creating table 'sbtest61'...
Unknown database driver:
Creating table 'sbtest60'...thread prepare60
Creating table 'sbtest61'...
Unknown database driver:

The command that generated the above test is this - 

sysbench --test=lua/oltp.lua --oltp_tables_count=64 --oltp-table-size=171875 --rand-seed=42 --rand-type=uniform --num-threads=32 --oltp-read-only=on --report-interval=2 --mysql-socket=/var/lib/mysql/mysql.sock --max-time=301 --max-requests=0 --mysql-user=root --percentile=99 run

The command to prepare/create the Db tables was this  - 

sysbench --test=lua/parallel_prepare.lua --oltp_tables_count=64 --oltp-table-size=171875 --num-threads=64 --mysql-table-engine=InnoDB --mysql-socket=/var/lib/mysql/mysql.sock --mysql-user=root run
WARNING: the --test option is deprecated. You can pass a script name or path on the command line without any options.

The above commands work flawlessly with sysbench 0.5.  Any ideas?

Any tips or pointers much appreciated.

JC

**Comment by akopytov** [comment]
Hi JC,

There is indeed some incompatibility with legacy OLTP scripts which requires you to specify the DB driver explicitly when running the `prepare` command. I'll push a fix shortly, but in the meantime adding the following to sysbench command line should fix it: `--db-driver=mysql`.

**Comment by Johnnie390** [comment]
Alexey,

appreciate the prompt reply. Cpacibo!

JC
