### ISSUE TITLE
Failed to build in busybox environment

### ISSUE THREAD

**Issue by duanyao** [akopytov/sysbench#148]
### Versions:
sysbench 1.0 branch.
busybox 1.22.1/1.25.1

### Steps to reproduce:
Build in a busybox environment, such as [alpine linux](https://alpinelinux.org/), without GNU coreutils installed.

If you don't have such busybox environment, you can install busybox (`apt install busybox` on debians), and modify `third_party/concurrency_kit/ck/configure`, line 172, change `expr` to `busybox expr`, and then build.

### Actual result
I you don't build as root user, it should fail at `mkdir -p //include`; If you do, it should fail at `../../../src/sb_util.h:34:19: fatal error: ck_md.h: no such file or directory`.

### The problem
 It seems `third_party/concurrency_kit/ck/configure` is incompatible with busybox's expr. If you run
`./configure --prefix=/home/yourname/project/sysbench-1.0/third_party/concurrency_kit/` in `sysbench-1.0/third_party/concurrency_kit/tmp/ck`, you will see the following output:

```
expr: syntax error
...
Headers will be installed in /include
Libraries will be installed in /lib
Documentation will be installed in /share/man
```
It means `--prefix` is misinterpreted as ""(empty) after a `expr` error.

### Suggestion
A simple workaround is installing GNU coreutils, but it would be nicer to make it compatible with busybox. At least, explicitly state that sysbench doesn't build with busybox.

**Comment by akopytov** [comment]
It sounds like it is a ConcurrencyKit library issue. Can you please check if the same problem occurs with https://github.com/concurrencykit/ck ?

If so, I suggest filing this issue there. I'd be happy to sync as soon as it's fixed upstream.

Thanks.

**Comment by duanyao** [comment]
Yeah, it seems a ConcurrencyKit bug. I'll file one there.

**Comment by akopytov** [comment]
Thanks! Closing this one.

**Comment by duanyao** [comment]
Filed https://github.com/concurrencykit/ck/issues/100

**Comment by duanyao** [comment]
@akopytov Hi, upstream has fixed this issue.

**Comment by akopytov** [comment]
@duanyao thanks, merged the upstream fix to master.
