### ISSUE TITLE
about problems of configure with MyRocks(server ver:5.6.35) 

### ISSUE THREAD

**Issue by fiona514** [akopytov/sysbench#149]
# configure command

```
./configure --prefix=/data1/local/sysbench --with-mysql-includes=/data1/local/mysql-5.6/include/ --with-mysql-libs=/data1/local/mysql-5.6/lib/
```

# error info

configure:15337: /usr/local/gcc61/bin/gcc -o conftest -ggdb3  -march=haswell -D_GNU_SOURCE  -L/data1/local/mysql-5.6/lib/ conftest.c -lmysqlclient_r   >&5
/bin/ld: cannot find -lmysqlclient_r
collect2: error: ld returned 1 exit status

# env
gcc version :6.1.0
kernel version: 3.10.0-229.el7.x86_64
os version:CentOS Linux release 7.1.1503 (Core)

# My opinion

It seems like it`s not found the libmysqlclient.so，but in $MYSQL_HOME/lib/,it names libfbmysqlclient.so. 
then I check mysql_config,  looks ok~

```
112 # Create options 
113 # We intentionally add a space to the beginning and end of lib strings, simplifies replace later
114 libs=" $ldflags -L$pkglibdir  "
115 libs="$libs -lfbmysqlclient   -lpthread -lm -lrt -lssl -lcrypto -ldl -lzlib  "
116 libs="$libs   "
117 libs="$libs "
118 libs_r=" $ldflags -L$pkglibdir  "
119 libs_r="$libs_r -lfbmysqlclient   -lpthread -lm -lrt -lssl -lcrypto -ldl -lzlib   "
120 libs_r="$libs_r "
```

next I check configure script and found hardcode below,no libfbmysqlclient in for statment:

```
15330 for ac_lib in '' mysqlclient_r mysqlclient; do
15331   if test -z "$ac_lib"; then
15332     ac_res="none required"
15333   else
15334     ac_res=-l$ac_lib
15335     LIBS="-l$ac_lib  $ac_func_search_save_LIBS"
15336   fi
15337   if ac_fn_c_try_link "$LINENO"; then :
15338   ac_cv_search_mysql_real_connect=$ac_res
15339 fi
15340 rm -f core conftest.err conftest.$ac_objext \
15341     conftest$ac_exeext
15342   if ${ac_cv_search_mysql_real_connect+:} false; then :
15343   break
15344 fi
15345 done
```

# My solution
in mysql lib dir,I use ln to add a symbolic link to libmysqlclient.so -> libfbmysqlclient.so

**Comment by akopytov** [comment]
Can you check if the following works for you without any workarounds?

```
./configure --prefix=/data1/local/sysbench --with-mysql=/data1/local/mysql-5.6/
```

This should also work:
```
export PATH=/data1/local/mysql-5.6/bin:$PATH
./configure --prefix=/data1/local/sysbench
```

**Comment by fiona514** [comment]
thanks~ It's works well

**Comment by akopytov** [comment]
OK, thanks for confirming. Generally, `--with-mysql` is the preferred way to build against a server installed in a non-standard location. `--with-mysql-includes` and `--with-mysql-libs` were implemented for cases when `--with-mysql` doesn't work.
