### ISSUE TITLE
Warn about unused/unsupported options

### ISSUE THREAD

**Issue by cubah** [akopytov/sysbench#15]
Hello, I tested sysbench 0.5 commit #246 on Windows 7, and seem there is no  --oltp-table-size affect:

sysbench --mysql-user=sbuser --mysql-password=mypwd --test=./db/insert.lua --oltp-table-size=20000 --oltp-tables-count=1 --num-threads=5 --report-interval=1 run

... I got result:

OLTP test statistics:
    queries performed:
        read:                            0
        write:                           10000
        other:                           0
        total:                           10000
    transactions:                        0      (0.00 per sec.)
    read/write requests:                 10000  (1329.67 per sec.)
    other operations:                    0      (0.00 per sec.)
    ignored errors:                      0      (0.00 per sec.)
    reconnects:                          0      (0.00 per sec.)

General statistics:
    total time:                          7.5207s
    total number of events:              10000
    total time taken by event execution: 37.2719s
    response time:
         min:                                  1.52ms
         avg:                                  3.73ms
         max:                                 17.34ms
         approx.  95 percentile:               8.68ms

Threads fairness:
    events (avg/stddev):           2000.0000/1.79
    execution time (avg/stddev):   7.4544/0.00

Expected:
SHoud not be here 20000 writes/insertions. reported when running insert.lua ? 

Regards
Buke

**Comment by akopytov** [comment]
It's an interesting corner case. On the one hand, `--oltp-table-size` does not have any effect on actual benchmark runs for all modes, it only affects the original table size when tables are created on `prepare`. On the other hand, it could be used by insert.lua as yet another limit in addition to `--max-requests` and `--max-time`. The former looks more consistent to me, but you seem to be expecting the latter. 

Changing insert.lua to respect `--oltp-table-size` during the benchmark run would be trivial, but then, unlike `--max-requests`, the actual number of inserted rows would also depend on `--oltp-tables-count`.

**Comment by cubah** [comment]
Hello Alexiej
Thanks for answer !
Now, I get your way of thinking (and after I have read sysbench-manual.pdf several times). So maybe I could give you my helpful feeligns which can make life easier for other. So i doc there is mentioned [common options]  vs [test option]. The first are listen in chapter.2. But the last option seems to be intuitive specific for the test, e.g. other for oltp.lua either for insert.lua. The problem is that the --oltp-table-size is affecting test for specific mode only (only when 'prepare' oltp test is used). Moreoverthis param affects also different test (insert.lua 'prepare'). This introduces some mess overall.
I think user should be informed if any param is not suitable for given test. Then your sysbench would be more perfect than is :) For me is best of all!
Anyway Marry Christamas !
Jakub Hunia
Dnia 21 grudnia 2015 13:01 Alexey Kopytov napisał(a):
 It's an interesting corner case. On the one hand, --oltp-table-size does not have any effect on actual benchmark runs for all modes, it only affects the original table size when tables are created on prepare. On the other hand, it could be used by insert.lua as yet another limit in addition to --max-requests and --max-time. The former looks more consistent to me, but you seem to be expecting the latter.Changing insert.lua to respect --oltp-table-size during the benchmark run would be trivial, but then, unlike --max-requests, the actual number of inserted rows would also depend on --oltp-tables-count.—

**Comment by akopytov** [comment]
Thank you, Jacob. I agree, sysbench should be stricter about its options handling and make it clear for the user when some options do not make any sense.

Let's keep it as a request to throw a warning/error message about unused/unsupported options.
