### ISSUE TITLE
about support of more data type

### ISSUE THREAD

**Issue by fiona514** [akopytov/sysbench#150]
HI,we have lots of tables which consist of bigint type fields.So in order to simulate actual workload of live service,could you please add unsigned long long type in sysbench.c

Then,too, varbinary,or blob data type in MySQL :)

**Comment by akopytov** [comment]
Just so I understand the request, can you be a little more specific? As in, what precisely prevents you from using BIGINT, BLOB and VARBINARY columns in sysbench benchmarks?

**Comment by fiona514** [comment]
because if our column value if very big,and hold 8 byte,if no suport longlong data type, the data I insert into  table is big negative numbers...

# for example:

* my lua script:

```
function event(thread_id)
   local table_name
   local i
   local a_id_val
   local b_offset_min_val
   local b_offset_max_val

   table_name = "t_" .. sb_rand_uniq(0,512)
   a_id_val = sb_rand(4040649290496151,4040649290498251)
   b_offset_min_val = sb_rand(1,99)
   b_offset_max_val = sb_rand(10000,3572863)

   rs = db_query("select * from " .. table_name .. " where a_id=" .. a_id_val .. " and b_offset BETWEEN " .. b_offset_min_val .. " AND " .. b_offset_max_val .. " and type=3 order by mid  desc limit 3000")

end

```

* my table schema

```
CREATE TABLE `t_1` (
`mid` bigint(20) unsigned NOT NULL,
`a_id` bigint(20) unsigned NOT NULL,
`type` tinyint(4) NOT NULL DEFAULT '0',
`offset` int(10) unsigned NOT NULL DEFAULT '0',
`b_offset` int(10) NOT NULL DEFAULT '0',
PRIMARY KEY (`mid`),
KEY `idx_attm` (`a_id`,`type`,`time_offset`,`mid`),
KEY `idx_rtcm` (`room_id`,`type`,`check_time_offset`,`mid`))
 ENGINE=InnoDB DEFAULT CHARSET=utf8
```

* sysbench.c i modified base on version 0.5

```
/* If we should initialize random numbers generator */
static unsigned long long rand_init;
static rand_dist_t rand_type;
static unsigned long long (*rand_func)(unsigned long long, unsigned long long); /* pointer to random numbers generator */
static unsigned long long rand_iter;
static unsigned long long rand_pct;
static unsigned long long rand_res;
static unsigned long long rand_seed; /* optional seed set on the command line */

```

**Comment by akopytov** [comment]
OK, thanks for clarifications. Few things to note:

1. I suggest migrating to sysbench 1.0. sysbench 0.5 is no longer supported. On top of that, 0.5 doesn't even support result sets, so doing things like `rs  = db_query(...)` doesn't make any sense.

2. As I understand, the real problem is that sb_rand*() functions in sysbench 0.5 return `int`. Your table schema uses the `INT UNSIGNED` MySQL type, so the range of generated random numbers is insufficient.

3. Again, sysbench 1.0 should solve this particular problem. sb_rand*() functions now return `uint32_t` integers, which should be fine for your case without any modifications to the code. Can you confirm it?

**Comment by fiona514** [comment]
wow~~~cool~~~thanks very much~~~~!!

**Comment by housansan** [comment]
Hi , we have lots of tables which consist of blob type fields.So in order to simulate actual workload of live service,  I want to use blob data type，but sysbench dont have this type，Is use VARCHAR and blob test result the same ? OR could you add blob data type，please ？

**Comment by akopytov** [comment]
@housansan it is hard to answer that without fully understanding the problem. Can you provide more details on what you have tried to do and how it failed?

**Comment by housansan** [comment]
my table schema
CREATE TABLE `sbtest_1` (
 `id` INT NOT NULL  ,
 `name` VARCHAR(64)   ,
 `BlobAttr` MEDIUMBLOB    ,    
PRIMARY KEY(`id`),
UNIQUE (`name`),
INDEX `ix_name` (`name`))
 ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
 I must insert MEDIUMBLOB Type data.

**Comment by akopytov** [comment]
I create the following test script in `test.lua`:
```lua
con = sysbench.sql.driver():connect()
con:query("DROP TABLE IF EXISTS sbtest_1")
con:query([[
CREATE TABLE `sbtest_1` (
 `id` INT NOT NULL  ,
 `name` VARCHAR(64)   ,
 `BlobAttr` MEDIUMBLOB    ,    
PRIMARY KEY(`id`),
UNIQUE (`name`),
INDEX `ix_name` (`name`))
 ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
]])

con:query("INSERT INTO sbtest_1 VALUES (1, 'name', 'blobdata');")

print(con:query_row("SELECT * FROM sbtest_1"))
```

Here's what I get when executing it:
```shell
$ sysbench /tmp/test.lua --db-driver=mysql --mysql-user=root --mysql-db=test
sysbench 1.1.0-9860001 (using bundled LuaJIT 2.1.0-beta3)

1	name	blobdata
```

What is missing in this test to demonstrate the problem with blobs?
