### ISSUE TITLE
Not support PowerPC of freescale

### ISSUE THREAD

**Issue by oska874** [akopytov/sysbench#154]
When I try to compile sysbench for my powerpc develop board, it shows:

```
sysbench-master/third_party/luajit/lib/libluajit-5.1.a: could not read symbols: File in wrong format
```

So sysbench does not support ppc .Will sysbench suppoert ppc in the future?

**Comment by akopytov** [comment]
64-bit PowerPC is not currently supported by LuaJIT. However, there's an experimental branch adding non-JIT support. I just need to think about the proper way to integrate it into sysbench.

This has already been reported and discussed in #129, so I'm closing this one.
