### ISSUE TITLE
FATAL Error in Sysbench reporting MySQL Error code 0 

### ISSUE THREAD

**Issue by jmyoda79** [akopytov/sysbench#156]
**I've used bold on my text to make it more obvious. I'm attempting to run sysbench against a Percona XtraDB cluster (version 5.7.18). I know that I will encounter deadlocks and I have set sysbench to ignore them (ignore-errors=1213,2013,1317). However, sysbench is erroring out with an error code of 0 (zero) which shouldn't be possible. Here is the exact item I am running and the errors I'm receiving :** 

`# sysbench oltp_read_write --mysql-user=sbuser  --mysql-password=sbpass --mysql-db=readWrite --mysql-host=127.0.0.1 --threads=24 --max-requests=0 --time=300 --report-interval=10 --tables=5  --db-driver=mysql --mysql-ignore-errors=1213,2013,1317 run
sysbench 1.0.7 (using bundled LuaJIT 2.1.0-beta2)

Running the test with following options:
Number of threads: 24
Report intermediate results every 10 second(s)
Initializing random number generator from current time

Initializing worker threads...

Threads started!

[ 10s ] thds: 24 tps: 375.19 qps: 8059.91 (r/w/o: 5674.56/1600.29/785.06) lat (ms,95%): 106.75 err/s: 44.76 reconn/s: 0.00
[ 20s ] thds: 24 tps: 386.64 qps: 8214.73 (r/w/o: 5777.28/1631.96/805.48) lat (ms,95%): 101.13 err/s: 42.00 reconn/s: 0.00
[ 30s ] thds: 24 tps: 378.50 qps: 8002.03 (r/w/o: 5625.72/1591.51/784.80) lat (ms,95%): 102.97 err/s: 38.10 reconn/s: 0.00
[ 40s ] thds: 24 tps: 389.10 qps: 8289.31 (r/w/o: 5833.31/1645.30/810.70) lat (ms,95%): 102.97 err/s: 44.00 reconn/s: 0.00
FATAL: mysql_stmt_execute() returned error 0 () for query 'SELECT c FROM sbtest3 WHERE id=?'
FATAL: thread_run' function failed: /usr/share/sysbench/oltp_common.lua:413: SQL error, errno = 0, state = '00000':`

**If I look at the query log, the last  error that occurred in the database is a deadlock (error code 1213). If I set sysbench to ignore error code 0, sysbench never finishes. Here is an example where time is set to 30.** 

`# sysbench oltp_read_write --mysql-user=sbuser  --mysql-password=sbpass --mysql-db=readWrite --mysql-host=127.0.0.1 --threads=24 --max-requests=0 --time=30 --report-interval=5 --tables=5  --db-driver=mysql --mysql-ignore-errors=1213,2013,1317,0 run
sysbench 1.0.7 (using bundled LuaJIT 2.1.0-beta2)

Running the test with following options:
Number of threads: 24
Report intermediate results every 5 second(s)
Initializing random number generator from current time

Initializing worker threads...

Threads started!

[ 5s ] thds: 24 tps: 380.36 qps: 8181.88 (r/w/o: 5764.10/1620.72/797.07) lat (ms,95%): 104.84 err/s: 44.95 reconn/s: 0.00
[ 10s ] thds: 24 tps: 391.04 qps: 8288.06 (r/w/o: 5824.00/1651.77/812.28) lat (ms,95%): 99.33 err/s: 42.20 reconn/s: 0.00
[ 15s ] thds: 24 tps: 392.62 qps: 8347.10 (r/w/o: 5875.35/1655.10/816.65) lat (ms,95%): 97.55 err/s: 42.40 reconn/s: 0.00
[ 20s ] thds: 24 tps: 388.78 qps: 8619.45 (r/w/o: 5787.97/1641.73/1189.75) lat (ms,95%): 95.81 err/s: 422.38 reconn/s: 0.20
[ 25s ] thds: 24 tps: 378.80 qps: 8763.15 (r/w/o: 5673.97/1601.79/1487.39) lat (ms,95%): 101.13 err/s: 740.20 reconn/s: 0.00
[ 30s ] thds: 24 tps: 368.26 qps: 8603.16 (r/w/o: 5538.71/1570.21/1494.24) lat (ms,95%): 104.84 err/s: 771.71 reconn/s: 0.00
[ 35s ] thds: 22 tps: 4.60 qps: 597.07 (r/w/o: 32.21/12.61/552.25) lat (ms,95%): 69.29 err/s: 547.45 reconn/s: 0.00
[ 40s ] thds: 22 tps: 0.00 qps: 1882.92 (r/w/o: 0.00/0.00/1882.92) lat (ms,95%): 0.00 err/s: 1882.92 reconn/s: 0.00
[ 45s ] thds: 22 tps: 0.00 qps: 2356.00 (r/w/o: 0.00/0.00/2356.00) lat (ms,95%): 0.00 err/s: 2356.00 reconn/s: 0.00
[ 50s ] thds: 22 tps: 0.00 qps: 2637.20 (r/w/o: 0.00/0.00/2637.20) lat (ms,95%): 0.00 err/s: 2637.20 reconn/s: 0.00
[ 55s ] thds: 22 tps: 0.00 qps: 2546.99 (r/w/o: 0.00/0.00/2546.99) lat (ms,95%): 0.00 err/s: 2546.99 reconn/s: 0.00
[ 60s ] thds: 22 tps: 0.00 qps: 2483.61 (r/w/o: 0.00/0.00/2483.61) lat (ms,95%): 0.00 err/s: 2483.61 reconn/s: 0.00
[ 65s ] thds: 22 tps: 0.00 qps: 2622.19 (r/w/o: 0.00/0.00/2622.19) lat (ms,95%): 0.00 err/s: 2622.19 reconn/s: 0.00
[ 70s ] thds: 22 tps: 0.00 qps: 2808.64 (r/w/o: 0.00/0.00/2808.64) lat (ms,95%): 0.00 err/s: 2808.64 reconn/s: 0.00
[ 75s ] thds: 22 tps: 0.00 qps: 2744.57 (r/w/o: 0.00/0.00/2744.57) lat (ms,95%): 0.00 err/s: 2744.57 reconn/s: 0.00
[ 80s ] thds: 22 tps: 0.00 qps: 2650.43 (r/w/o: 0.00/0.00/2650.43) lat (ms,95%): 0.00 err/s: 2650.43 reconn/s: 0.00
[ 85s ] thds: 22 tps: 0.00 qps: 2798.96 (r/w/o: 0.00/0.00/2798.96) lat (ms,95%): 0.00 err/s: 2798.96 reconn/s: 0.00
[ 90s ] thds: 22 tps: 0.00 qps: 2643.60 (r/w/o: 0.00/0.00/2643.60) lat (ms,95%): 0.00 err/s: 2643.60 reconn/s: 0.00
[ 95s ] thds: 22 tps: 0.00 qps: 2582.22 (r/w/o: 0.00/0.00/2582.22) lat (ms,95%): 0.00 err/s: 2582.22 reconn/s: 0.00
[ 100s ] thds: 22 tps: 0.00 qps: 2703.22 (r/w/o: 0.00/0.00/2703.22) lat (ms,95%): 0.00 err/s: 2703.22 reconn/s: 0.00
..... removed lines .... 
[ 935s ] thds: 22 tps: 0.00 qps: 2464.12 (r/w/o: 0.00/0.00/2464.12) lat (ms,95%): 0.00 err/s: 2464.12 reconn/s: 0.00
`

**Comment by akopytov** [comment]
Apparently this is what happens. At some point `mysql_stmt_execute()` fails with a non-zero return code, but for some reasons the server does not indicate any error via `mysql_errno()` / `mysql_error()`. All subsequent attempts to restart transaction fail with the same symptom -- that's why most threads get stuck in the 'restart' loop. Can you verify that with `--mysql-debug`?

It could be a MySQL / Percona XtraDB Cluster bug. Or some problem in the client library. But so far I don't see anything wrong in what sysbench is doing.

**Comment by jmyoda79** [comment]
The debug does support that conclusion : 

`DEBUG: mysql_real_query(0x7f6fb40009c0, "BEGIN", 5) = 0
DEBUG: mysql_store_result(0x7f6fb40009c0) = (nil)
DEBUG: mysql_stmt_execute(0x7f6fb40128b0) = 1
DEBUG: mysql_errno(0x7f6fb40009c0) = 0
DEBUG: mysql_state(0x7f6fb40009c0) = 00000
DEBUG: mysql_error(0x7f6fb40009c0) =
FATAL: mysql_stmt_execute() returned error 0 () for query 'SELECT c FROM sbtest4 WHERE id=?'`

However, the transaction log from the database says that error code 1213 (deadlock) was returned.

**Comment by akopytov** [comment]
So either the server is not correctly propagating the error to the client, or the error happens entirely at the client library level. I'd recommend filing it with Percona.
