### ISSUE TITLE
V1.1.0  run with 8000 threads got an segmentation fault

### ISSUE THREAD

**Issue by lechgif** [akopytov/sysbench#157]
My pc have 16cpus and 64G ram
When i run the program with 8000 threads (with --num-threads=8000), 
an error has occur in   sb_lua.c  file , sb_lua_new_state function

 L = luaL_newstate();   ------ this returns NULL,thread_id aournd 56xx

  luaL_openlibs(L);  --- get segmentation fault

how can i fix this, thanks:)

**Comment by akopytov** [comment]
You can't do much. Lua states require memory, and with 8000 threads they need a lot of memory. You can try disabling the JIT compiler (`--luajit-cmd=off`), but other than I don't have any recommendations.
