### ISSUE TITLE
Two autogen errors on CentOS 7

### ISSUE THREAD

**Issue by paulcaskey** [akopytov/sysbench#158]
```
[sysbench]# ./autogen.sh
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal -I m4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf
configure.ac:48: error: possibly undefined macro: AC_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1
```

(**autoreconf: configure.ac: not using Libtool**)

To fix, I commented this line out of configure.ac:
#AC_PROG_LIBTOOL

I also had to force this:
AC_PROG_RANLIB=/usr/bin/ranlib

```
[sysbench]# autoconf -V
autoconf (GNU Autoconf) 2.69
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later

[sysbench]# head /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
```

Thanks, 
Paul Caskey

**Comment by akopytov** [comment]
libtool is a build requirement for sysbench. You can install all build dependencies on CentOS as documented at https://github.com/akopytov/sysbench#rhelcentos.

Alternatively, you may want to install precompiled binary packages for CentOS 7 from https://packagecloud.io/akopytov/sysbench

**Comment by paulcaskey** [comment]
If libtool is that crucial, I don't know why autoconf would let me proceed without it. But thanks, sorry for the lame case.
