### ISSUE TITLE
sysbench error message accesses uninitialized memory

### ISSUE THREAD

**Issue by akopytov** [akopytov/sysbench#16]
This is a copy of https://bugs.launchpad.net/sysbench/+bug/1529742

```
FATAL: Cannot open file errno = 24 ((
���)

FATAL: Cannot open file errno = 24 (8�6k�)

FATAL: Cannot open file errno = 24 (�
Y�)
```

**Comment by akopytov** [comment]
I'm unable to reproduce this. This is on Ubuntu 14.10 in a read-only directory:

```
user@ubuntu:/tmp/test$ ~/src/git/sysbench/sysbench/sysbench --test=fileio prepare
sysbench 0.5: multi-threaded system evaluation benchmark

128 files, 16384Kb each, 2048Mb total
Creating files for the test...
Extra file open flags: 0
FATAL: Can't open file errno = 13 (Permission denied)
```

**Comment by chadmiller** [comment]
Perhaps it's the path up to this. Create more data files than your ulimit (-n) has the ability to open. For me, this was

sysbench --num-threads=16 --test=fileio --file-total-size=1300G --file-test-mode=rndrw --file-num=13000

**Comment by akopytov** [comment]
Still can't repeat:

```
user@ubuntu:/tmp/test$ ulimit -n 50
user@ubuntu:/tmp/test$ ~/src/git/sysbench/sysbench/sysbench --test=fileio --file-test-mode=rndrw run
...
Doing random r/w test
FATAL: Cannot open file errno = 24 (Too many open files)
```

I'll try more ways to repeat that. What's the OS version in your setup?

**Comment by chadmiller** [comment]
Ubuntu xenial, to be 16.04. sysbench version 0.4.12-1.1 from Debian.

I can still reproduce even with sources. Looks to me like
strerror_r(old_errno, errbuf, sizeof(errbuf));
doesn't fill errbuf. I thought it could be because of an attempt to open
gettext files, but strace doesn't bear that out.

I'll look more later.



On Tue, Dec 29, 2015 at 9:55 AM, Alexey Kopytov <notifications@github.com>
wrote:

> Still can't repeat:
>
> user@ubuntu:/tmp/test$ ulimit -n 50
> user@ubuntu:/tmp/test$ ~/src/git/sysbench/sysbench/sysbench --test=fileio --file-test-mode=rndrw run
> ...
> Doing random r/w test
> FATAL: Cannot open file errno = 24 (Too many open files)
>
> I'll try more ways to repeat that. What's the OS version in your setup?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/akopytov/sysbench/issues/16#issuecomment-167804114>.
>



-- 

Chad Miller
chad.org

**Comment by akopytov** [comment]
Closing, feel free to reopen if can provide more details.
