### ISSUE TITLE
Sysbench 1.0.8 fails to build against mariadb 10.2

### ISSUE THREAD

**Issue by xavierba** [akopytov/sysbench#160]
Hi,
sysbench 1.0.8 was reported to fail to build against mariadb 10.2.
I'll link a patch that fixes the issue (and works with older mariadb, tested with 10.1).

Regards,
Xavier

**Comment by xavierba** [comment]
Link to patch :
http://pkgs.fedoraproject.org/cgit/rpms/sysbench.git/plain/sysbench-1.0.8-fix_build_with_mariadb_10_2.patch

**Comment by akopytov** [comment]
Thanks! The patch has been pushed to both `1.0` and `master`. Would you prefer a 1.0.9 release with this fix?

**Comment by xavierba** [comment]
I'm fine with keeping the patch for now, no need to rush a release.
Thanks for pushing the fix.

**Comment by akopytov** [comment]
Fixed in https://github.com/akopytov/sysbench/commit/0c127582221e829f518e284fefcffa2d9f6d7ae9
