### ISSUE TITLE
sysbench 1.0.x segfault 0.5.x perfect

### ISSUE THREAD

**Issue by chrcoluk** [akopytov/sysbench#163]
FreeBSD 11.x 64bit

sysbench any 1.0.x version segfaults, just simply even with no syntax it segfaults so cannot even display help text.

How can I debug this further thanks?

**Comment by akopytov** [comment]
Can you get a gdb backtrace?

**Comment by chrcoluk** [comment]
ok will do

**Comment by akopytov** [comment]
Closing as no feedback has been provided. Feel free to reopen.

**Comment by chrcoluk** [comment]
I tried to do a backtrace but I seem to have no useful information, sorry.

`root@test:/usr/ports # gdb sysbench
GNU gdb 6.1.1 [FreeBSD]
Copyright 2004 Free Software Foundation, Inc.
GDB is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.
Type "show copying" to see the conditions.
There is absolutely no warranty for GDB.  Type "show warranty" for details.
This GDB was configured as "amd64-marcel-freebsd"...(no debugging symbols found)...
(gdb) run
Starting program: /usr/local/bin/sysbench 
sysbench 1.0.10 (using system LuaJIT 2.0.5)

Reading the script from the standard input:


Program received signal SIGSEGV, Segmentation fault.
0x00000168aebcb1b2 in ?? ()
(gdb) backtrace
#0  0x00000168aebcb1b2 in ?? ()
#1  0x0000000000000000 in ?? ()`

**Comment by chrcoluk** [comment]
Ok I downloaded the src tarball and compiled it.

Wouldnt work with make so grabbed gmake, this required gcc, so grabbed gcc (FreeBSD now uses clang as default compiler), and now the segfault is gone.

I then got the issue reported here https://github.com/akopytov/sysbench/issues/174

So I added -rdynamic to the LDFLAGS in Makefile and compiled again.

Result is it still doesnt work, but I have progress at least now. With the same error in issue 174.  I dont know why the guys who reported the 174 bug dont have the issue I got in this bug report tho.

**Comment by akopytov** [comment]
Hm, I regularly build and run sysbench on macOS, i.e. with BSD make and clang. Can you give me more details on all of the above issues? I.e. commands you type to build, the precise output, etc.?

**Comment by chrcoluk** [comment]
yep

with make (I assume using clang it fails instantly with this.)

This is on FreeBSD 11.1. A fresh system with no customisation's to compiler etc.

`root@test:~/sysbench-1.0.10 # make
Making all in doc
Making all in xsl
touch manual.html
Making all in third_party/luajit
make -C ./luajit clean
make[2]: "/root/sysbench-1.0.10/third_party/luajit/luajit/Makefile" line 93: Missing dependency operator
make[2]: "/root/sysbench-1.0.10/third_party/luajit/luajit/Makefile" line 95: Need an operator
make[2]: "/root/sysbench-1.0.10/third_party/luajit/luajit/Makefile" line 97: Need an operator
make[2]: "/root/sysbench-1.0.10/third_party/luajit/luajit/Makefile" line 100: Missing dependency operator
make[2]: "/root/sysbench-1.0.10/third_party/luajit/luajit/Makefile" line 105: Need an operator
make[2]: Fatal errors encountered -- cannot continue
make[2]: stopped in /root/sysbench-1.0.10/third_party/luajit/luajit
*** Error code 1

Stop.
make[1]: stopped in /root/sysbench-1.0.10/third_party/luajit
*** Error code 1

Stop.
make: stopped in /root/sysbench-1.0.10`

**Comment by chrcoluk** [comment]
So now it works I added the ldflag to the configure command.

./configure --with-extra-ldflags=-rdynamic

**Comment by akopytov** [comment]
My bad, macOS uses GNU make by default, not the BSD one. And LuaJIT indeed requires GNU make.

`--with-extra-ldflags` is a little weird option, it has been removed from `master`. It is fully equivalent to `LDFLAGS=... ./configure ...`. But even that should not be necessary in your case, `-rdynamic` is now added automatically to `LDFLAGS` on FreeBSD. I suspect there was something wrong with your build environment (for example, some targets not being properly rebuilt after `git pull` or something like that). A complete build log would shed some light on that.

Anyway, glad the problem has been resolved.

**Comment by chrcoluk** [comment]
Is the automatic addition after the 1.0.10 release then?

**Comment by akopytov** [comment]
Yes, the automatic addition was added 3 days after releasing 1.0.10. Speaking of which, I'm going to release 1.0.11 today or tomorrow with that fix included.

**Comment by chrcoluk** [comment]
Ok thanks :)
