### ISSUE TITLE
FATAL: error 2026: SSL connection error: SSL_CTX_set_default_verify_paths failed

### ISSUE THREAD

**Issue by liuyunpeng-1** [akopytov/sysbench#166]
使用sysbench 压测 mysql SSL加密链接的性能时 报错FATAL: error 2026: SSL connection error: SSL_CTX_set_default_verify_paths failed 但是我通过mysql客户端链接是没有问题的，有人碰到过这个问题吗？提供一下解决方法。

我试过 把 ca.pem client-cert.pem 放在执行命令的目录下 报出的是同样的错误

**Comment by liuyunpeng-1** [comment]
测试命令
/data/sysbench/bin/sysbench /data/sysbench-master/tests/include/oltp_legacy/oltp.lua --db-driver=mysql  --mysql-host=x.x.x.x  --mysql-user=liu --mysql-password=123456 --mysql-db=dbtest --oltp_tables_count=10 --oltp-table-size=1000000 --num-threads=8 --oltp-read-only=off --report-interval=10 --rand-type=uniform --time=1800 --max-requests=0 --percentile=99 --mysql-ssl=on run

**Comment by akopytov** [comment]
sysbench expects `client-key.pem`, `client-cert.pem` and `cacert.pem` in the current directory when `--mysql-ssl` is used.
