### ISSUE TITLE
warmup maybe problem

### ISSUE THREAD

**Issue by trgfree** [akopytov/sysbench#167]
look the statistic below
when i set --time=30 --warmup-time=30 
the intermediate report's data is just half of the final report's data.
so maybe the final report count the warmup-time's operation

sysbench --report-interval=5 --time=30 --warmup-time=30 --file-total-size=2G --file-test-mode=rndrw fileio run   
sysbench 1.1.0-dcde0d9 (using bundled LuaJIT 2.1.0-beta3)

Running the test with following options:
Number of threads: 1
Warmup time: 30s
Report intermediate results every 5 second(s)
Initializing random number generator from current time

Extra file open flags: 0
128 files, 16MiB each
2GiB total file size
Block size 16KiB
Number of IO requests: 0
Read/Write ratio for combined random IO test: 1.50
Periodic FSYNC enabled, calling fsync() each 100 requests.
Calling fsync() at the end of test, Enabled.
Using synchronous I/O mode
Doing random r/w test
Initializing worker threads...

Threads started!

Warming up for 30 seconds...

[ 5s ] reads: 1.78 MiB/s writes: 1.19 MiB/s fsyncs: 241.26/s latency (ms,95%): 9.560
[ 10s ] reads: 1.58 MiB/s writes: 1.05 MiB/s fsyncs: 230.43/s latency (ms,95%): 9.734
[ 15s ] reads: 1.72 MiB/s writes: 1.14 MiB/s fsyncs: 230.40/s latency (ms,95%): 9.734
[ 20s ] reads: 1.74 MiB/s writes: 1.16 MiB/s fsyncs: 230.40/s latency (ms,95%): 9.734
[ 25s ] reads: 1.76 MiB/s writes: 1.18 MiB/s fsyncs: 230.41/s latency (ms,95%): 9.734

File operations:
    reads/s:                      225.97
    writes/s:                     150.64
    fsyncs/s:                     477.80

Throughput:
    read, MiB/s:                  3.53
    written, MiB/s:               2.35

General statistics:
    total time:                          30.0051s
    total number of events:              12870

Latency (ms):
         min:                                  0.00
         avg:                                  2.33
         max:                                416.73
         95th percentile:                      9.73
         sum:                              29944.11

Threads fairness:
    events (avg/stddev):           12868.0000/0.00
    execution time (avg/stddev):   29.9441/0.00

**Comment by trgfree** [comment]
the param maybe wrong for memory too

sysbench memory --report-interval=1 --warmup-time=3 --memory-block-size=8K --memory-access-mode=seq --memory-oper=read run 
sysbench 1.1.0-dcde0d9 (using bundled LuaJIT 2.1.0-beta3)

Running the test with following options:
Number of threads: 1
Warmup time: 3s
Report intermediate results every 1 second(s)
Initializing random number generator from current time


Running memory speed test with the following options:
  block size: 8KiB
  total size: 102400MiB
  operation: read
  scope: global

Initializing worker threads...

Threads started!

Warming up for 3 seconds...

[ 1s ] 11974.15 MiB/sec
[ 2s ] 12028.65 MiB/sec
[ 3s ] 12063.77 MiB/sec
[ 4s ] 12097.72 MiB/sec
[ 5s ] 12052.23 MiB/sec
Total operations: 8515615 (1543496.45 per second)

66528.24 MiB transferred (12058.57 MiB/sec)


General statistics:
    total time:                          5.5187s
    total number of events:              8515615

Latency (ms):
         min:                                  0.00
         avg:                                  0.00
         max:                                  0.27
         95th percentile:                      0.00
         sum:                               2576.97

Threads fairness:
    events (avg/stddev):           8513132.0000/0.00
    execution time (avg/stddev):   2.5770/0.00

**Comment by akopytov** [comment]
I can reproduce it, thanks.

**Comment by akopytov** [comment]
Should be fixed in HEAD.

**Comment by trgfree** [comment]
the same problem about warmup

the warmup affected the first intermediate report and the number of events

[root@144]~/trg/test# sysbench /root/trg/sysbench/src/lua/oltp_delete.lua --mysql-user=root --mysql-password=0000abc! --mysql-socket=/data/dmain/mysqld.sock --threads=32 --report-interval=10 --rand-type=uniform --time=0 --events=30000 --table_size=1000000 --tables=10 --warmup-time=10 run
sysbench 1.1.0-d724133 (using bundled LuaJIT 2.1.0-beta3)

Running the test with following options:
Number of threads: 32
Warmup time: 10s
Report intermediate results every 10 second(s)
Initializing random number generator from current time


Initializing worker threads...

Threads started!

Warming up for 10 seconds...

[ 10s ] thds: 32 tps: 665.09 qps: 1331.13 (r/w/o: 0.00/1331.13/0.00) lat (ms,95%): 303.33 err/s: 0.00 reconn/s: 0.00
[ 20s ] thds: 32 tps: 436.96 qps: 874.43 (r/w/o: 0.00/874.43/0.00) lat (ms,95%): 204.11 err/s: 0.00 reconn/s: 0.00
[ 30s ] thds: 32 tps: 439.32 qps: 878.14 (r/w/o: 0.00/878.14/0.00) lat (ms,95%): 207.82 err/s: 0.00 reconn/s: 0.00
[ 40s ] thds: 32 tps: 398.53 qps: 796.15 (r/w/o: 0.00/796.15/0.00) lat (ms,95%): 235.74 err/s: 0.00 reconn/s: 0.00
SQL statistics:
    queries performed:
        read:                            0
        write:                           39832
        other:                           0
        total:                           39832
    transactions:                        19922  (412.97 per sec.)
    queries:                             39832  (825.68 per sec.)
    ignored errors:                      0      (0.00 per sec.)
    reconnects:                          0      (0.00 per sec.)

General statistics:
    total time:                          48.2452s
    total number of events:              19922

Latency (ms):
         min:                                  1.15
         avg:                                 77.66
         max:                                760.01
         95th percentile:                    235.74
         sum:                            1547135.13

Threads fairness:
    events (avg/stddev):           622.5625/15.69
    execution time (avg/stddev):   48.3480/0.02

**Comment by trgfree** [comment]
@akopytov 
**the first of intermediate report maybe not affected by warmup ,but other ,please check it** 

[root@144]~/trg/test#   sysbench /root/trg/sysbench/src/lua/oltp_delete.lua --mysql-user=root --mysql-password=0000abc! --mysql-socket=/data/dmain/mysqld.sock --threads=32 --report-interval=10 --rand-type=uniform --time=0 --events=40000 --table_size=1000000 --tables=10 run
sysbench 1.1.0-d724133 (using bundled LuaJIT 2.1.0-beta3)

Running the test with following options:
Number of threads: 32
Report intermediate results every 10 second(s)
Initializing random number generator from current time


Initializing worker threads...

Threads started!

**[ 10s ] thds: 32 tps: 1028.46 qps: 2058.81 (r/w/o: 0.00/2058.81/0.00) lat (ms,95%): 193.38 err/s: 0.00 reconn/s: 0.00**
[ 20s ] thds: 32 tps: 314.71 qps: 629.02 (r/w/o: 0.00/629.02/0.00) lat (ms,95%): 331.91 err/s: 0.00 reconn/s: 0.00
[ 30s ] thds: 32 tps: 431.46 qps: 862.33 (r/w/o: 0.00/862.33/0.00) lat (ms,95%): 231.53 err/s: 0.00 reconn/s: 0.00
[ 40s ] thds: 32 tps: 420.72 qps: 842.44 (r/w/o: 0.00/842.44/0.00) lat (ms,95%): 244.38 err/s: 0.00 reconn/s: 0.00
[ 50s ] thds: 32 tps: 435.80 qps: 870.61 (r/w/o: 0.00/870.61/0.00) lat (ms,95%): 231.53 err/s: 0.00 reconn/s: 0.00
[ 60s ] thds: 32 tps: 425.34 qps: 851.28 (r/w/o: 0.00/851.28/0.00) lat (ms,95%): 272.27 err/s: 0.00 reconn/s: 0.00
[ 70s ] thds: 32 tps: 445.72 qps: 891.05 (r/w/o: 0.00/891.05/0.00) lat (ms,95%): 204.11 err/s: 0.00 reconn/s: 0.00
[ 80s ] thds: 32 tps: 425.99 qps: 852.38 (r/w/o: 0.00/852.38/0.00) lat (ms,95%): 211.60 err/s: 0.00 reconn/s: 0.00
SQL statistics:
    queries performed:
        read:                            0
        write:                           80000
        other:                           0
        total:                           80000
    transactions:                        40000  (492.87 per sec.)
    queries:                             80000  (985.74 per sec.)
    ignored errors:                      0      (0.00 per sec.)
    reconnects:                          0      (0.00 per sec.)

General statistics:
    total time:                          81.1570s
    total number of events:              40000

Latency (ms):
         min:                                  1.19
         avg:                                 64.92
         max:                               1115.49
         95th percentile:                    231.53
         sum:                            2596750.14

Threads fairness:
    events (avg/stddev):           1250.0000/17.38
    execution time (avg/stddev):   81.1484/0.00

**Comment by akopytov** [comment]
What makes you think the first intermediate report is affected by the warmup option? In the latest example I don't even see the `--warmup-time` option being used?

**Comment by trgfree** [comment]
@akopytov 
there are two example above 
please check them
 In the latest example I denied my opinion of the first intermediate report is affected by the warmup option in the example before the latest example 
so ,there are still two issues at all
one is about warmup ,the other one I have no idea.

**Comment by akopytov** [comment]
@trgfree 

I have fixed the `--events` limit to work correctly with `--warmup-time`, please check git HEAD.

But generally, I don't recommend using `--events`. It has a non-trivial performance overhead, and is also causing too much confusion. I believe in most cases limiting by `--time` rather than `--events` should be sufficient.
