### ISSUE TITLE
oltp_delete.lua uses DELETE + INSERT statements

### ISSUE THREAD

**Issue by trgfree** [akopytov/sysbench#168]
[root@144]/ssddata/sysbench#    sysbench /root/trg/sysbench/src/lua/oltp_delete.lua --mysql-user=root --mysql-password=0000abc! --mysql-socket=/ssddata/dmain/mysqld.sock **--threads=32** --report-interval=10 --rand-type=uniform --time=60 --table_size=1000000 --tables=10 prepare
sysbench 1.1.0-d724133 (using bundled LuaJIT 2.1.0-beta3)

Initializing worker threads...

Creating table 'sbtest2'...
Creating table 'sbtest1'...
Creating table 'sbtest9'...
Creating table 'sbtest3'...
Creating table 'sbtest7'...
Creating table 'sbtest5'...
Creating table 'sbtest4'...
Creating table 'sbtest6'...
Creating table 'sbtest8'...
Creating table 'sbtest10'...
Inserting 1000000 records into 'sbtest7'
Inserting 1000000 records into 'sbtest6'
Inserting 1000000 records into 'sbtest1'
Inserting 1000000 records into 'sbtest10'
Inserting 1000000 records into 'sbtest8'
Inserting 1000000 records into 'sbtest3'
Inserting 1000000 records into 'sbtest5'
Inserting 1000000 records into 'sbtest2'
Inserting 1000000 records into 'sbtest4'
Inserting 1000000 records into 'sbtest9'
Creating a secondary index on 'sbtest3'...
Creating a secondary index on 'sbtest2'...
Creating a secondary index on 'sbtest5'...
Creating a secondary index on 'sbtest6'...
Creating a secondary index on 'sbtest1'...
Creating a secondary index on 'sbtest8'...
Creating a secondary index on 'sbtest4'...
Creating a secondary index on 'sbtest7'...
Creating a secondary index on 'sbtest9'...
Creating a secondary index on 'sbtest10'...
[root@144]/ssddata/sysbench# sysbench /root/trg/sysbench/src/lua/oltp_delete.lua --mysql-user=root --mysql-password=0000abc! --mysql-socket=/ssddata/dmain/mysqld.sock **--threads=32** --report-interval=10 --rand-type=uniform --time=60 --table_size=1000000 --tables=10 run
sysbench 1.1.0-d724133 (using bundled LuaJIT 2.1.0-beta3)

Running the test with following options:
Number of threads: 32
Report intermediate results every 10 second(s)
Initializing random number generator from current time

Initializing worker threads...

Threads started!

[ 10s ] thds: 32 tps: 4295.76 qps: 8593.02 (r/w/o: 0.00/8593.02/0.00) lat (ms,95%): 13.70 err/s: 0.00 reconn/s: 0.00
**FATAL: mysql_stmt_execute() returned error 1062 (Duplicate entry '445785' for key 'PRIMARY') for query 'INSERT INTO sbtest1 (id, k, c, pad) VALUES (?, ?, ?, ?)'
FATAL: `thread_run' function failed: /usr/local/share/sysbench/oltp_common.lua:484: SQL error, errno = 1062, state = '23000': Duplicate entry '445785' for key 'PRIMARY'**
[root@144]/ssddata/sysbench#

**Comment by akopytov** [comment]
oltp_delete.lua actually executed `DELETE` + `INSERT` pairs to make the benchmark idempotent. The downside is that INSERT may cause duplicate key errors.

This is also different from the legacy `delete.lua` where only `DELETE` statements were used. I think I'll fix oltp_delete.lua to execute only `DELETE` statements.

**Comment by trgfree** [comment]
maybe you could add trx on it

**Comment by akopytov** [comment]
Wrapping `DELETE` + `INSERT` into a transaction would still make it inconsistent with legacy `delete.lua`, and other OLTP scripts like `oltp_insert.lua`, `oltp_point_select.lua`, `oltp_update_index.lua` and `oltp_update_non_index.lua`

**Comment by trgfree** [comment]
yes, you are right.

**Comment by fxober** [comment]
Alexey , we see these duplicate key errors also on running oltp_rw, has this been reported yet.

Our version of MySQL 8 is: 8.0.11
sysbench: 1.0.15 
output:
Threads started!

FATAL: mysql_stmt_execute() returned error 1062 (Duplicate entry '125943991' for key 'PRIMARY') for query 'INSERT INTO sbtest6 (id, k, c, pad) VALUES (?, ?, ?, ?)'
FATAL: `thread_run' function failed: /usr/share/sysbench/oltp_common.lua:488: SQL error, errno = 1062, state = '23000': Duplicate entry '125943991' for key 'PRIMARY'
Error in my_thread_global_end(): 1 threads didn't exit
sysbench 1.0.15 (using bundled LuaJIT 2.1.0-beta2)

We have not customized oltp_rw.lua in any way. 

Any thoughts on this or prior reports? 

We see this only with higher thread counts, this is using Optane SSDs (extremely fast SSDs) and Skylake CPUs (72 HT cores in total), running on 4.16.8 kernel (Spectre patched with retpoline). CentOS 7.5 build.

Thanks for the feedback.
Frank
