### ISSUE TITLE
a fileio bug

### ISSUE THREAD

**Issue by trgfree** [akopytov/sysbench#169]
@akopytov 
check up the command, the intermediate reports **show reads data but not writes**, I can give you a tip,  it's affected by _--file-io-mode=async_ ,because without this option, it's right.

[root@144]/ssddata/sysbench#     sysbench fileio --file-total-size=200G --file-num=100 --file-block-size=4096 --threads=32 --report-interval=60 --time=1200 --warmup-time=60 --file-test-mode=rndwr --file-io-mode=async run
sysbench 1.1.0-d724133 (using bundled LuaJIT 2.1.0-beta3)

Running the test with following options:
Number of threads: 32
Warmup time: 60s
Report intermediate results every 60 second(s)
Initializing random number generator from current time

Extra file open flags: 0
100 files, 2GiB each
200GiB total file size
Block size 4KiB
Number of IO requests: 0
Read/Write ratio for combined random IO test: 1.50
Periodic FSYNC enabled, calling fsync() each 100 requests.
Calling fsync() at the end of test, Enabled.
Using asynchronous I/O mode
Doing random write test
Initializing worker threads...

Threads started!

Warming up for 60 seconds...

[ 60s ] reads: 563.39 MiB/s writes: 0.00 MiB/s fsyncs: 0.00/s latency (ms,95%): 0.527
[ 120s ] reads: 566.71 MiB/s writes: 0.00 MiB/s fsyncs: 0.00/s latency (ms,95%): 0.527
[ 180s ] reads: 565.79 MiB/s writes: 0.00 MiB/s fsyncs: 0.00/s latency (ms,95%): 0.527
[ 240s ] reads: 567.06 MiB/s writes: 0.00 MiB/s fsyncs: 0.00/s latency (ms,95%): 0.517
 [ 300s ] reads: 566.49 MiB/s writes: 0.00 MiB/s fsyncs: 0.00/s latency (ms,95%): 0.527
[ 360s ] reads: 566.65 MiB/s writes: 0.00 MiB/s fsyncs: 0.00/s latency (ms,95%): 0.527
[ 420s ] reads: 566.82 MiB/s writes: 0.00 MiB/s fsyncs: 0.00/s latency (ms,95%): 0.527
[ 480s ] reads: 566.59 MiB/s writes: 0.00 MiB/s fsyncs: 0.00/s latency (ms,95%): 0.517
[ 540s ] reads: 566.37 MiB/s writes: 0.00 MiB/s fsyncs: 0.00/s latency (ms,95%): 0.517
 [ 600s ] reads: 566.64 MiB/s writes: 0.00 MiB/s fsyncs: 0.00/s latency (ms,95%): 0.527
[ 660s ] reads: 566.98 MiB/s writes: 0.00 MiB/s fsyncs: 0.00/s latency (ms,95%): 0.527
[ 720s ] reads: 565.88 MiB/s writes: 0.00 MiB/s fsyncs: 0.00/s latency (ms,95%): 0.527
[ 780s ] reads: 567.17 MiB/s writes: 0.00 MiB/s fsyncs: 0.00/s latency (ms,95%): 0.527
[ 840s ] reads: 566.89 MiB/s writes: 0.00 MiB/s fsyncs: 0.00/s latency (ms,95%): 0.527
 [ 900s ] reads: 566.44 MiB/s writes: 0.00 MiB/s fsyncs: 0.00/s latency (ms,95%): 0.527
[ 960s ] reads: 565.82 MiB/s writes: 0.00 MiB/s fsyncs: 0.00/s latency (ms,95%): 0.527
[ 1020s ] reads: 566.58 MiB/s writes: 0.00 MiB/s fsyncs: 0.00/s latency (ms,95%): 0.517
[ 1080s ] reads: 566.87 MiB/s writes: 0.00 MiB/s fsyncs: 0.00/s latency (ms,95%): 0.517
[ 1140s ] reads: 566.52 MiB/s writes: 0.00 MiB/s fsyncs: 0.00/s latency (ms,95%): 0.527
 [ 1200s ] reads: 565.40 MiB/s writes: 0.00 MiB/s fsyncs: 0.00/s latency (ms,95%): 0.527

File operations:
    reads/s:                      0.00
    writes/s:                     145013.06
    fsyncs/s:                     0.00

Throughput:
    read, MiB/s:                  566.46
    write, MiB/s:                 0.00

General statistics:
    total time:                          1200.0582s
    total number of events:              348045035

Latency (ms):
         min:                                  0.00
         avg:                                  0.11
         max:                                 17.04
         95th percentile:                      0.53
         sum:                            37831115.39

Threads fairness:
    events (avg/stddev):           10876361.9375/57954.21
    execution time (avg/stddev):   1182.2224/0.12

**Comment by akopytov** [comment]
Thanks. Should be fixed in 'master'.
