### ISSUE TITLE
Commit feb0346 removed latency sum from reporting

### ISSUE THREAD

**Issue by pfriedenbach** [akopytov/sysbench#173]
Alexey,
Your feb0346 commit removed the latency sum from the test reporting.  Unfortunately I often rely on that value when I'm using sysbench.  In particular, when running multiple drivers in parallel, I use the sum of the latency across the drivers and the sum of the transactions across the drivers to calculate the average latency for the test.  Could you please consider adding the sum of the latency back to the reporting.
Thank you,
Peter Friedenbach

**Comment by akopytov** [comment]
Peter,
My bad, I was trying to unclutter the report and I didn't know someone relies on the 'sum' field. I'm going to add it back shortly. Thanks for letting me know.
