### ISSUE TITLE
Oracle DB support

### ISSUE THREAD

**Issue by atishp04** [akopytov/sysbench#175]
Hi,
Does sysbench support Oracle Database with all features? I see a readme about Oracle.
https://github.com/akopytov/sysbench/blob/master/README-Oracle.md

But it also says to install cuda which surprises me. Is it mandatory ?
Once I configure sysbench with Oracle DB, do I just need to change following arguments (from mysql run)
--db-driver=mysql --mysql-host=localhost --mysql-user=root 
--mysql-db=test1

Regards,
Atish

**Comment by akopytov** [comment]
Unfortunately, I don't have capacity to test and maintain the Oracle DB driver as I have never used it myself, so it is in the unsupported status. The instructions have been contributed by a user, I have just included whatever worked for him.

If something doesn't work for you, there's not much I can do to help. But I would appreciate patches, corrections and suggestions for improvements.

**Comment by atishp04** [comment]
Thanks for the prompt response. I will give it a shot and update the instructions if it will work.

Regards,
Atish
