### ISSUE TITLE
Memory test doesn't do anything; is this normal?

### ISSUE THREAD

**Issue by seanspotatobusiness** [akopytov/sysbench#176]
Is the below output normal? I expected some statistics regarding how my memory was performing.

Wyse V90L thin client with VIA Eden 800 MHz CPU, 1 GB DDR2 SODIMM at 533 MHz running antiX 16.2.

[code]sean@Teleprompter:~
$ sysbench --test=memory run
sysbench 0.4.12:  multi-threaded system evaluation benchmark

Running the test with following options:
Number of threads: 1

Doing memory operations speed test
Memory block size: 1K

Memory transfer size: 0M

Memory operations type: write
Memory scope type: global
Threads started!
Done.

Operations performed: 0 (    0.00 ops/sec)

0.00 MB transferred (0.00 MB/sec)

Test execution summary:
    total time:                          0.0043s
    total number of events:              0
    total time taken by event execution: 0.0000
    per-request statistics:
         min:                            18446744073709.55ms
         avg:                                  0.00ms
         max:                                  0.00ms

Threads fairness:
    events (avg/stddev):           0.0000/0.00
    execution time (avg/stddev):   0.0000/0.00

sean@Teleprompter:~
$ [/code]

**Comment by akopytov** [comment]
sysbench 0.4.12 is more than 10 years old. And yes, there were issues with the memory test with old versions. You want to install a recent version: https://github.com/akopytov/sysbench#installing-from-binary-packages
