### ISSUE TITLE
Graphing with Sysbench

### ISSUE THREAD

**Issue by mitchelp** [akopytov/sysbench#177]
Hi, i'm using sysbench for quite some time now.
But I was wondering if there is any way to put the results in a graph? Any known solutions?
In the past I made use of: https://github.com/tsuna/sysbench-tools but this doesn't work anymore.

Hope to get some help here. If it's not wanted you can close the issue.

Thanks 👍

**Comment by akopytov** [comment]
Currently I use my own combination of shell scripts and R programs to create charts for my purposes. I don't think they would be useful for other people without heavy modifications.

I'd like to have some functionality in sysbench to facilitate graphing. I think introducing custom reports in 1.0 was a good first step. By the way, you can use JSON reporter (see an [example here](https://github.com/akopytov/sysbench/blob/1.0/src/lua/internal/sysbench.lua#L91)) to make sysbench-tools work with minimal efforts. After all, sysbench-tools convert sysbench output to JSON and then use JavaScript to plot it. So the only thing you need is to figure out the JSON format expected by `sysbench.html`, then make sure sysbench is producing the output in that format by implementing your own reporter based on `sysbench.report_json`.

But I would also like to implement some automation around existing functionality, probably as a Lua module, and make it good enough for the majority of users. So seeing examples of how people usually graph their sysbench results is helpful. Thanks for introducing me to sysbench-tools.
