### ISSUE TITLE
compile sysbench 1.0.10 with oracle client, but failed

### ISSUE THREAD

**Issue by wangzhijun2005** [akopytov/sysbench#179]
Follow the guide https://github.com/akopytov/sysbench/blob/master/README-Oracle.md to compile sysbench 1.0.10, but failed. Compare the source code against sysbench 0.5, and found struct db_result_set_t is changed to db_result_t.

=============================================
In file included from /usr/include/oracle/12.1/client64/oci.h:3488:0,
                 from drv_oracle.c:30:
/usr/include/oracle/12.1/client64/ociap.h:10858:1: warning: function declaration isn't a prot
 void OCIThreadProcessInit();
 ^
/usr/include/oracle/12.1/client64/ociap.h:10864:1: warning: function declaration isn't a prot
 boolean OCIThreadIsMulti();
 ^
In file included from /usr/include/oracle/12.1/client64/oci.h:3491:0,
                 from drv_oracle.c:30:
/usr/include/oracle/12.1/client64/ocixmldb.h:208:1: warning: function declaration isn't a pro
 ub1 OCIXmlGetDiffBndVersion();
 ^
drv_oracle.c:51:3: warning: initialization makes pointer from integer without a cast [enabled
   {"oracle-user", "Oracle user", SB_ARG_TYPE_STRING, "sbtest"},
   ^
drv_oracle.c:51:3: warning: (near initialization for 'ora_drv_args[0].value') [enabled by def
drv_oracle.c:51:3: error: incompatible types when initializing type 'enum <anonymous>' using
drv_oracle.c:51:3: warning: missing initializer for field 'type' of 'sb_arg_t' [-Wmissing-fie
In file included from drv_oracle.c:32:0:
../../../src/sb_options.h:60:22: note: 'type' declared here
   sb_arg_type_t      type;
                      ^
drv_oracle.c:52:3: warning: initialization makes pointer from integer without a cast [enabled
   {"oracle-password", "Oracle password", SB_ARG_TYPE_STRING, ""},
   ^
drv_oracle.c:52:3: warning: (near initialization for 'ora_drv_args[1].value') [enabled by def
drv_oracle.c:52:3: error: incompatible types when initializing type 'enum <anonymous>' using
drv_oracle.c:52:3: warning: missing initializer for field 'type' of 'sb_arg_t' [-Wmissing-fie
In file included from drv_oracle.c:32:0:
../../../src/sb_options.h:60:22: note: 'type' declared here
   sb_arg_type_t      type;
                      ^
drv_oracle.c:53:3: warning: initialization makes pointer from integer without a cast [enabled
   {"oracle-db", "Oracle database name", SB_ARG_TYPE_STRING, "sbtest"},
   ^
drv_oracle.c:53:3: warning: (near initialization for 'ora_drv_args[2].value') [enabled by def
drv_oracle.c:53:3: error: incompatible types when initializing type 'enum <anonymous>' using
drv_oracle.c:53:3: warning: missing initializer for field 'type' of 'sb_arg_t' [-Wmissing-fie
In file included from drv_oracle.c:32:0:
../../../src/sb_options.h:60:22: note: 'type' declared here
   sb_arg_type_t      type;
                      ^
drv_oracle.c:55:3: error: incompatible types when initializing type 'enum <anonymous>' using
   {NULL, NULL, SB_ARG_TYPE_NULL, NULL}
   ^
drv_oracle.c:55:3: warning: missing initializer for field 'type' of 'sb_arg_t' [-Wmissing-fie
In file included from drv_oracle.c:32:0:
../../../src/sb_options.h:60:22: note: 'type' declared here
   sb_arg_type_t      type;
                      ^
drv_oracle.c:208:5: error: unknown field 'store_results' specified in initializer
     .store_results = ora_drv_store_results,
     ^
drv_oracle.c:208:5: warning: initialization from incompatible pointer type [enabled by defaul
drv_oracle.c:208:5: warning: (near initialization for 'oracle_driver.ops.thread_done') [enabl
drv_oracle.c: In function 'ora_drv_init':
drv_oracle.c:241:11: warning: pointer targets in assignment differ in signednes
   args.db = sb_get_value_string("oracle-db");
           ^
drv_oracle.c: In function 'ora_drv_connect':
drv_oracle.c:308:3: warning: pointer targets in passing argument 1 of 'strlen'
   rc = OCIServerAttach(ora_con->srvhp, ora_con->errhp, args.db, strlen(args.db
   ^
In file included from drv_oracle.c:24:0:
/usr/include/string.h:395:15: note: expected 'const char *' but argument is of
 extern size_t strlen (const char *__s)
               ^
drv_oracle.c: In function 'ora_drv_prepare':
drv_oracle.c:470:27: warning: pointer targets in passing argument 3 of 'OCIStmt
                           OCI_NTV_SYNTAX, OCI_DEFAULT);
                           ^
In file included from /usr/include/oracle/12.1/client64/oci.h:3488:0,
                 from drv_oracle.c:30:
/usr/include/oracle/12.1/client64/ociap.h:7205:9: note: expected 'const OraText
 sword   OCIStmtPrepare   (OCIStmt *stmtp, OCIError *errhp, const OraText *stmt
         ^
drv_oracle.c:403:64: warning: unused parameter 'len' [-Wunused-parameter]
 int ora_drv_prepare(db_stmt_t *stmt, const char *query, size_t len)
                                                                ^
drv_oracle.c: In function 'ora_drv_store_results':
drv_oracle.c:783:33: error: 'db_result_t' has no member named 'connection'
   db_conn_t        *db_conn = rs->connection;
                                 ^
drv_oracle.c:783:31: warning: initialization from incompatible pointer type [en
   db_conn_t        *db_conn = rs->connection;
                               ^
drv_oracle.c:835:18: warning: pointer targets in assignment differ in signednes
     column->name = (char *)malloc(col_len + 1);
                  ^
drv_oracle.c:838:5: warning: pointer targets in passing argument 1 of '__builti
     strncpy(column->name, fnamep, col_len + 1);
     ^
drv_oracle.c:838:5: note: expected 'char *' but argument is of type 'text *'
drv_oracle.c:838:5: warning: pointer targets in passing argument 2 of '__builti
drv_oracle.c:838:5: note: expected 'const char *' but argument is of type 'text
drv_oracle.c: At top level:
drv_oracle.c:1062:16: warning: no previous prototype for 'get_db_bind_type' [-W
 db_bind_type_t get_db_bind_type(sword type)
                ^
make[3]: *** [libsboracle_a-drv_oracle.o] Error 1
make[3]: Leaving directory `/home/luke/sysbench-1.0.10/src/drivers/oracle'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/home/luke/sysbench-1.0.10/src/drivers'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/luke/sysbench-1.0.10/src'
make: *** [all-recursive] Error 1

**Comment by akopytov** [comment]
Hello,

Support for Oracle DBMS has been dropped in sysbench 1.0, but sysbench 0.5 should still work. I added a warning to https://github.com/akopytov/sysbench/blob/1.0/README-Oracle.md so it is a little less confusing

**Comment by Sinoprise** [comment]
sysbench 0.5 (Github) ，Oracle 12.1 and Opensuse 42.3
----------------------------------------------------------------------
andy@linux:~> ./oracle-prepare.sh 
sysbench 0.5:  multi-threaded system evaluation benchmark

Creating table 'sbtest1'...
Unknown database driver: oracle

how to fix? 3Q
