### ISSUE TITLE
Add support for CockroachDB (PostgreSQL protocol)

### ISSUE THREAD

**Issue by amq** [akopytov/sysbench#180]
CockroachDB is a new open-source datastore which is using the PostgreSQL wire protocol, inspired by [Google Spanner](https://cloud.google.com/spanner/)

It went GA in [May](https://www.cockroachlabs.com/blog/cockroachdb-1-0-release/) and recently got a second major release [1.1](https://www.cockroachlabs.com/blog/cockroachdb-1dot1/)

Since it is so fresh, benchmarking is essential and it would be ideal to use an industry-standard tool like sysbench.

Most of the sysbench functionality already works, such as:

```
sysbench --db-driver=pgsql --pgsql-host=cockroachdb --pgsql-port=26257 \
--pgsql-user=root --table-size=1000000 \
oltp_read_write prepare
```

```
sysbench --db-driver=pgsql --pgsql-host=cockroachdb --pgsql-port=26257 \
--pgsql-user=root --max-time=60 \
oltp_read_write run
```

What doesn't work, for example, is using multiple threads:

```
sysbench --db-driver=pgsql --pgsql-host=cockroachdb --pgsql-port=26257 \
--pgsql-user=root --max-time=60 --num-threads=4 \
oltp_read_write run
```

Which returns:

```
FATAL: PQexecPrepared() failed: 7 restart transaction: HandledRetryableTxnError: TransactionRetryError: retry txn (RETRY_SERIALIZABLE): "sql txn" id=95c891bf key=/Table/51/1/4982/0 rw=true pri=0.02449537 iso=SERIALIZABLE stat=PENDING epo=0 ts=1510501967.622759247,1 orig=1510501967.603494873,0 max=1510501967.603494873,0 wto=false rop=false seq=14
FATAL: `thread_run' function failed: /usr/share/sysbench/oltp_common.lua:405: SQL error, errno = 0, state = '40001': restart transaction: HandledRetryableTxnError: TransactionRetryError: retry txn (RETRY_SERIALIZABLE): "sql txn" id=95c891bf key=/Table/51/1/4982/0 rw=true pri=0.02449537 iso=SERIALIZABLE stat=PENDING epo=0 ts=1510501967.622759247,1 orig=1510501967.603494873,0 max=1510501967.603494873,0 wto=false rop=false seq=14
```

A possible cause and solution is indicated here: https://github.com/cockroachdb/docs/issues/1587 and here: https://www.cockroachlabs.com/docs/stable/transactions.html#transaction-retries

**Comment by akopytov** [comment]
This particular problem has been fixed in both 1.0 and master branches. So the OLTP benchmarks appear to be functional with CockroachDB.

However, I ran the sysbench test suite against CockroachDB and got a few failures. They look benign (different error messages or SQL states returned by CockroachDB as compared to PostgeSQL). Will try to find some bandwidth to fix them later. Patches are welcome too.
