### ISSUE TITLE
sysbench complilation failed on ppc64le

### ISSUE THREAD

**Issue by harihare** [akopytov/sysbench#182]
latest  version failed to compile on ppc64le with following error
lj_arch.h:428:2: error: #error "No support for PowerPC 64 bit mode (yet)"
 #error "No support for PowerPC 64 bit mode (yet)"
  ^
Compilation of 4.12 or 0.4 branch worked fine with out issues.

**Comment by akopytov** [comment]
Correct, PPC is not supported by LuaJIT and thus, sysbench. Which has already been reported as #129 and #154. I think I can fix it at least partially, but I need access to a ppc64le machine. I'm also happy to accept patches.

Closing this one as a duplcate of #129.
