### ISSUE TITLE
Support variable-length random string generation

### ISSUE THREAD

**Issue by jaypipes** [akopytov/sysbench#184]
Feature request, with code coming.

Currently, the `sysbench.rand.string()` Lua function takes a `fmt` parameter and only supports a fixed string length. It would be nice to have a `sysbench.rand.varstring` function that returned a variable-length string of ASCII characters. This is useful for testing `VARCHAR` column performance and generated a (little more) realistic string data set.

**Comment by akopytov** [comment]
This could also be implemented purely in Lua:

```lua
local s = sysbench.rand.string(string.rep('@', sysbench.rand.default(10, 100)))
```
Pros:
- no need to modify sysbench
- can use non-uniform distributions for string lengths (but not characters)

Cons:
- slower (2.3 times slower than the C version with the above parameters)
- limited to either letters or digits

So in some cases a builtin function may be preferable. Thanks for the contribution!
