### ISSUE TITLE
help, not bug

### ISSUE THREAD

**Issue by trgfree** [akopytov/sysbench#190]
how can I make a bin package for sysbench.
because test computer can not connected to the Internet.
thank you.

**Comment by akopytov** [comment]
Try `make dist`.

**Comment by trgfree** [comment]
I attempt "make dist", but encounter a problem . see bold characters below . 
I edit the Makefile set PACKAGE = sbh, and it works.
then a sbh-1.1.0.tar.gz generated. after i tar -xvf sbh-1.1.0.tar.gz. I find i can't use it.
What I should do next?

I just want to copy a binary package to a new computer,without network and some components. after I set the env vairialbes PATH , I could use sysbench normally.

[betadmin@SpringCloud05 sysbench]$ make dist
.
.
.
**tardir=sysbench-1.1.0 && /bin/sh /home/betadmin/sysbench/config/missing --run tar chof - "$tardir" | GZIP=--best gzip -c >sysbench-1.1.0.tar.gz
tar: sysbench-1.1.0/third_party/concurrency_kit/ck/regressions/ck_barrier/validate/barrier_dissemination.c: file name is too long (max 99); not dumped
tar: Exiting with failure status due to previous errors
gtar: sysbench-1.1.0/third_party/concurrency_kit/ck/regressions/ck_barrier/validate/barrier_dissemination.c: file name is too long (max 99); not dumped
gtar: Exiting with failure status due to previous errors
{ test ! -d "sysbench-1.1.0" || { find "sysbench-1.1.0" -type d ! -perm -200 -exec chmod u+w {} ';' && rm -fr "sysbench-1.1.0"; }; }**
[betadmin@SpringCloud05 sysbench]$  

**[betadmin@SpringCloud05 sysbench]$ ll sbh-1.1.0.tar.gz
-rw-r--r--. 1 betadmin bet 1925042 Nov 30 16:35 sbh-1.1.0.tar.gz**
