### ISSUE TITLE
Is it possible to add a Debian Stretch .deb in packagecloud ?

### ISSUE THREAD

**Issue by nicolas707** [akopytov/sysbench#192]
Maybe not so easy as libmysqlclient18 is not any more in Debian 9 repos. So maybe at least a .deb without mysql support will be possible ?
Thanks

**Comment by akopytov** [comment]
I have tried adding Stretch to the build matrix a few times and got some obscure build failures, most likely related to packpack. Will look again.

**Comment by nicolas707** [comment]
Okay, Thanks
