### ISSUE TITLE
qeustion about the mutex loop time between intel and aarch64 ？

### ISSUE THREAD

**Issue by jaredzhu** [akopytov/sysbench#202]
while I running sysbench mutex test, I found much different result between intel skylake 6148 and  aarch64 server.
the test cmd ： sysbench --num-threads=512 --max-requests=2000  --test=mutex --mutex-num=1024 --mutex-locks=10000 --mutex-loops=15000 run

while I checked the sysbench code ， I found the function mutex_execute_event use ck_pr_barrier() as the loop time. but the intel and the aarch64 is much different while execute the ck_pr_barrier(), so is there have some mistake ?

**Comment by akopytov** [comment]
`ck_pr_barrier()` is a compiler barrier and does not result in any code being emitted by the compiler. It is literally zero instructions on any architecture, including x86 and aarch64.
