### ISSUE TITLE
OLTP test for thread 1000 meet FATAL: `thread_run' function failed error

### ISSUE THREAD

**Issue by jowang111** [akopytov/sysbench#203]
while running oltp test for thread more than 1k. I meet below error， can anyone help on this? I have confirmed it is not host client /MySQL issue.

FATAL: unable to connect to MySQL server on host
FATAL: error 2005: Unknown MySQL server host '127.0.0.1'
FATAL: `thread_run' function failed: sysbench/tests/include/oltp_legacy/oltp.lua:43: Failed to connect to the database

**Comment by jowang111** [comment]
MySQL is AWS RDS. I heard of that there is thread limit on thread from same IP, is that true?

**Comment by akopytov** [comment]
Apparently no one has an answer to the question, closing.

**Comment by ShawnXxy** [comment]
Tested on Azure but got the same error when threads greater than 1000
