### ISSUE TITLE
Testing the ProxySQL backend error

### ISSUE THREAD

**Issue by zhjwpku** [akopytov/sysbench#204]
➜  ~ sysbench --db-driver=mysql --table-size=100000 --tables=24 --threads=4 \
--mysql-host=10.0.63.204 --mysql-port=6033 --mysql-user=root --mysql-password=p4ssw0rd \
 oltp_read_write prepare
sysbench 1.0.11 (using bundled LuaJIT 2.1.0-beta2)

Initializing worker threads...

Creating table 'sbtest2'...Creating table 'sbtest3'...

Creating table 'sbtest4'...
Creating table 'sbtest1'...
Inserting 100000 records into 'sbtest3'
Inserting 100000 records into 'sbtest2'
Inserting 100000 records into 'sbtest4'
Inserting 100000 records into 'sbtest1'
Creating a secondary index on 'sbtest3'...
Creating table 'sbtest7'...
Inserting 100000 records into 'sbtest7'
Creating a secondary index on 'sbtest2'...
Creating table 'sbtest6'...
Inserting 100000 records into 'sbtest6'
Creating a secondary index on 'sbtest1'...
Creating table 'sbtest5'...
Inserting 100000 records into 'sbtest5'
Creating a secondary index on 'sbtest4'...
Creating table 'sbtest8'...
Inserting 100000 records into 'sbtest8'
Creating a secondary index on 'sbtest7'...
Creating table 'sbtest11'...
Inserting 100000 records into 'sbtest11'
Creating a secondary index on 'sbtest6'...
Creating table 'sbtest10'...
Inserting 100000 records into 'sbtest10'
Creating a secondary index on 'sbtest5'...
Creating table 'sbtest9'...
Inserting 100000 records into 'sbtest9'
Creating a secondary index on 'sbtest8'...
Creating table 'sbtest12'...
Inserting 100000 records into 'sbtest12'
Creating a secondary index on 'sbtest11'...
Creating table 'sbtest15'...
Inserting 100000 records into 'sbtest15'
Creating a secondary index on 'sbtest10'...
Creating table 'sbtest14'...
Inserting 100000 records into 'sbtest14'
Creating a secondary index on 'sbtest9'...
Creating table 'sbtest13'...
Inserting 100000 records into 'sbtest13'
Creating a secondary index on 'sbtest12'...
Creating table 'sbtest16'...
Inserting 100000 records into 'sbtest16'
Creating a secondary index on 'sbtest15'...
Creating table 'sbtest19'...
Inserting 100000 records into 'sbtest19'
Creating a secondary index on 'sbtest14'...
Creating table 'sbtest18'...
Inserting 100000 records into 'sbtest18'
Creating a secondary index on 'sbtest13'...
Creating table 'sbtest17'...
Inserting 100000 records into 'sbtest17'
Creating a secondary index on 'sbtest16'...
Creating table 'sbtest20'...
Inserting 100000 records into 'sbtest20'
Creating a secondary index on 'sbtest19'...
Creating table 'sbtest23'...
Inserting 100000 records into 'sbtest23'
Creating a secondary index on 'sbtest18'...
Creating table 'sbtest22'...
Inserting 100000 records into 'sbtest22'
Creating a secondary index on 'sbtest17'...
Creating table 'sbtest21'...
Inserting 100000 records into 'sbtest21'
Creating a secondary index on 'sbtest20'...
Creating table 'sbtest24'...
Inserting 100000 records into 'sbtest24'
Creating a secondary index on 'sbtest23'...
Creating a secondary index on 'sbtest22'...
Creating a secondary index on 'sbtest21'...
Creating a secondary index on 'sbtest24'...
➜  ~ sysbench --db-driver=mysql --table-size=100000 --tables=24 --threads=4 \
--mysql-host=10.0.63.204 --mysql-port=6033 --mysql-user=root --mysql-password=p4ssw0rd \
 oltp_read_write run
sysbench 1.0.11 (using bundled LuaJIT 2.1.0-beta2)

Running the test with following options:
Number of threads: 4
Initializing random number generator from current time

Initializing worker threads...

Threads started!

FATAL: mysql_stmt_execute() returned error 1146 (Table 'sbtest.sbtest22' doesn't exist) for query 'SELECT c FROM sbtest22 WHERE id=?'
FATAL: `thread_run' function failed: .../Cellar/sysbench/1.0.11_1/share/sysbench/oltp_common.lua:415: SQL error, errno = 1146, state = '42S02': Table 'sbtest.sbtest22' doesn't exist
FATAL: mysql_stmt_execute() returned error 1146 (Table 'sbtest.sbtest17' doesn't exist) for query 'SELECT c FROM sbtest17 WHERE id=?'
FATAL: `thread_run' function failed: .../Cellar/sysbench/1.0.11_1/share/sysbench/oltp_common.lua:415: SQL error, errno = 1146, state = '42S02': Table 'sbtest.sbtest17' doesn't exist
FATAL: mysql_stmt_execute() returned error 1146 (Table 'sbtest.sbtest21' doesn't exist) for query 'SELECT SUM(k) FROM sbtest21 WHERE id BETWEEN ? AND ?'
FATAL: `thread_run' function failed: .../Cellar/sysbench/1.0.11_1/share/sysbench/oltp_common.lua:428: SQL error, errno = 1146, state = '42S02': Table 'sbtest.sbtest21' doesn't exist
➜  ~

I am testing the proxysql as a backend, sometimes I got the error above, can anybody help?

Can anybody help?

**Comment by zhjwpku** [comment]
I am not sure this bug belongs to sysbench, I test several MySQL proxy, like [Atlas](https://github.com/Qihoo360/Atlas), [MaxScale][https://github.com/mariadb-corporation/MaxScale] and [ProxySQL][https://github.com/sysown/proxysql].  Only ProxySQL has the problem.

**Comment by akopytov** [comment]
I guess you need to make sure the tables are created on all backend servers. I'm not sure if ProxySQL provides any ways to automate that, but you can always manually run `sysbench --mysql-host=... prepare` on each host before running the benchmark against ProxySQL.

**Comment by zhjwpku** [comment]
@akopytov thanks for the quick reply, I have checked the backend servers. The tables did exist.

I will issue a question to the ProxySQL community.

Thanks again.
