### ISSUE TITLE
what does each choice  of --rand-type mean?

### ISSUE THREAD

**Issue by rainnnnny** [akopytov/sysbench#207]
mainly for 'uniform' and 'special',   no doc found and hard to search...

**Comment by akopytov** [comment]
- Uniform distribution: https://en.wikipedia.org/wiki/Discrete_uniform_distribution
- Guassian (aka Normal) distribution: https://en.wikipedia.org/wiki/Normal_distribution
- Pareto distribution: https://en.wikipedia.org/wiki/Pareto_distribution
- Zipfian distribution: https://en.wikipedia.org/wiki/Zipf%27s_law

As to the 'special' distribution. It is unscientific and I'm going to remove it in the next major release.
