### ISSUE TITLE
Huge performance difference of aarch32 & aarch64 on the same system

### ISSUE THREAD

**Issue by zyxmon** [akopytov/sysbench#209]
I have compiled the same (0.5) sysbench version for armv7 and armv8 architecure. The results of running sysbench on the same system (QNAP NAS with Realtek RTD1295 Quad-Core ARM Cortex-A53 Processor @ 1.4GHz) is very very very different with 32 & 64 bit versions. Running other tests  (echo "scale=5000; a(1)*4" | bc -l) or openssl benchmarks give several percentage difference.
What is wrong with 32 bit sysbench version on aarch64?

**Comment by zyxmon** [comment]
Here are two sysbench runs. The first one is 64 bit version, the second one is 32 bit
```
# sysbench --test=cpu --cpu-max-prime=20000 run
sysbench 0.5:  multi-threaded system evaluation benchmark

Running the test with following options:
Number of threads: 1
Random number generator seed is 0 and will be ignored


Prime numbers limit: 20000

Initializing worker threads...

Threads started!


General statistics:
    total time:                          83.7920s
    total number of events:              10000
    total time taken by event execution: 83.7733s
    response time:
         min:                                  8.36ms
         avg:                                  8.38ms
         max:                                 14.37ms
         approx.  95 percentile:               8.39ms

Threads fairness:
    events (avg/stddev):           10000.0000/0.00
    execution time (avg/stddev):   83.7733/0.00
	
	
------------------------------

# sysbench --test=cpu --cpu-max-prime=20000 run
sysbench 0.5:  multi-threaded system evaluation benchmark

Running the test with following options:
Number of threads: 1
Random number generator seed is 0 and will be ignored


Prime numbers limit: 20000

Initializing worker threads...

Threads started!


General statistics:
    total time:                          1990.2294s
    total number of events:              10000
    total time taken by event execution: 1990.0771s
    response time:
         min:                                198.58ms
         avg:                                199.01ms
         max:                                228.78ms
         approx.  95 percentile:             199.32ms

Threads fairness:
    events (avg/stddev):           10000.0000/0.00
    execution time (avg/stddev):   1990.0771/0.00

```

**Comment by zyxmon** [comment]
@father-mande was the first to discover this. He can give more results (with different sysbench version). The same behaviour is observed by @father-mande in qemu (???) chroot environment.

**Comment by akopytov** [comment]
@zyxmon that doesn't ring any bells. I don't have access to the same aarch64 hardware. Was the armv7 build compiled with hard float?

**Comment by zyxmon** [comment]
The same behaviour was observed by @father-made in qemu environment. Please contact him if you need details. He used ubuntu packages. He also compiled sysbench himself.
armv7 was compiled with soft float. But 24 times difference for binaries I have compiled or ubuntu packages benchmarks in qemu environment look very strange.
Other benchmarks  http://forums.zyxmon.org/viewtopic.php?f=10&t=5382 (Russian) show very small difference for 32 and 64 bit binaries compiled the same way as sysbench.
I do not think sysbench can be used to benchmark arm systems.

**Comment by akopytov** [comment]
Well, sysbench is successfully used to benchmark **MySQL** on arm systems. The cpu microbenchmark is very naive and simplstic. It was implemented many years ago just get some simple bogomips-like metric about CPU performance. I know that many people try to use it for something it has never been designed for.

With that said, it wouldn't be too hard to fix it to be more representative of raw CPU power. It's just not high on my list of priorities. Meanwhile, one could use other benchmark tools that have been specifically designed to microbenchmark CPU operations.

I'm also happy to debug this specific problem with armv7 builds, but I would need your help. My current guess is that soft float is to blame here, because the code uses sqrt(). Can you get some perf data to verify that?

**Comment by zyxmon** [comment]
I hope @father_mande has no objection for quoting him here:

> Yes it's very confusing ... 
> To be sure it's NOT my own port of sysbench (but I don't have control on the code inside ;-) )
> I have do a change in my strategy ...
> 
> I have create 2 chroot based on Ubuntu 16.04, one with aarch64 (64 bits compatible with A53 ... so TS-128A) the other with armhf (32 bits compatible armv7 for TS-x31+) 
> I have configured exactly with same basic things the two
> I have installed the Ubuntu sysbench using apt-get
> Then I have re-run the becnh
> 1 time on x28A using aarch64 chroot
> 1 time on x31+ using armhf chroot
> 1 time on x28A using ermhf chroot
> 
> ... and I get exactly the same result ~60 sec. for aarch64, ~350 for armhf on x31+, ~800 for armhf on x28A

He has 60 sec (64 bit aarch64) vs 800 sec in emulated environment. Can you check or explain it? You can check it yourself.
The largest difference I had on the same aarch64 system was 17% aarch64 мы armv7.
One of the users reports big difference in real time usage here - https://www.snbforums.com/threads/entware-3x-for-new-hnd-platform-gt-ac5300-and-rt-ac86u-with-asuswrt-merlin-firmware.44393/#post-378303

> I am testing it now on my RT-AC86U. Some packages get improvement.
> For instance,
> ocserv (Openconnect vpn server) can reach 200Mbps. It was 70Mbps on armv7.
> Transmission also get more speed, nearly 30MB/s. It was 12MB/s on armv7.

It is unbelievably big, but still it is less then 3 times difference. sysbench gives more, up to 24 times in my case.

**Comment by akopytov** [comment]
Please take a look at the source code, it's short and simple: https://github.com/akopytov/sysbench/blob/0.5/sysbench/tests/cpu/sb_cpu.c#L139

So what the cpu benchmark essentially does is integer divisions on 64-bit number (that alone may explain the huge difference between 32- and 64-bit builds) and sqrt() (which explains even bigger difference with soft float builds). Does that make sense?

**Comment by zyxmon** [comment]
It makes some sense but shows that benchmark has no relation to real applications.
Синтетика, она и в Африке синтетика. Но настолько .....

**Comment by zyxmon** [comment]
А в случае QEMU все спишем на кривую эмуляцию. Хотя все выполняется на 64 разрядном интеле.

**Comment by akopytov** [comment]
Well, I'm sorry to hear the cpu benchmark doesn't do what you need. Personally, I have used it just a few times when I needed to create some load on CPU core(s). Basically, as a cpuburn replacement. I have never recommended using to to **compare** CPU performance across different machines, emulated-vs-native performance, let alone different architectures. I believe there are better tools to do that job.

If there's enough interest, some day I may fix the `cpu` benchmark to do something more meaningful for those purposes. it's not hard at all, as I said.

**Comment by zyxmon** [comment]
> Basically, as a cpuburn replacement.

Then it should not be called sysBENCH. It would be nice to have more meaningful tests in future, because there are really no linux tools for it.
