### ISSUE TITLE
Why the queue_time is included in 'Latency'?

### ISSUE THREAD

**Issue by hnwyllmm** [akopytov/sysbench#216]
Why the queue_time is included in 'Latency'?
I think the latency is the time between response and request.
```
  uint64_t elapsed = TIMESPEC_DIFF(t->time_end, t->time_start) + t->queue_time;
```
in `sb_timer_stop`

**Comment by akopytov** [comment]
Imagine a situation when the system is unable to keep up with the specified rate. For simplicity, let's say it got stalled completely for one second. 

What's going to happen is requests first piling up in the queue for one second, then getting processed. If your latency only includes the time between response and request, you're not going to see that in your reports. Everything will look normal. But if you add queue time to latency, you will see a huge spike in max/avg and percentile latency values.

I believe this is called "coordinated omission problem": https://groups.google.com/forum/#!msg/mechanical-sympathy/icNZJejUHfE/BfDekfBEs_sJ
