### ISSUE TITLE
Sysbench error with MySQL 8.0.11 

### ISSUE THREAD

**Issue by shiviyer** [akopytov/sysbench#226]
[root@localhost shiv]# sysbench --test=cpu --cpu-max-prime=300000 run
sysbench 1.1.0-4412a54 (using bundled LuaJIT 2.1.0-beta3)

FATAL: Cannot find benchmark 'run': no such built-in test, file or module
[root@localhost shiv]# 

mysql> select version();
+-----------+
| version() |
+-----------+
| 8.0.11    |
+-----------+
1 row in set (0.00 sec)

**Comment by akopytov** [comment]
Hi Shiv,

Yes, `--test` was deprecated in sysbench 1.0 (was only supported for compatibility with 0.5) and I recently removed it from 1.1. Please use `sysbench cpu ...`.

**Comment by shiviyer** [comment]
Thank you so much, My bad.. I still continued using deprecated feature, Thanks again 👍
