### ISSUE TITLE
invalid option: --warmup-time=10

### ISSUE THREAD

**Issue by extraSix** [akopytov/sysbench#227]
I tried to use --warmup-time in the test for oltp, but it didn't work.

> sysbench oltp_read_only.lua --mysql-host=xxx --mysql-port=3306 --mysql-user=xxx --mysql-password=xxx --mysql-db=sbtest --db-driver=mysql --threads=32 --percentile=95 --tables=5 --table_size=50000 --time=100 --warmup-time=10 --report-interval=5 run

```
 sysbench 1.0.14 (using bundled LuaJIT 2.1.0-beta2)
 invalid option: --warmup-time=10
```

What should I do?

**Comment by akopytov** [comment]
`--warmup-time` is only supported in the development (`master`) branch. You can either build sysbench from source, our use the sysbench-prereleases repository on packagecloud.
