### ISSUE TITLE
Sysbench config-file

### ISSUE THREAD

**Issue by smac89** [akopytov/sysbench#228]
I run sysbench like this:

`sysbench --config-file=config.cnf`

Where `config.cnf` contains the configuration options. However, all I see on the command line is:

```
sysbench 1.0.14 (using bundled LuaJIT 2.1.0-beta2)

Reading the script from the standard input:
```

What does that mean? What script is it supposed to be reading?

The contents of `config.cnf` are:

`--mysql-user=username --mysql-password=password --mysql-port=3306 --mysql-host=localhost --threads=10 --verbosity=5 --validate --db-driver=mysql oltp_read_write --mysql_storage_engine=innodb run`

When I do this instead:
`sysbench --config-file=config.cnf oltp_read_write --mysql_storage_engine=innodb run`

I get the output:

```
sysbench 1.0.14 (using bundled LuaJIT 2.1.0-beta2)

WARNING: Global option 'user' will not be exported, because the type is unknown
WARNING: Global option 'password' will not be exported, because the type is unknown
WARNING: Global option 'port' will not be exported, because the type is unknown
WARNING: Global option 'verbose' will not be exported, because the type is unknown
Running the test with following options:
Number of threads: 1
Initializing random number generator from current time


Initializing worker threads...

WARNING: Global option 'user' will not be exported, because the type is unknown
WARNING: Global option 'password' will not be exported, because the type is unknown
WARNING: Global option 'port' will not be exported, because the type is unknown
WARNING: Global option 'verbose' will not be exported, because the type is unknown
FATAL: Multiple DB drivers are available. Use --db-driver=name to specify which one to use
FATAL: `thread_init' function failed: /usr/share/sysbench/oltp_common.lua:348: failed to initialize the DB driver
FATAL: Thread initialization failed!
```

My conclusion: **It does not read the config file**

Am I missing something? Is the config supposed to be a lua script? I'm not sure.

Thanks.

**Comment by smac89** [comment]
I got it. The options are to be list one on each line without the dashes like so:

```cfg
mysql-user=username
mysql-password=password
mysql-port=3306
mysql-host=localhost
threads=10
verbosity=5
validate
db-driver=mysql
```

**Comment by akopytov** [comment]
This is going to be improved and simplified after #200 is implemented. The configuration file will be a Lua table. It will also be possible to change options from the benchmark script itself.
