### ISSUE TITLE
"--file-fsync-freq=0" seems to prevent fsync() at end of test

### ISSUE THREAD

**Issue by jamespharvey20** [akopytov/sysbench#229]
This is all with my Toshiba MD04ACA500 (5TB platter) drives.

Way back on v0.4.12, I could run:
```
# sysbench --test=fileio --file-num=1 --file-block-size=2M --file-test-mode=seqwr --file-fsync-freq=0 run
...
Calling fsync() at the end of the test, Enabled.
...
Operations performed:  0 Read, 1024 Write, 1 Other = 1025 Total
Read 0b  Written 2Gb  Total transferred 2Gb  (189.16Mb/sec)
...
```

That speed is as expected, over a single 2GB sequential write.

I tried the git version way back in 2016, when master was 0.5 #85889df.  The same command showed:
```
Calling fsync() at the end of the test, Enabled.
...
Operations performed:  0 reads, 10000 writes, 1 Other = 10001 Total
Read 0b  Written 19.531Gb  Total transferred 19.531Gb  (1.2467Gb/sec)
...
```

Between v0.4 and git v0.5 #85889df, I'm thinking something broke that prevents calling fsync() at the end of the test.  I meant to open an issue back then, but doesn't look like I ever did.

Adding `--file-fsync-end=on` didn't change anything.

I just tried v1.0.14, and running:

```
# sysbench fileio --file-test-mode=seqwr --file-fsync-freq=0 run
...
Calling fsync() at the end of test, Enabled.
...
Throughput:
    read, MiB/s:                  0.00
    written, MiB/s:               1616.36
...
```

Adding `--file-fsync-end=on` doesn't change anything.

So, it looks like fsync() isn't called in the current version, either.

Omitting `--file-fsync-freq=0` does allow fsync() calls, which is why I'm thinking this option prevents the fsync() at the end.

**Comment by akopytov** [comment]
Looking at the code, `--file-fsync-freq` is not honored if the benchmark stops due to a time limit, rather than an operations limit. In my tests, adding `--time=0 --events=10000` results in fsync() being called again at the end. I'll see if there's a simple fix for that, but at least there is a workaround.

**Comment by jamespharvey20** [comment]
Wasn't sure if e633f9c is supposed to honor calling `fsync()` if the benchmark stops due to a time limit, or instead if it was to allow the workaround by using `--time=0 --events=10000`.

2e6b7d5 (which is after e633f9c) still does not call `fsync()` at the end when ran like:

```
# sysbench fileio --file-test-mode=seqwr --file-fsync-freq=0 run
```

But, the workaround does appear to call `fsync()` at the end with

```
# sysbench fileio --file-test-mode=seqwr --file-fsync-freq=0 --time=0 --events=10000 run
```

**Comment by akopytov** [comment]
@jamespharvey20 hmm, what makes you think commit 2e6b7d5 does not call `fsync()` at the end? It seems to work for me:

```
$ src/sysbench fileio --file-test-mode=seqwr --file-fsync-freq=0 run
sysbench 1.0.14-2368f4d (using bundled LuaJIT 2.1.0-beta2)

Running the test with following options:
Number of threads: 1
Initializing random number generator from current time


Extra file open flags: (none)
128 files, 16MiB each
2GiB total file size
Block size 16KiB
Calling fsync() at the end of test, Enabled.
Using synchronous I/O mode
Doing sequential write (creation) test
Initializing worker threads...

Threads started!


File operations:
    reads/s:                      0.00
    writes/s:                     13215.12
    fsyncs/s:                     7.60

Throughput:
    read, MiB/s:                  0.00
    written, MiB/s:               206.49

General statistics:
    total time:                          16.8312s
    total number of events:              222482

Latency (ms):
         min:                                    0.00
         avg:                                    0.04
         max:                                  131.65
         95th percentile:                        0.04
         sum:                                 9870.09

Threads fairness:
    events (avg/stddev):           222482.0000/0.00
    execution time (avg/stddev):   9.8701/0.00
```

**Comment by jamespharvey20** [comment]
Huh.  What distro, kernel, and filesystem is your test on?  Are you using LVM?  If so, regular thick, or thin volume?

I'm on Arch Linux, kernel 4.15.14.  I'm tracking down a bug somewhere in btrfs, lvm, or maybe kernel file caching.  I think it's been there for a considerable amount of time.  It causes 2-60 second laggy lockups during heavy writes, and I wouldn't expect it to be causing what's happening here with sysbench.  And, as shown way below, telling `dd` to `fsync()` at the end gives expected results.

With my posts above, I'm not sure if I was using LVM or not, and could have been using ext4, xfs, or btrfs.  But, the output below is in a simplified regular partition, no LVM, using ext4, on a single Toshiba 5TB (platter) drive.  (For my future reference, sdb3.)  Xfs and btrfs give similar results.

With `0.4.12`:

```
# sysbench --test=fileio --file-test-mode=seqwr --file-fsync-freq=0 --file-num=1 --file-block-size=2M run
sysbench 0.4.12:  multi-threaded system evaluation benchmark
...
Read 0b  Written 2Gb  Total transferred 2Gb  (177.56Mb/sec)
...
# sysbench --test=fileio --file-test-mode=seqwr --file-fsync-freq=0 run
sysbench 0.4.12:  multi-threaded system evaluation benchmark
...
Read 0b  Written 2Gb  Total transferred 2Gb  (114.91Mb/sec)
...
```

That's as expected for a fast but non-raid platter drive.

With `1.0.14`:

```
# sysbench fileio --file-test-mode=seqwr --file-fsync-freq=0 --file-num=1 --file-block-size=2M run
sysbench 1.0.14 (using bundled LuaJIT 2.1.0-beta2)
...
File operations:
    reads/s:                      0.00
    writes/s:                     1362.67
    fsyncs/s:                     0.00

Throughput:
    read, MiB/s:                  0.00
    written, MiB/s:               2725.34
...
# sysbench fileio --file-test-mode=seqwr --file-fsync-freq=0 run
sysbench 1.0.14 (using bundled LuaJIT 2.1.0-beta2)
...
File operations:
    reads/s:                      0.00
    writes/s:                     186520.95
    fsyncs/s:                     0.00

Throughput:
    read, MiB/s:                  0.00
    written, MiB/s:               2914.39
...
```

So, it's saying there's no `fsync()` which seems accurate because 2+GiB/s is way too fast for this non-raid platter drive.

With `1.1.0-2e6b7d5`:

```
# sysbench fileio --file-test-mode=seqwr --file-fsync-freq=0 --file-num=1 --file-block-size=2M run
sysbench 1.1.0-2e6b7d5 (using bundled LuaJIT 2.1.0-beta3)
...
         write: IOPS=479.72 959.43 MiB/s (1006.04 MB/s)
         fsync: IOPS=0.04

# sysbench fileio --file-test-mode=seqwr --file-fsync-freq=0 run
sysbench 1.1.0-2e6b7d5 (using bundled LuaJIT 2.1.0-beta3)
...
         write: IOPS=71126.49 1111.35 MiB/s (1165.34 MB/s)
         fsync: IOPS=4.87
...
```

I saw the 1+GB/s, and concluded it still wasn't calling `fsync()`.  I don't know if I read its `fsync: IOPS` claims before my last message.

Something definitely changed, because the throughput reports have moved in the right direction, around 1GB/s rather than around 3GB/s.

But, it's still reporting a throughput about 5 times higher than the drive is capable of.

Comparing to `dd`, using `status=progress` which gives an every second progress update (it seems to give intermediate progress updates on every even second if it's not done yet), and `conv=fdatasync` which makes a single `fsync()` call after writing everything:

```
# dd if=/dev/zero of=zero bs=64k count=50000 conv=fdatasync status=progress
3013214208 bytes (3.0 GB, 2.8 GiB) copied, 2 s, 1.5 GB/s
50000+0 records in
50000+0 records out
3276800000 bytes (3.3 GB, 3.1 GiB) copied, 18.2095 s, 180 MB/s
```

So, this shows `dd` reports the buffered 1.5GB/s amounts prior to its `fsync()`, taking 2 seconds to write 3G.  It takes another fraction of a second to finish the 3.3GB write, and stops progress updating because that portion of its code thinks it's done, and it doesn't update during an `fsync()`.  Then, it calls `fsync()` and it takes about 16 seconds for that to complete, and it reports a realistic 180 MB/s.

So, I don't know if I was right saying 2e6b7d5 doesn't call `fsync()`.  But, it's still reporting too high of throughput.

I noticed that I was using branch master `1.1.0-2e6b7d5` and your reply was using branch 1.0's `1.0.14-2368f4d`.  I tried using the same, in case the branch master had a new bug that branch 1.0 didn't.

```
# sysbench fileio --file-test-mode=seqwr --file-fsync-freq=0 --file-num=1 --file-block-size=2M run
sysbench 1.0.14-2368f4d (using bundled LuaJIT 2.1.0-beta2)
...
File operations:
    reads/s:                      0.00
    writes/s:                     679.75
    fsyncs/s:                     0.04

Throughput:
    read, MiB/s:                  0.00
    written, MiB/s:               1359.49
...
# sysbench fileio --file-test-mode=seqwr --file-fsync-freq=0 run
sysbench 1.0.14-2368f4d (using bundled LuaJIT 2.1.0-beta2)
...
File operations:
    reads/s:                      0.00
    writes/s:                     71643.82
    fsyncs/s:                     4.84

Throughput:
    read, MiB/s:                  0.00
    written, MiB/s:               1119.43
...
```

So, branch 1.0 is reporting the same throughput as branch master, giving it some 30% latitude for statistical variance.

**Comment by akopytov** [comment]
I see what the problem is here. `--file-test-mode=seqwr` also honors the `--file-total-size` limit (2 GiB by default). So it wraps around to offset 0 when it reaches that limit, and the benchmark essentially updates the 2 GiB block in page cache, which is `fsync()`ed at the end. Which, of course, is different from the `dd` benchmarks and does not reflect the real storage capacity.

For sequential benchmark it would be more reasonable to make sure `--file-total-size` is high enough to not be reached during the benchmark, so it creates as large file as it can without wrapping around.
