### ISSUE TITLE
Question about "Threads fairness"

### ISSUE THREAD

**Issue by steffi0202** [akopytov/sysbench#231]
Hi everybody,

i did a cpu test with `sysbench --test=cpu --cpu-max-prime=100000 --num-threads=12 run` and i know, that i should only compare the "total time" but i'm also wondering what the result under `Threads fairness:` mean. 

For Example my two tests. One on a hardware machine and one on a virtual machine: 

**VM:** 

General

 statistics:
--
total time:                          34.4150s
total number of events:              10000
total time taken by event execution: 412.6643s
response time:
min:                                 37.56ms
avg:                                 41.27ms
max:                                136.04ms
approx.  95 percentile:              46.81ms
 
Threads fairness:
events (avg/stddev):           833.3333/23.57
execution time (avg/stddev):   34.3887/0.01

**Hardware:** 

Test execution summary:
--
total time:                          18.3264s
total number of events:              10000
total time taken by event execution: 219.7879
per-request statistics:
min:                                 21.65ms
avg:                                 21.98ms
max:                                 34.45ms
approx.  95 percentile:              22.04ms
 
Threads fairness:
events (avg/stddev):           833.3333/1.31
execution time (avg/stddev):   18.3157/0.01

The result `events (avg/stddev):` is 20 times higher. What does that mean?

**Comment by akopytov** [comment]
"Threads fairness" was an unfortunate wording for "Event distribution by threads". I.e. it shows average numbers of executed events by thread, their total execution time by thread, and standard deviation for the same values. You can also run with the `--debug` option to see the actual values per thread in addition to their aggregate values.

I'll try to fix the wording in the next release.
