### ISSUE TITLE
sysbench does not excercise the "--memory-total-size=SIZE" option for memory test

### ISSUE THREAD

**Issue by hsane2001** [akopytov/sysbench#233]
sysbench memory test includes the option:
--memory-total-size=SIZE    total size of data to transfer [100G]
However, if you either monitor vmstat (system memory usage) or traverse through source code, you will find that this option is not being exercised. This results in all selected threads working on the same small global buffer defined by "--memory-block-size=SIZE", which can result in a lot of contention. The source needs to nest the "for" loop buffer traversal within the "for loop to traverse the defined "memory-total-size".

**Comment by akopytov** [comment]
`--memory-total-size` defines the total amount of bytes to process, rather than the total amount of memory to allocate. In other words, it is a limit on the number of memory operations, and that limits is check in `memory_next_event()`.
