### ISSUE TITLE
WARNING: the --test option is deprecated. You can pass a script name or path on the command line without any options. Unrecognized command line argument: prepare

### ISSUE THREAD

**Issue by cintyaelsa** [akopytov/sysbench#235]
i got the error, after i run my script. how to fix it

this is the script

sysbench --test=tests/db/insert.lua --mysql-host= <host> --mysql-port=3306 --mysql-user=<****> --mysqlpassword=<*****>--mysql-db=<dbname> --mysql-table-engine=innodb --oltp-table-size=25000 --oltp-tables-count=250 --db-driver=mysql prepare
WARNING: the --test option is deprecated. You can pass a script name or path on the command line without any options.
Unrecognized command line argument: prepare

please help me, to fix it.

thank you,

**Comment by akopytov** [comment]
What it says, just use `tests/db/insert.lua` instead of `--test=tests/db/insert.lua`.

**Comment by cintyaelsa** [comment]
sorry i forgot,
i run this script 
./sysbench --test=/db/oltp.lua --mysql-host=(****) --mysql-port=3306 --mysql-user=**** --mysqlpassword=**** --mysql-db=**** --mysql-table-engine=innodb --oltp-table-size=25000 --oltp-tables-count=250 --db-driver=mysql prepare

if i run that script, i got the error like this
See 'sysbench --test=<name> help' for a list of options for each test.

and if i run this script,
sysbench --test=/db/oltp.lua --mysql-host=(****) --mysql-port=3306 --mysql-user=**** --mysqlpassword=**** --mysql-db=**** --mysql-table-engine=innodb --oltp-table-size=25000 --oltp-tables-count=250 --db-driver=mysql prepare

i got the error like this,

WARNING: the --test option is deprecated. You can pass a script name or path on the command line without any options.
Unrecognized command line argument: prepare

**Comment by akopytov** [comment]
Sorry, I don't see any difference between runs. Can you explain it?
