### ISSUE TITLE
sysbench.sql.type

### ISSUE THREAD

**Issue by yvesware** [akopytov/sysbench#236]
I am using sysbench 1.1 

I have created a table like this:
CREATE TABLE sbtest%d(
  ....
   imm_txn INT,
   options TINYINT,
   iv BINARY,
   data LONGBLOB,
   ...
   ) 

my question is what the sysbench.sql.type, I don't see BINARY LONGBLOB. what type should I used?  Also for the create_table what string_format would match the BINARY and LONGBLOB?

**Comment by akopytov** [comment]
It is true that sysbench SQL API for prepared statements does not yet support binary data types such as BINARY and *BLOB. However, it is possible to work with those types via normal (non-prepared) SQL statements. There is an example in issue #150. 

The SQL statements to use are the same as if you had to work with those data types from the MySQL command line client. For example:

```sql
INSERT INTO sbtest1 VALUES (..., 1, 2, 'binary string', 'another binary string');
```
or, if some non-ASCII characters should be involved:

```sql
INSERT INTO sbtest1 VALUES (..., 1, 2, UNHEX('62696E61727920737472696E67'), UNHEX('616E6F746865722062696E61727920737472696E67');
```

In both cases, the `%s` directive to `string.format()` can be used to build queries.

Would that work for you?

**Comment by yvesware** [comment]
Thanks Alexey, I this can work.
