### ISSUE TITLE
BINARY LONGBLOB type

### ISSUE THREAD

**Issue by yvesware** [akopytov/sysbench#237]
I am using sysbench 1.1 

I have created a table like this:
CREATE TABLE sbtest%d(
  ....
   imm_txn INT,
   options TINYINT,
   iv BINARY,
   data LONGBLOB,
   ...
   ) 

my question is what the sysbench.sql.type, I don't see BINARY LONGBLOB. what type should I used?  Also for the create_table what string_format would match the BINARY and LONGBLOB?

**Comment by akopytov** [comment]
Duplicate of #236?

**Comment by yvesware** [comment]
Yes sorry,
