### ISSUE TITLE
init value for each thread.

### ISSUE THREAD

**Issue by yvesware** [akopytov/sysbench#238]
I'm using sysbench 1.1
I need to set range for each thread when time to insert to present "dup".  We don;t have thread_init? . I want do something like id=370000+(thread_id*1000) .. I also would be able to find the max value to start using query().

SO QUESTION, where do I setup per thread initial variables ?

**Comment by akopytov** [comment]
There is the `thread_init()` which is normally used exactly for that purpose: setup thread-local variables. You can find an example in https://github.com/akopytov/sysbench/blob/master/src/lua/oltp_common.lua#L349

You can also get current thread's id from `sysbench.tid`.
