### ISSUE TITLE
oltp_insert.lua

### ISSUE THREAD

**Issue by yvesware** [akopytov/sysbench#239]
Ok,
I did RTFM and source , i have modified to have oltp-insert to insert 10k rows and after it should stop. NOT.! it try again but will get a dup keys. I know that the original would run to --time default (10) sec. so I'm blind don';t know much about lua and sysbench but I'm on exponential curve ;-).

What control the run time behavior of oltp_insert.lua (version 1.1) ?
Merci

**Comment by akopytov** [comment]
Hi Yves,

You don't have to modify anything, you can simply use `--time=10 --events=10000`. Can you confirm it works for you?

**Comment by akopytov** [comment]
Closing for now, feel free to reopen if have further questions on this.
