### ISSUE TITLE
how to run sysbench with mysql-ssl option ?

### ISSUE THREAD

**Issue by junli0411** [akopytov/sysbench#240]
Hello,
Can anybody help me to run sysbench with mysql-ssl option ? When I run it with this option to MySQL5.7, I got the following error :
FATAL: error 2026: SSL connection error: SSL_CTX_set_default_verify_paths failed

**Comment by junli0411** [comment]
there's no cacert.pem file in the MySQL data dir .

**Comment by junli0411** [comment]
just renamed ca.pem to caret.pem ,and it works.

**Comment by akopytov** [comment]
Yes, in sysbench 1.0 client key, client cerfification and CA certificate file names are hard-coded to `client-key.pem`, `client-cert.pem` and `cacert.pem` respectively. In sysbench 1.1 there are options to control that (`--mysql-ssl-key`, `--mysql-ssl-cert` and `--mysql-ssl-ca`).

**Comment by Nor7th** [comment]
I ran into same issue for sysbench 1.0.20
But rename ca.pem to cacert.pem doesn't help.

My case is that the mysql data dir is put under a dedicated path, like /home/mysql_install/data
The files client-key.pem, client-cert.pem, and ca.pem are all there. Simply rename ca.pem doesn't help.
Access rights for all files are OK.

Does this issue have something to do with the ssl cert file searching path of sysbench or mysql server?
Thanks for any guidance.

**Comment by Nor7th** [comment]
> I ran into same issue for sysbench 1.0.20 But renaming ca.pem to cacert.pem doesn't help.
> 
> My case is that the mysql data dir is put under a dedicated path, like /home/mysql_install/data The files client-key.pem, client-cert.pem, and ca.pem are all there. Simply rename ca.pem doesn't help. Access rights for all files are OK.
> 
> Does this issue have something to do with the ssl cert file searching path of sysbench or mysql server? Thanks for any guidance.

Finally change to 1.1.0 to bypass.
