### ISSUE TITLE
thread init after event completes.

### ISSUE THREAD

**Issue by yvesware** [akopytov/sysbench#241]
My understanding is the following:
When the thread get created , thread_init is call ONCE, and thereafter for every --events the same value are used?.
Is it possible to have those value re-init for the next event? I am asking because, each thread insert into a table with some preset range for a number of rows. The next event comes along and since values are the same well, duplicate keys happens.

What's the best solution? I'm reading the code to see if there is a thread_run and maybe in that call I could  do something....

Cheers

**Comment by akopytov** [comment]
Yves,

sysbench creates separate Lua interpreter for each thread. Which means global variables actual have thread scope. So any global variable created in `thread_init()` will persist for the entire benchmark run for the thread that has created it.

But nothing prevents you from creating or modifying variables in `event()`. For example, you can create a variable in `thread_init()` by assigning a value to it, but modify its value in the `event()` function. Is that what you want to do?

**Comment by yvesware** [comment]
Alexey,

Thanks for the response, I think that would work, so the event if I'm correct are all the queries that will be executed in event(). Once completed, I can like suggested re-adjust the value before the thread_run.

thanks.
