### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by emily0418** [akopytov/sysbench#245]
在Docker环境中运行：
[root@zst1 ~]# sysbench /usr/local/share/sysbench/oltp_read_write.lua --mysql-host=172.17.0.2 --mysql-port=3306 --mysql-user=wubx --mysql-password=wubxwubx --mysql-db=wubx --tables=10 --table_size=100000 --mysql_storage_engine=Innodb  prepare
Illegal instruction (core dumped)

sysbench版本：
[root@zst1 ~]# sysbench --version
sysbench 1.1.0-50966c8
[core.zip](https://github.com/akopytov/sysbench/files/2143708/core.zip)

宿主机CPU类型：
[root@Docker30-Redhat opt]# cat /proc/cpuinfo | grep name | cut -f2 -d: | uniq -c
      4  Intel(R) Xeon(R) CPU E5-2620 0 @ 2.00GHz

操作系统版本：
[root@Docker30-Redhat ~]# cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.3 (Maipo)
[root@Docker30-Redhat ~]# uname -a
Linux Docker30-Redhat.localdomain 3.10.0-514.el7.x86_64 #1 SMP Wed Oct 19 11:24:13 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux

docker版本：
[root@Docker30-Redhat ~]# docker --version
Docker version 18.03.1-ce, build 9ee9f40

core日志文件见附件

**Comment by akopytov** [comment]
Can you try a binary built by me from https://packagecloud.io/akopytov/sysbench-prereleases/packages/el/7/sysbench-1.0.14.210-1.el7.centos.x86_64.rpm instead of the self-compiled one?

**Comment by emily0418** [comment]
Thank you for your reply. 
https://packagecloud.io/akopytov/sysbench-prereleases/packages/el/7/sysbench-1.0.14.210-1.el7.centos.x86_64.rpm  is ok , and the problem has been solved！



zhuff@thinkive.com
 
From: Alexey Kopytov
Date: 2018-06-28 12:36
To: akopytov/sysbench
CC: emily0418; Author
Subject: Re: [akopytov/sysbench] Illegal instruction (core dumped) (#245)
Can you try a binary built by me from https://packagecloud.io/akopytov/sysbench-prereleases/packages/el/7/sysbench-1.0.14.210-1.el7.centos.x86_64.rpm instead of the self-compiled one?

**Comment by akopytov** [comment]
Thanks for confirming. I think the reason is that you have built the binary optimized for a specific architecture (sysbench does that by default unless `--without-gcc-arch` is passed to `./configure`), and somehow that architecture doesn't match whatever is provided inside the Docker container.
