### ISSUE TITLE
random read/write memory test results between 0.5 and 1.1.0

### ISSUE THREAD

**Issue by ravyn440** [akopytov/sysbench#248]
I saw that someone else had a similar question comparing memory benchmark results between 0.4 and 1.0, and I looked at the commit in question which was included in the answer to that question.  That commit appears to be in sysbench 0.5.

I have a series of test runs with sysbench 1.1 and sysbench 0.5 and for the most part, the results are inline with what I would expect - with the major exception of random memory access testing.  On the exact same machine (AWS c3.8xlarge instance - 32 cores, 61G RAM), using gcc 7.3 to compile both old sysbench and new sysbench, the numbers are so far off that it seems like there is a bug.

Old sysbench 0.5:
```
sysbench --num-threads=4 --max-time=60 --max-requests=0 --test=memory --rand-type=uniform --memory-block-size=16K --memory-total-size=1T --memory-access-mode=rnd --report-interval=1 --rand-seed=123423423 run
sysbench 0.5:  multi-threaded system evaluation benchmark

Running the test with following options:
Number of threads: 4
Report intermediate results every 1 second(s)
Initializing random number generator from seed (123423423).
...
1048576.00 MB transferred (17960.53 MB/sec)
```

Running the exact same test parameters under sysbench 1.1.0:
```sysbench110--threads=4 --time=60 --events=0 --rand-type=uniform --memory-block-size=16K --memory-total-size=1T --rand-seed=123423423 --memory-access-mode=rnd --report-interval=1 memory run
sysbench 1.1.0-4b3cd3e (using bundled LuaJIT 2.1.0-beta3)

Running the test with following options:
Number of threads: 4
Report intermediate results every 1 second(s)
Initializing random number generator from seed (123423423).
...
31354.61 MiB transferred (522.57 MiB/sec)
```

522MiB/sec vs. 17960MB/sec?  Same test, same parameters, same hardware, same compiler... 

I ran it all again and collected perf data, and sysbench 1.1 spends most of its time here:
```
       │    sb_rand_uniform_double():
 90.10 │      vsubsd %xmm3,%xmm4,%xmm0
```

Whereas sysbench 0.5 perf data shows the majority of time being spent here:
```
       │               idx = (int)((double)rand / (double)SB_MAX_RND *
       │                           (double)(memory_block_size / sizeof(int)));
       │               buf[idx] = tmp;
  5.52 │       mov    0x4(%rsp),%ecx
  4.57 │       mov    0x4(%rsp),%ecx
 20.16 │       mov    0x4(%rsp),%ecx
  2.77 │       mov    0x4(%rsp),%ecx
 16.11 │       mov    0x4(%rsp),%ecx
  5.55 │       mov    0x4(%rsp),%ecx
 19.31 │       mov    0x4(%rsp),%ecx
  4.48 │       mov    0x4(%rsp),%ebp
       │       {
       │         rand = sb_rnd();
       │         LOG_EVENT_START(msg, thread_id);
       │         switch (mem_req->type) {
       │           case SB_MEM_OP_WRITE:
       │             for (i = 0; i < memory_block_size; i++)
 20.23 │       cmp    %r10,%rdi
```

As best I can tell, sysbench 1.1 is burning a lot more cycles on random number generation than on actual memory access, but I cannot tell if this is expected behavior or a bug, but the massive difference in throughput makes me think that this is not intended.

**Comment by akopytov** [comment]
Generally, I do not promise any results compatibility even between minor sysbench releases. Whenever you make any change to a code which is on a hot path, that change is going to affect benchmark numbers, i.e. the benchmark is not the same.

With that said, I try to avoid changing the workload code (something that is executed in a loop for each benchmark) in minor releases (1.0.x) to minimize impact, but make such changes in major releases.

The memory benchmark code is quite different between 0.5 and 1.0 / 1.1:

sysbench 0.5:
```c
    rand = sb_rnd();
...
        for (i = 0; i < memory_block_size; i++)
        {
          idx = (int)((double)rand / (double)SB_MAX_RND *
                      (double)(memory_block_size / sizeof(int)));
          buf[idx] = tmp;
        }   
```

sysbench 1.0 / 1.1

```c
  for (ssize_t i = 0; i < memory_block_size; i += SIZEOF_SIZE_T)
  {
    size_t offset = (size_t) (sb_rand_uniform_double() *
                              (memory_block_size / SIZEOF_SIZE_T));
    SIZE_T_STORE(tls_buf + offset, i);
  }
```

That is, in each event with your command line arguments sysbench 0.5 will be doing something like this: "pick a random 4-byte word in a 16K block, then store something into the same word 16384 / 4 times".

sysbench 1.0 / 1.1, on the other hand, would do the same number of loop iterations, but pick a new random word for each iteration. Which yes, in reality that means we are going to spend more time generating random numbers than actually doing memory writes.

Which approach is the correct one? I don't know, they simply simulate two different workloads. If I had to measure raw memory latency, I would probably go for sequential benchmark (`--memory-access-mode=seq`).
