### ISSUE TITLE
Unknown option: --oltp-num-tables.

### ISSUE THREAD

**Issue by digdeep126** [akopytov/sysbench#251]
version: sysbench 0.4
OS: windows 7

C:\sysbench2008>sysbench.exe --test=oltp --oltp-test-mode=complex --num-threads=64 --max-requests=200000  --db-driver=mysql --mysql-user=root --mysql-host=1
--mysql-password=xxx  --mysql-db=sbtest --oltp-table-size=50000 --oltp-num-tables=16 prepare
Unknown option: --oltp-num-tables.
Usage:
  sysbench [general-options]... --test=<test-name> [test-options]... command

General options:
  --num-threads=N             number of threads to use [1]
  --max-requests=N            limit for total number of requests [10000]
  --max-time=N                limit for total execution time in seconds [0]
... ...

**Comment by akopytov** [comment]
sysbench 0.4 does not support that option.
