### ISSUE TITLE
about sysbench prepare

### ISSUE THREAD

**Issue by trgfree** [akopytov/sysbench#255]
when i prepare tables with 10000000 records per table. i got the error :
FATAL: myssql_drv_query() returned error 1105 (Information schema is out of date.) for query 'INSERT INTO sbtest21(id, k, c, pad) values (...................

and then the threads becomes zombie threads.
what can i do?

**Comment by akopytov** [comment]
What server is that? I've never seen that error and cannot find it in the MySQL sources?

**Comment by trgfree** [comment]
sysbench\src\drivers\mysql\drv_mysql.c

**Comment by trgfree** [comment]
funcation check_error 
    log_text(LOG_FATAL, "%s returned error %u (%s) for query '%s'",
             func, error, sb_con->sql_errmsg, query);

**Comment by trgfree** [comment]
i find the code,i guess. but i cann't got it

**Comment by akopytov** [comment]
The error message returned by the MySQL server is "Information schema is out of date". This must be some customized MySQL, so you should talk to its authors. It is impossible to tell anything without understanding what that *server* error means.

**Comment by trgfree** [comment]
can this problem be resolve?

**Comment by trgfree** [comment]
the server is mysql，next week i give you the detail information

**Comment by trgfree** [comment]
i cannot find the error in mysql source code,nor internet
