### ISSUE TITLE
Sysbench Does not Terminate at Given --time for High Thread Count (MySQL OLTP Test)

### ISSUE THREAD

**Issue by kcamp34** [akopytov/sysbench#271]
Running command: `sudo sysbench --db-driver=mysql --db-ps-mode=disable --mysql-user=root --mysql-password=password --mysql-db=sbtest --oltp-tables-count=999 --oltp-table-size=99999 --mysql-host=10.0.0.3 --percentile=95 --time=1200 --max-requests=0 --num-threads=512 --report-interval=1  /usr/share/sysbench/tests/include/oltp_legacy/oltp.lua run`

Results in a run that is sensible until the specified --time is reached. Over the next second or two there is more tps, qps, etc data reported then the thread count drops and returns 0s for every metric every second and this behavior does not terminate. Here is a few lines of the output around the 1200s mark:

```
...
[ 1198s ] thds: 512 tps: 100.00 qps: 3000.09 (r/w/o: 2423.06/836.02/366.01) lat (ms,95%): 4437.27 err/s: 0.00 reconn/s: 0.00
[ 1199s ] thds: 512 tps: 200.00 qps: 5000.02 (r/w/o: 3937.01/947.00/522.00) lat (ms,95%): 4768.67 err/s: 0.00 reconn/s: 0.00
[ 1200s ] thds: 512 tps: 200.98 qps: 5000.66 (r/w/o: 4146.76/1171.93/589.97) lat (ms,95%): 5033.35 err/s: 0.00 reconn/s: 0.00
[ 1201s ] thds: 512 tps: 100.01 qps: 800.05 (r/w/o: 4.00/724.04/156.01) lat (ms,95%): 4128.91 err/s: 0.00 reconn/s: 0.00
[ 1202s ] thds: 409 tps: 300.00 qps: 600.00 (r/w/o: 0.00/365.00/320.00) lat (ms,95%): 3040.14 err/s: 0.00 reconn/s: 0.00
[ 1203s ] thds: 409 tps: 0.00 qps: 0.00 (r/w/o: 0.00/0.00/0.00) lat (ms,95%): 0.00 err/s: 0.00 reconn/s: 0.00
[ 1204s ] thds: 409 tps: 0.00 qps: 0.00 (r/w/o: 0.00/0.00/0.00) lat (ms,95%): 0.00 err/s: 0.00 reconn/s: 0.00
[ 1205s ] thds: 409 tps: 0.00 qps: 0.00 (r/w/o: 0.00/0.00/0.00) lat (ms,95%): 0.00 err/s: 0.00 reconn/s: 0.00
[ 1206s ] thds: 409 tps: 0.00 qps: 0.00 (r/w/o: 0.00/0.00/0.00) lat (ms,95%): 0.00 err/s: 0.00 reconn/s: 0.00
[ 1207s ] thds: 409 tps: 0.00 qps: 0.00 (r/w/o: 0.00/0.00/0.00) lat (ms,95%): 0.00 err/s: 0.00 reconn/s: 0.00
[ 1208s ] thds: 409 tps: 0.00 qps: 0.00 (r/w/o: 0.00/0.00/0.00) lat (ms,95%): 0.00 err/s: 0.00 reconn/s: 0.00
[ 1209s ] thds: 409 tps: 0.00 qps: 0.00 (r/w/o: 0.00/0.00/0.00) lat (ms,95%): 0.00 err/s: 0.00 reconn/s: 0.00
[ 1210s ] thds: 409 tps: 0.00 qps: 0.00 (r/w/o: 0.00/0.00/0.00) lat (ms,95%): 0.00 err/s: 0.00 reconn/s: 0.00
...
```

Having checked the server and the connections to the db, it appears there is nothing connected to the db after the 1200s mark. I have only seen this issue for high thread counts (512+). Any idea what is happening here?

**Comment by hicqu** [comment]
Similar issue. Any progress?

**Comment by hicqu** [comment]
Remove `--report-interval` resolves my problem. You can take a try.

**Comment by kcamp34** [comment]
Unfortunately that is not a good solution for me as I need both the intermediate reports and cumulative report.

**Comment by jsshafer** [comment]
I have the same issue with thread count as low as 16.

**Comment by akopytov** [comment]
Apologies for the delayed response. I'm pretty sure the reason is that most threads are stuck trying to create connections to the server.

- check `dmesg` on the server. It should contain messages about SYN flooding and cookies.
- get a backtrace of stuck threads. They must be waiting on `mysql_real_connect()`.
- try using modern OLTP scripts instead of the legacy ones. Modern OLTP scripts create connections in `thread_init()`, i.e. before starting the actual benchmark. If a `thread_init()` call fails to return in 30 seconds, the benchmark fails.
- if the above checks are positive, configure the server to avoid SYN flooding protection as described [here](https://github.com/akopytov/sysbench/issues/89#issuecomment-264781448)

**Comment by kcamp34** [comment]
I can confirm `dmesg` showed SYN flooding.
Modern OLTP scripts ran fine - they did not appear to fail to create connections.

I went ahead with configuring the server to avoid SYN flooding protection which seems to have solved the issue.

**Comment by akopytov** [comment]
Thanks for confirming!
