### ISSUE TITLE
master vs 1.0 branches

### ISSUE THREAD

**Issue by jamespharvey20** [akopytov/sysbench#273]
Hoping a developer would be willing to make a few comments about the `master` vs `1.0` branch.  With them being quite diverged, if someone wants to run the "latest and greatest" (and potentially incomplete and/or with bugs) rather than a release version, what should be considered when choosing between the branches?  Notably, the 1.0 branch has tests with `legacy` in their filename, and the master branch does not.  I'm assuming `master` has a big new feature set being developed that isn't `1.0`-compatible, or something along those lines.  I maintain the "sysbench-git" package in the Arch User Repository, and am asking ultimately to see which the package should use, or if there's any reason to have one for both.  (Currently using master.)  The master branch currently identifies itself as v `1.1.0`in `configure.ac`, and I'll admit until now I didn't realize the branches were so diverged.

**Comment by akopytov** [comment]
The master branch is what will eventually be released as sysbench 1.1 or 2.0 (depending on the nature of changes by the time I decide it is ready for a release). The 1.0 branch is the current stable release series containing only bug fixes.
