### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by ss-torres** [akopytov/sysbench#277]
I couldn't install the sysbench in a computer whose OS is CentOS Linux release 7.2.1511 (Core). 
First, I could run the command, which is `curl -s https://packagecloud.io/install/repositories/akopytov/sysbench/script.rpm.sh | sudo bash`, successfully. 
Then, I input `sudo yum -y install sysbench`, but ran it failed. The error message is 
" Transaction check error:
  file /usr/share/mysql/charsets/README from install of mariadb-libs-1:5.5.60-1.el7_5.x86_64 conflicts with file from package MySQL-server-5.6.17-1.el6.x86_64
  file /usr/share/mysql/charsets/Index.xml from install of mariadb-libs-1:5.5.60-1.el7_5.x86_64 conflicts with file from package MySQL-server-5.6.17-1.el6.x86_64
...".
I want to know how to solve this problem. Please give me some suggestions. Thanks.

**Comment by akopytov** [comment]
I don't have a suggestion at hand, but it is clearly not a sysbench packaging issue.
