### ISSUE TITLE
No support for this architecture

### ISSUE THREAD

**Issue by z278718149** [akopytov/sysbench#284]
make[3]: Entering directory '/home/zhaoan/sysbench/sysbench-1.0.12/third_party/luajit/luajit/src'
lj_arch.h:59:2: error: #error "No support for this architecture (yet)"
 #error "No support for this architecture (yet)"
  ^~~~~
lj_arch.h:357:2: error: #error "No target architecture defined"
 #error "No target architecture defined"
  ^~~~~
lj_arch.h:59:2: error: #error "No support for this architecture (yet)"
 #error "No support for this architecture (yet)"
  ^~~~~
lj_arch.h:357:2: error: #error "No target architecture defined"
 #error "No target architecture defined"
  ^~~~~
lj_arch.h:59:2: error: #error "No support for this architecture (yet)"
 #error "No support for this architecture (yet)"
  ^~~~~
lj_arch.h:357:2: error: #error "No target architecture defined"
 #error "No target architecture defined"
  ^~~~~
lj_arch.h:59:2: error: #error "No support for this architecture (yet)"
 #error "No support for this architecture (yet)"

Linux stage4.fedoraproject.org 4.15.0-00046-g48fb45691946 #27 SMP Mon May 14 08:25:14 UTC 2018 riscv64 riscv64 riscv64 GNU/Linux

**Comment by akopytov** [comment]
This is technically a valid bug report, but it should go to the LuaJIT project. sysbench simply contains a bundled snapshot of LuaJIT for convenience, but also supports building with external LuaJIT (`--with-system-luajit`).
