### ISSUE TITLE
Allow hashed primary key

### ISSUE THREAD

**Issue by robert-s-lee** [akopytov/sysbench#285]
Sequentially ordered primary key can create hotspot when used with some shard based distributed systems.  YCSB has [insertorder property](https://github.com/brianfrankcooper/YCSB/wiki/Core-Properties) that control the primary key to be ordered or hashed.  When hashed is used, primary key of 1 is translated to hashed equivalent.  The hash value allows better distribution of data.   

A one option would be translate YCSB's ordered number to hash algorithm copy and pasted below:

https://github.com/brianfrankcooper/YCSB/blob/d2d9a3fdea62217e714843fef9b5da531aebd1bd/core/src/main/java/com/yahoo/ycsb/Utils.java
```
/**
   * Hash an integer value.
   */
  public static long hash(long val) {
    return fnvhash64(val);
  }

  public static final long FNV_OFFSET_BASIS_64 = 0xCBF29CE484222325L;
  public static final long FNV_PRIME_64 = 1099511628211L;

  /**
   * 64 bit FNV hash. Produces more "random" hashes than (say) String.hashCode().
   *
   * @param val The value to hash.
   * @return The hash value
   */
  public static long fnvhash64(long val) {
    //from http://en.wikipedia.org/wiki/Fowler_Noll_Vo_hash
    long hashval = FNV_OFFSET_BASIS_64;

    for (int i = 0; i < 8; i++) {
      long octet = val & 0x00ff;
      val = val >> 8;

      hashval = hashval ^ octet;
      hashval = hashval * FNV_PRIME_64;
      //hashval = hashval ^ octet;
    }
    return Math.abs(hashval);
  }
```

**Comment by akopytov** [comment]
It is not clear support in which sysbench part is being requested.

- most OLTP scripts indeed use sequentially ordered IDs, but they are only used to populate the table(s) in the `prepare` stage. So any potential hotspots should not matter much for the actual performance evaluation where IDs are generated randomly, but INSERTs are always preceded by a DELETE with the same ID to keep the benchmark idempotent.

- Lua API. sysbench currently does not provide any hash functions, but there is the `sysbench.rand.unique()` function generating a unique sequence of 32-bit integers that are not monotonically increasing. On top of that, LuaJIT is efficient enough to implement any hashing function without resorting to C and exposing it through API for performance reasons.

What particular use case are we talking about?

**Comment by robert-s-lee** [comment]
Sorry for jumping the gun as I was more familiar with YCSB.   A bit of background: Testing  [CockroachDB](https://www.cockroachlabs.com) which uses PostgreSQL wire protocol.  Working on a simulation where the ratio of read:update:insert:delete can be controlled, for example ratio of 8:4:2:1

The sequence of the run is as follows:
- populate data with `oltp_read_write prepare`
- run mixture of `oltp_read_write run`, `select_random_points run` and `oltp_insert run` to get the right ratio

### auto_inc=on
When running `auto_inc=on` (sequence below), `oltp_read_write prep` expects the values of primary key `id` to stay between 1 and `--table-size` to generate proper result set.  With [CockroachDB's serial type](https://www.cockroachlabs.com/docs/v2.1/serial.html#main-content), the `id` values are something like `415008032707739649`. As a result, `oltp_read_write --auto_inc= on run` returns all empty results set which is not a valid test.
 
```
cockroach sql --insecure  -e "drop table if exists sbtest1"
_sysb oltp_read_write --auto_inc= on prepare 
_sysb oltp_read_write --auto_inc= on run
_sysb oltp_insert --auto_inc= on run
```

### auto_inc=off
When running `auto_inc=off` (sequence below), `oltp_read_write prep` runs properly.  
```
cockroach sql --insecure  -e "drop table if exists sbtest1"
_sysb oltp_read_write --auto_inc=off prepare 
_sysb oltp_read_write --auto_inc=off run
_sysb oltp_insert --auto_inc=off run
[ 1s ] thds: 1 tps: 698.23 qps: 698.23 (r/w/o: 0.00/698.23/0.00) lat (ms,95%): 2.30 err/s: 0.00 reconn/s: 0.00
```

However,  `oltp_insert` is not re-entrant as the 2nd and subsequent runs produce dup `id` with `sysbench.rand.unique() - 2147483648`.  The `error` rates are high.  Tried `--rand-seed=123 --rand-type=uniform` to get different set of `id` but that did not yield positive result.  

**Not sure if there is a better way to control the `id` generation to prevent the dups.**

```
_sysb oltp_insert --auto_inc=off run
[ 1s ] thds: 1 tps: 0.00 qps: 0.00 (r/w/o: 0.00/0.00/0.00) lat (ms,95%): 0.00 err/s: 853.28 reconn/s: 0.00

_sysb --rand-seed=123 --rand-type=uniform oltp_insert --auto_inc=off run
[ 1s ] thds: 1 tps: 0.00 qps: 0.00 (r/w/o: 0.00/0.00/0.00) lat (ms,95%): 0.00 err/s: 910.10 reconn/s: 0.00
```

### mix of auto_inc=off and auto_inc=off 

A quick [hack](https://github.com/robert-s-lee/sysbench/tree/choose-autoinc) was tested so that choice of `auto_inc` can be made by the module.  `oltp_read_write` `prepare` and `run` control the `id` , but CockroachDB to controls the `id` in `oltp_insert `.  This allows multiple threads to run without creating dups.

```
cockroach sql --insecure  -e "drop table if exists sbtest1"
_sysb oltp_read_write --auto_inc_ddl=on --auto_inc=off prepare 
_sysb oltp_read_write --auto_inc=off run
_sysb oltp_insert --auto_inc=on run
[ 1s ] thds: 1 tps: 1301.04 qps: 1301.04 (r/w/o: 0.00/1301.04/0.00) lat (ms,95%): 0.99 err/s: 0.00 reconn/s: 0.00
_sysb oltp_insert --auto_inc=on run
[ 1s ] thds: 1 tps: 1100.00 qps: 1100.00 (r/w/o: 0.00/1100.00/0.00) lat (ms,95%): 1.23 err/s: 0.00 reconn/s: 0.00
_sysb_threads=2 _sysb oltp_insert --auto_inc=on run
[ 1s ] thds: 2 tps: 2143.46 qps: 2143.46 (r/w/o: 0.00/2143.46/0.00) lat (ms,95%): 1.55 err/s: 0.00 reconn/s: 0.00


> show create table sbtest1;
  table_name |                create_statement
+------------+------------------------------------------------+
  sbtest1    | CREATE TABLE sbtest1 (
             |     id INT8 NOT NULL DEFAULT unique_rowid(),
             |     k INT8 NOT NULL DEFAULT 0:::INT8,
             |     c CHAR(120) NOT NULL DEFAULT '':::STRING,
             |     pad CHAR(60) NOT NULL DEFAULT '':::STRING,
             |     CONSTRAINT "primary" PRIMARY KEY (id ASC),
             |     INDEX k_1 (k ASC),
             |     FAMILY "primary" (id, k, c, pad)
             | )

> select id from sbtest1 limit 10;
          id
+--------------------+
  415082781176299521
  415082984882208769
  415082982180519937
```

One drawback to this approach is that `serial` produces sequential (not monotonically increasing as there could be gaps) order which tend to create bottleneck when pushed to extremely high concurrency (1000 of threads).  If the `id` is hashed, distribution is better -- which was the reason for the original question.  `--auto_inc=off` does produce good distribution, if it can be run multiple times.

Is there a way to setup `_sysb oltp_insert --auto_inc=off run` so dups are not generated on subsequent runs (or lessen the chance)?  

`_sysb` function below.
```
_sysb() {
sysbench --db-driver=pgsql --threads=${_sysb_threads:-1} --events=0 --pgsql-host=${_sysb_host:-localhost} --pgsql-port=${_sysb_port:-26257} --pgsql-user=${_sysb_user:-root} --pgsql-db=${_sysb_db:-defaultdb} --delete_inserts=${_sysb_inserts:-0} --index_updates=${_sysb_updates:-0} --non_index_updates=${_sysb_non_index_updates:-0} --table-size=${_sysb_table_size:-1222} --db-ps-mode=disable --report-interval=${_sysb_report_interval:-1} --histogram=on --time=${_sysb_time:-60} --debug=${_sysb_debug:-off} --verbosity=${_sysb_verbosity:-3} $*
}
```

**Comment by robert-s-lee** [comment]
@akopytov started draft document of sysbench and CockroachDB at https://github.com/cockroachdb/docs/issues/4221.  What is your thought on `mix of auto_inc=on and auto_inc=off` to make the test re-entrant or an alternate approach.  Would like to add `oltp_insert` to add more data while the testing is going on.

**Comment by akopytov** [comment]
@robert-s-lee it sounds like you are trying to create a custom workload by using the OLTP scripts as building blocks. It would likely be more efficient if you looked at them as examples and then implemented your own script. The CockroachDB docs you referenced recommend using "the UUID data type with the `gen_random_uuid()` function as the default value" instead of `SERIAL` so why not just do so in your custom script?

Also, instead of running multiple sysbench instances you could have a single instance with your custom script accepting the desired read:update:insert:delete ratio as a parameter and the `event()` function picking the query/transaction type to execute based on that parameter and either thread ID (`sysbench.tid`) or a random value?

**Comment by akopytov** [comment]
Closing for now. Feel free to reopen if there's anything that should be changed on the sysbench side.

**Comment by robert-s-lee** [comment]
@akopytov Thank you for your feedback.
