### ISSUE TITLE
Sysbech 1.0.9 CPU Benchmarking Issue (No. of events are same against different no. Threads)

### ISSUE THREAD

**Issue by jaySiddiqui** [akopytov/sysbench#286]
Dears,
Need help as i am doing some CPU benchmarking for SQL Server.

### VM Specs: 16vCPU and 64GB RAM \ (vsphere 6.5) & RHEL 7.5 OS
_max-Prime=200000
Threads= 10 & 16
Time=10 sec (Default)_

*_*Tests with 10 and 16 threads are producing the same number of events **whereas the events should be more on 16 threads****..?._  

Here is the summary of two tests I just executed on the VM..

### 1. Test with 10 threads`
General statistics:
    total time:                          10.0052s
    total number of events:              32189

Latency (ms):
         min:                                  3.06
         avg:                                  3.10
         max:                                  7.36
         95th percentile:                      3.19
         sum:                              99921.22

Threads fairness:
    events (avg/stddev):           3218.9000/14.24
    execution time (avg/stddev):   9.9921/0.01

### 2 Test with 16 threads
General statistics:
    total time:                          10.0057s
    total number of events:              32517

Latency (ms):
         min:                                  3.06
         avg:                                  4.92
         max:                                630.72
         95th percentile:                      3.82
         sum:                             159887.30

Threads fairness:
    events (avg/stddev):           2032.3125/79.26
    execution time (avg/stddev):   9.9930/0.01

> As you can see the total amount of events is nearly the same with 10 or 16 threads at 17:50

Kindly Advise what can be the issue.

Best Regards
JS

**Comment by akopytov** [comment]
The CPU benchmark scales only up to the number of CPU cores as opposed to CPU threads aka vCPUs. The reason is that hyper-threading hides memory latencies by switching the core between threads if there is a stall in memory access. The CPU benchmark is compute-bound, so it does not benefit from hyper-threading at all.

**Comment by jaySiddiqui** [comment]
__Hi Akopytov,
Thanks for your prompt response. It means benchmark is being done on 8 vCpus (not 16vCPUs_). ### Can you please explain more. 

Also what is the difference between events ### (avg/stdden) and ### total number of events.

But i did the same test with _--time=5_ and there i can see _more events_ for 16 threads and _less for 10_ threads.

**Comment by akopytov** [comment]
In the provided output I can see more average events per thread for 10 threads and less for 16 threads as expected.

**Comment by akopytov** [comment]
I believe it has something to do with dynamic CPU frequency scaling, see my presentation on the topic: https://www.percona.com/live/18/sessions/benchmark-noise-reduction-how-to-configure-your-machines-for-stable-results

**Comment by jaySiddiqui** [comment]
Thanks Ako, Let me have a look at it. and will get back to you for further assistance.

Really appreciate your dedication and commitment.
