### ISSUE TITLE
MySQL Database Performs ~40% Better when the Secondary Index is Created Immediately Following Table Creation in common.lua

### ISSUE THREAD

**Issue by kcamp34** [akopytov/sysbench#289]
Recently I ran some tests comparing various aspects of Sysbench 0.5 vs Sysbench 1.0, as I had been seeing differences in MySQL database performance depending on which version of Sysbench generated the database. To summarize the findings, I determined that the problem was simply the order of creation of the secondary index (the ordering of the line `db_query("CREATE INDEX k_" .. i .. " on sbtest" .. i .. "(k)")`). In Sysbench 0.5 the index is created before any rows are inserted into the table, right after table creation. In Sysbench 1.0 (1.0.16), the index is created after all the rows are inserted into the table.

Steps to reproduce issue:
1. Install sysbench - `sudo apt-get install sysbench`
2. Run parallel_prepare.lua script as follows - `sysbench --test=/usr/share/sysbench/tests/include/oltp_legacy/parallel_prepare.lua --db-driver=mysql --mysql-db=sbtest --oltp_tables_count=100 --oltp-table-size=12000000 --db-ps-mode=disable --num-threads=X --max-requests=X --mysql-user=root --mysql-password=**** --mysql-host=10.x.y.z run` (we attempt to make a dataset that is 5x RAM)
3. Run oltp.lua benchmark as follows - `sysbench --test=/usr/share/sysbench/tests/include/oltp_legacy/oltp.lua --oltp_tables_count=100 --oltp-table-size=12000000 --rand-init=on --db-ps-mode=disable --oltp-dist-type=uniform --num-threads=128 --oltp-read-only=off --oltp-test-mode=complex --percentile=50 --report-interval=1 --max-time=1200 --max-requests=0 --mysql-user=root --mysql-password=**** --mysql-host=10.x.y.z --mysql-db=sbtest run` - Observe results of an average TPS of ~1795
4. Edit `/usr/share/sysbench/tests/include/oltp_legacy/common.lua` to move `db_query("CREATE INDEX k_" .. i .. " on sbtest" .. i .. "(k)")` before any rows are inserted, matching the behavior in Sysbench 0.5.
5. Delete the database created previously, then repeat steps 2-3 - Observe results of an average TPS of ~2450

Please let me know if you have any questions, and I will propose a fix (Pull Request) shortly.

**Comment by akopytov** [comment]
Before we start fixing it, let's define the issue. Indexes created with [Sorted index builds](https://dev.mysql.com/doc/refman/8.0/en/sorted-index-builds.html) (aka "fast index creation", that is what `CREATE INDEX` uses on existing table data) are known to differ from those built with the top-down approach (as would be the case with inserting rows after an index is created).

By default, sorted index builds use the fill factor of 100 (see [`innodb_fill_factor`](https://dev.mysql.com/doc/refman/8.0/en/innodb-parameters.html#sysvar_innodb_fill_factor)). The top-down approach uses the fill factor of 15/16 (~94%), which is not configurable. 

As a result, sorted index builds with the default fill factor may result in more frequent page splits during the benchmark run, and that may explain the performance difference?

**Comment by kcamp34** [comment]
If this were the case then a simple test would be to set `innodb_fill_factor` to 94 and run the above test again, correct? I have tried that have seen no improvement, the results are the same as in the first comment.

**Comment by akopytov** [comment]
Right, that would be a simple test for my hypothesis. I currently don't have capacity to replicate the test, but I still suspect the reason for the results difference is in the InnoDB tuning, i.e. it's not that sysbench does something wrong.

A more robust test for the hypothesis would be monitoring page splits after the index a created and running the actual workload for a fixed duration in three cases:

1. sorted builds with `innodb_fill_factor=100`
2. sorted builds with `innodb_fill_factor=94`
3. indexes built by insertion

To enable the counter:
```sql
set global innodb_monitor_enable = index_page_splits;
```

To read the counter:
```sql
select count_reset from information_schema.innodb_metrics where name='index_page_splits';
```

To reset the counter:

```sql
set global innodb_monitor_reset = index_page_splits;
```

I'd be very surprised if this shows the same rate in all cases.

**Comment by kcamp34** [comment]
After running the test again you seem to be correct! Stats:

innodb_fill_factor=100, index created after rows have been inserted: TPS of ~1200, 1084068 page splits
innodb_fill_factor=94, index created after rows have been inserted: TPS of ~3400, 133029 page splits
innodb_fill_factor=100, index created BEFORE rows have been inserted (innodb_fill_factor is overriden with a value of 94): TPS of ~3500, 149613 page splits


What is odd (and why I initially did not see an increase in TPS) is that I have an automated test which is not showing this increased average TPS. But this issue is likely resolved, I will look into my automated test more myself.
