### ISSUE TITLE
FATAL: Failed to read file! file: 24 pos: 14516224 errno = 0 (Success)

### ISSUE THREAD

**Issue by xypron** [akopytov/sysbench#29]
version: Branch 1.0 HEAD

./sysbench --file-test-mode=rndrd --test=fileio run

gives an error

FATAL: Failed to read file! file: 24 pos: 14516224 errno = 0 (Success)

Best regards

Heinrich Schuchardt

```
sysbench 0.9:  multi-threaded system evaluation benchmark

Running the test with following options:
Number of threads: 1
Initializing random number generator from current time


Extra file open flags: 0
128 files, 16Mb each
2Gb total file size
Block size 16Kb
Number of IO requests: 10000
Read/Write ratio for combined random IO test: 1.50
Periodic FSYNC enabled, calling fsync() each 100 requests.
Calling fsync() at the end of test, Enabled.
Using synchronous I/O mode
Doing random read test
Initializing worker threads...

Threads started!

FATAL: Failed to read file! file: 24 pos: 14516224 errno = 0 (Success)
Operations performed:  0 reads, 0 writes, 0 Other = 0 Total
Read 0b  Written 0b  Total transferred 0b  (0b/sec)
    0.00 Requests/sec executed

General statistics:
    total time:                          0.0005s
    total number of events:              0
    total time taken by event execution: 0.0000s
    response time:
         min:                            18446744073709.55ms
         avg:                                  0.00ms
         max:                                  0.00ms

Threads fairness:
    events (avg/stddev):           0.0000/0.00
    execution time (avg/stddev):   0.0000/0.00
```

**Comment by xypron** [comment]
The generated files test_file.* all have length 0.
The test tries to read
file_req->pos: 14516224 
file_req->size: 16384
Tested on Debian Jessie amd64.

**Comment by akopytov** [comment]
I guess you forgot to run `./sysbench --file-test-mode=rndrd --test=fileio prepare` to create test_file.* before executing `run`.

But yes, this should case be handled more gracefully, so keeping it open.

**Comment by BattleHamster** [comment]
Hi, 

Have the same problem: 
`Extra file open flags: 0
128 files, 280Mb each
35Gb total file size
Block size 16Kb
Number of random requests for random IO: 0
Read/Write ratio for combined random IO test: 1.50
Periodic FSYNC enabled, calling fsync() each 100 requests.
Calling fsync() at the end of test, Enabled.
Using synchronous I/O mode
Doing random read test
Threads started!
FATAL: Failed to read file! file: 127 pos: 213614592 errno = 0 ()
`

files are prepared, but...
`
root@e537c7033261:/test# ls
HDD            test_file.102  test_file.117  test_file.17  test_file.31  test_file.46  test_file.60  test_file.75  test_file.9
hdd_0.txt      test_file.103  test_file.118  test_file.18  test_file.32  test_file.47  test_file.61  test_file.76  test_file.90
hdd_1.txt      test_file.104  test_file.119  test_file.19  test_file.33  test_file.48  test_file.62  test_file.77  test_file.91
hdd_2.txt      test_file.105  test_file.12   test_file.2   test_file.34  test_file.49  test_file.63  test_file.78  test_file.92
hdd_3.txt      test_file.106  test_file.120  test_file.20  test_file.35  test_file.5   test_file.64  test_file.79  test_file.93
hdd_4.txt      test_file.107  test_file.121  test_file.21  test_file.36  test_file.50  test_file.65  test_file.8   test_file.94
hdd_5.txt      test_file.108  test_file.122  test_file.22  test_file.37  test_file.51  test_file.66  test_file.80  test_file.95
hdd_6.txt      test_file.109  test_file.123  test_file.23  test_file.38  test_file.52  test_file.67  test_file.81  test_file.96
hdd_7.txt      test_file.11   test_file.124  test_file.24  test_file.39  test_file.53  test_file.68  test_file.82  test_file.97
hdd_8.txt      test_file.110  test_file.125  test_file.25  test_file.4   test_file.54  test_file.69  test_file.83  test_file.98
hdd_9.txt      test_file.111  test_file.126  test_file.26  test_file.40  test_file.55  test_file.7   test_file.84  test_file.99
test_file.0    test_file.112  test_file.127  test_file.27  test_file.41  test_file.56  test_file.70  test_file.85  tresc
test_file.1    test_file.113  test_file.13   test_file.28  test_file.42  test_file.57  test_file.71  test_file.86
test_file.10   test_file.114  test_file.14   test_file.29  test_file.43  test_file.58  test_file.72  test_file.87
test_file.100  test_file.115  test_file.15   test_file.3   test_file.44  test_file.59  test_file.73  test_file.88
test_file.101  test_file.116  test_file.16   test_file.30  test_file.45  test_file.6   test_file.74  test_file.89
`

**Comment by akopytov** [comment]
Can you show the full sequence of commands to repeat it (including the `prepare` step)? Thank you.

**Comment by xypron** [comment]
```
./sysbench --file-test-mode=rndrd --test=fileio prepare
./sysbench --file-test-mode=rndrd --test=fileio run
```
worked fine for me with Git HEAD (sysbench 1.1.0-1e6e1a9).

```
./sysbench --file-test-mode=rndrd --test=fileio cleanup
./sysbench --file-test-mode=rndrd --test=fileio run
```

produces the error ouptut of @BattleHamster 

@akopytov 
Could you, please, consider providing an output which indicates that the prepare step should be run.

**Comment by akopytov** [comment]
@xypron According to the `ls` output provided by @BattleHamster the files are there, it's just that sysbench is unable to read from a file at a specific offset. So it must be something other than a missing `prepare`. For example, an interrupted prepare. I can also reproduce this when doing `prepare` and `run` with different `--file-total-size` values.

But providing a hint about a missing prepare on 'no such file' errors is still a good idea. So I'm going to merge #138.

**Comment by BattleHamster** [comment]
Hi, 

Just found another one example: 
`sysbench --test=fileio --file-total-size=35G --file-test-mode=seqrd  --max-time=30 --max-requests=0 run`

`Running the test with following options:
Number of threads: 1

Extra file open flags: 0
128 files, 280Mb each
35Gb total file size
Block size 16Kb
Periodic FSYNC enabled, calling fsync() each 100 requests.
Calling fsync() at the end of test, Enabled.
Using synchronous I/O mode
Doing sequential read test
Threads started!
FATAL: Failed to read file! file: 79 pos: 170721280 errno = 0 ()
Done.
`

Another one:
`sysbench --test=fileio --file-total-size=35G --file-test-mode=rndrw  --max-time=300 --max-requests=0 ru`
`Running the test with following options:
Number of threads: 1

Extra file open flags: 0
128 files, 280Mb each
35Gb total file size
Block size 16Kb
Number of random requests for random IO: 0
Read/Write ratio for combined random IO test: 1.50
Periodic FSYNC enabled, calling fsync() each 100 requests.
Calling fsync() at the end of test, Enabled.
Using synchronous I/O mode
Doing random r/w test
Threads started!
FATAL: Failed to read file! file: 112 pos: 292782080 errno = 0 ()
Done.
`

When I startes same tests again - everything works fine. 

Have ni idea why it failed, so just for info, that sometimes it happens :)

**Comment by guidoiaquinti** [comment]
I confirm the same issue on `sysbench 1.0.11` (macOS)

The prepare step is executed correctly (exit code 0)
```
(.virtualenv) ➜  file_io-l6merO ll
total 614400
drwxr-xr-x  130 giaquinti  wheel   4.3K Dec 15 11:35 .
drwxrwxrwt  155 root       wheel   5.1K Dec 15 11:36 ..
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.0
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.1
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.10
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.100
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.101
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.102
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.103
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.104
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.105
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.106
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.107
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.108
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.109
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.11
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.110
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.111
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.112
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.113
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.114
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.115
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.116
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.117
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.118
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.119
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.12
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.120
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.121
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.122
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.123
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.124
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.125
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.126
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.127
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.13
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.14
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.15
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.16
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.17
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.18
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.19
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.2
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.20
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.21
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.22
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.23
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.24
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.25
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.26
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.27
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.28
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.29
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.3
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.30
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.31
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.32
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.33
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.34
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.35
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.36
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.37
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.38
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.39
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.4
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.40
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.41
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.42
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.43
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.44
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.45
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.46
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.47
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.48
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.49
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.5
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.50
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.51
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.52
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.53
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.54
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.55
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.56
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.57
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.58
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.59
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.6
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.60
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.61
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.62
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.63
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.64
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.65
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.66
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.67
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.68
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.69
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.7
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.70
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.71
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.72
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.73
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.74
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.75
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.76
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.77
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.78
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.79
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.8
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.80
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.81
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.82
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.83
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.84
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.85
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.86
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.87
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.88
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.89
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.9
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.90
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.91
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.92
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.93
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.94
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.95
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.96
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.97
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.98
-rw-------    1 giaquinti  wheel   2.3M Dec 15 11:35 test_file.99
```
but the test run is failing
```
(.virtualenv) ➜  file_io-l6merO sysbench --threads=1 --time=5 --file-test-mode=rndrd fileio run
sysbench 1.0.11 (using bundled LuaJIT 2.1.0-beta2)

Running the test with following options:
Number of threads: 1
Initializing random number generator from current time


Extra file open flags: 0
128 files, 16MiB each
2GiB total file size
Block size 16KiB
Number of IO requests: 0
Read/Write ratio for combined random IO test: 1.50
Periodic FSYNC enabled, calling fsync() each 100 requests.
Calling fsync() at the end of test, Enabled.
Using synchronous I/O mode
Doing random read test
Initializing worker threads...

Threads started!

FATAL: Failed to read file! file: 66 pos: 7290880 errno = 0 (Undefined error: 0)
```

**Comment by akopytov** [comment]
@guidoiaquinti the directory listing says `prepare` created files with the 2.3M size, but `run` is being executed with a default `--file-total-size`, so it expects files to be 16M in size. I can reproduce that. So the behavior is technically correct, but I'd like to make it less error-prone and more user-friendly. I think sysbench should validate file sizes when opening them on startup.

**Comment by nglszhaosi** [comment]
when i test  rndrw  rndwr  rndrd  with 8k file-size and 10000 file-num  ,i got a problem, 

sysbench 1.0.17 (using system LuaJIT 2.0.4)

Running the test with following options:
Number of threads: 2
Report intermediate results every 5 second(s)
Initializing random number generator from current time


Extra file open flags: (none)
10000 files, 8.1914KiB each
79.994MiB total file size
Block size 1KiB
Number of IO requests: 0
Read/Write ratio for combined random IO test: 1.50
Periodic FSYNC enabled, calling fsync() each 100 requests.
Calling fsync() at the end of test, Enabled.
Using synchronous I/O mode
Doing random read test
Initializing worker threads...

Threads started!

FATAL: Failed to read file! file: 0 pos: 960 errno = 29 (Illegal seek)
