### ISSUE TITLE
build version 0.5 on windows LNK2019 errors

### ISSUE THREAD

**Issue by Manoj-M-97** [akopytov/sysbench#290]
There are a lot of errors while building sysbench build version 0.5 on windows without mysql support. 
[Errors.docx](https://github.com/akopytov/sysbench/files/2865026/Errors.docx)

**Comment by akopytov** [comment]
Unfortunately, I don't have capacity to support version 0.5 in general and Windows builds in particular. I could leave the bug open in case someone else wants to chime in, but in my experience that is extremely unlikely. So I'm closing it as Won't Fix.
