### ISSUE TITLE
deb package on Ubuntu 18.04 does not install the latest oltp tests

### ISSUE THREAD

**Issue by vadimtk** [akopytov/sysbench#292]
I use 

`curl -s https://packagecloud.io/install/repositories/akopytov/sysbench/script.deb.sh | sudo bash`

to install sysbench (current version 1.0.16)

but the option `create_table_options` is not present in installed lua tests
 `cat /usr/share/sysbench/oltp_common.lua  | grep create_table_options` - null result

I would love to have the latest lua tests installed, so I can use `create_table_options`

**Comment by akopytov** [comment]
`create_table_options` is only available in the master branch aka "sysbench 1.1". There is quite a number of requests to release it, so I'll be doing it pretty soon.

For now, you can just use the `sysbench-prereleases` repository, i.e.:

```console
curl -s https://packagecloud.io/install/repositories/akopytov/sysbench-prereleases/script.deb.sh | sudo bash
```
