### ISSUE TITLE
Cant seem to call sb_rand_pareto inside script

### ISSUE THREAD

**Issue by jonathanhartley** [akopytov/sysbench#293]
function event(thread_id)
  local outcomerange = tonumber(os.date("1%m%d%H"))*100000
  tsbi=(os.time()*1000)+sb_rand_uniform(0,999)
  local outcomes = sb_rand_pareto(1,8)

FATAL: `thread_run' function failed: ./book_place.lua:139: attempt to call global 'sb_rand_pareto' (a nil value)

Can call sb_rand_gaussian(0,100000) without issue ?

**Comment by akopytov** [comment]
`sb_rand_*()` functions is legacy API provided only for compatibility. Try using `sysbench.rand.*` API: https://github.com/akopytov/sysbench/blob/1.0/src/lua/internal/sysbench.rand.lua

For example, there are `sysbench.rand.uniform()` and `sysbench.rand.pareto()`.
