### ISSUE TITLE
Cross-Compile sysbench for aarch64

### ISSUE THREAD

**Issue by Theil** [akopytov/sysbench#294]
Hi,

I am trying to cross-compile sysbench from the latest sources (especially for aarch64).
I have seen that there are aarch64 packages available at packagecloud, and the Makefile structure also indicates that cross-compilation might already work.

However I had some issues to figure out how to do it on my own.
After some changes to the Makefiles and config Files I got an arm64 executable but I get the same error as Huang Jinhua: 
https://github.com/akopytov/sysbench/issues/109
Unfortunately this issue was closed without a proper solution...

Without touching the Makefiles and Config Files I was not able to compile at all.
Did you already try to cross-compile it? Should it work out of the box?

Thanks in advance

**Comment by akopytov** [comment]
Unfortunately, I can't help here. I've never tried cross-compilation for aarch64. The existing packages on packagecloud were built natively. I have also never seen the error from #109 myself, so never had a chance to look into it.

**Comment by Theil** [comment]
Hi @akopytov 
Thank you very much for the quick response.

Actually I was able to solve it by adding the -rdynamic flag as you mentioned in https://github.com/akopytov/sysbench/issues/174
Now I can run the statically linked sysbench on my arm64 target.

The hacks that I did to the Makefiles are very ugly but basically not complicated.
I will clean it up and also have a look at compiling for arm32, after that I will share it in some way.

Thank you very much
BR

**Comment by akopytov** [comment]
Thanks for the update.

**Comment by zeehha** [comment]
Can you please explain how to build sysbench as a statically linked binary? I was trying
./configure CFLAGS="-static" LDFLAGS="-static --with-gnu-ld ...",
./make
but the resulting binary is still dynamically linked.

Best,
Chris

**Comment by tavivia** [comment]
@Theil @akopytov  I was wondering if you had any updates on this. I am not able to compile sysbench for arm64 at all as it says the compiler needs updated, but this should not cause and issue. Is there anyway I could get the executable for sysbench that is statically linked with arm64 compilation.

**Comment by RomanovSergey** [comment]
Have you tried compiling this sysbench for arm64? :
https://github.com/logicalclocks/sysbench-0.4.12
