### ISSUE TITLE
sysbench in virtualized environments

### ISSUE THREAD

**Issue by Daparrag** [akopytov/sysbench#296]
### sysbench in virtualized environments

Hi all. 

My name is diego and I'm computer science student. recently I start to work with sysbench, and small question came to my mind.

I would like to know which is the internal sysbench architecture. Most specifically, i want to know which are its system requirements. Or in another words, which system resources are used by sysbench in order to perform measures. 

This is important because I want to use it  in a virtualized embedded systems, where the Guest OS doesn't have a complete view of the underlying platform (I.e. CPU control registers, performance monitor units  PMU, etc.)

**Comment by akopytov** [comment]
sysbench is a customizable workload generator, i.e. users define which system resources to stress by choosing workloads or implementing their own ones. sysbench also comes with a few bundled workloads [listed in README](https://github.com/akopytov/sysbench/blob/1.0/README.md#sysbench). 

There are some microbenchmarks stressing CPU or memory. But the most popular ones are database load generators (the `oltp_*` scripts), where it's hard to name a particular resource being targeted – it all depends on too many things, including workload parameters, available resources and database server configuration.
