### ISSUE TITLE
No buster release

### ISSUE THREAD

**Issue by Cat5TV** [akopytov/sysbench#297]
After running the script to install the repository, I'm greeted with this lovely output:

`Err:7 https://packagecloud.io/akopytov/sysbench/debian buster Release          
  404  Not Found [IP: 52.9.242.175 443]
Reading package lists... Done
E: The repository 'https://packagecloud.io/akopytov/sysbench/debian buster Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.`

I'll just compile from source, but thought it'd be nice for you to know it's not loading up on Debian buster.

**Comment by akopytov** [comment]
Debian Buster packages for 1.0.17 are now available in the packagecloud repository. Thanks for letting me know!

**Comment by AcharyaOne** [comment]
same is happening now for debian bullseye release
