### ISSUE TITLE
E: Unable to locate package sysbench

### ISSUE THREAD

**Issue by Cat5TV** [akopytov/sysbench#298]
Having added Buster release as per #297 I now receive the following:

```
...
The repository is setup! You can now install packages.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package sysbench
```

apt now updates fine, but no package available.

Tried wildcard just for good measure:

```
# apt install sysbench*
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package sysbench*
E: Couldn't find any package by glob 'sysbench*'
E: Couldn't find any package by regex 'sysbench*'
```

apt update uses the repo just fine:

```
Hit:5 https://packagecloud.io/akopytov/sysbench/debian buster InRelease        
Fetched 1,335 B in 2s (551 B/s)
```

FYI, in case it's relevant, I'm on aarch64:

```uname -a
Linux nems 4.4.167-1161-rockchip-ayufan-g6f1664023387 #1 SMP Fri Mar 22 23:03:38 UTC 2019 aarch64 GNU/Linux
```

**Comment by akopytov** [comment]
Yes, aarch64 packages aren't there. I'll need to make a few CI-related changes to build them automatically.

**Comment by Cat5TV** [comment]
Any chance this will happen within the next week? I'm writing an article about the brand new ODROID-N2 for Odroid Magazine and on a deadline. I'd _love_ to use sysbench in the review. Thanks man!!

**Comment by akopytov** [comment]
For now, I just built 1.0.17 packages for Buster manually. Enjoy!

**Comment by Cat5TV** [comment]
Thanks Alexey!

**Comment by Cat5TV** [comment]
Hey @akopytov - any idea why sysbench disappeared from the Buster repo again on the aarch64? I'm once again unable to install from your repo.

**Comment by raginigupta6** [comment]
I am having the same issue on Rasbpian OS, unable to locate package sysbench. What is the workaround?

**Comment by hardenchant** [comment]
```bash
echo "deb http://deb.debian.org/debian buster-backports main" >> /etc/apt/sources.list
apt-get update
apt-get -t buster-backports install sysbench
```

@raginigupta6 this can help you

**Comment by ghltshubh** [comment]
@hardenchant  `E: The value 'buster-backports' is invalid for APT::Default-Release as such a release is not available in the sources`

**Comment by ghltshubh** [comment]
@hardenchant I am getting this error `E: The value 'buster-backports' is invalid for APT::Default-Release as such a release is not available in the sources`
