### ISSUE TITLE
Runtime segmentation fault with the latest version as of 2015/04/22

### ISSUE THREAD

**Issue by maximmai** [akopytov/sysbench#3]
It seems that the segmentation fault is coming from 
https://github.com/akopytov/sysbench/commit/7a0e384cf05bd819cc798279e4efd27f3b896e94

OS: Ubuntu 14.04 x86_64 kernel 3.13.0-49
DB in test: MariaDB 5.5
Command to run: 

	sysbench --test=tests/db/oltp.lua prepare
	[Thread debugging using libthread_db enabled]
	Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
	sysbench 0.5:  multi-threaded system evaluation benchmark

	[New Thread 0x7ffff639b700 (LWP 26654)]
	[Thread 0x7ffff639b700 (LWP 26654) exited]
	Creating table 'sbtest1'...

	Program received signal SIGSEGV, Segmentation fault.
	mysql_drv_query (sb_conn=0x8a7aa0, 
	    query=0x8acf68 "CREATE TABLE sbtest1 (\nid INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,\nk INTEGER UNSIGNED DEFAULT '0' NOT NULL,\nc CHAR(120) DEFAULT '' NOT 		NULL,\npad CHAR(60) DEFAULT '' NOT NULL,\nPRIMARY KEY (id)\n) /*! E"..., rs=<optimized out>) at drv_mysql.c:799
	799	  MYSQL *con = db_mysql_con->mysql;
	(gdb) bt
	#0  mysql_drv_query (sb_conn=0x8a7aa0, 
	    query=0x8acf68 "CREATE TABLE sbtest1 (\nid INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,\nk INTEGER UNSIGNED DEFAULT '0' NOT NULL,\nc CHAR(120) DEFAULT '' NOT NULL,\npad CHAR(60) DEFAULT '' NOT NULL,\nPRIMARY KEY (id)\n) /*! E"..., rs=<optimized out>) at drv_mysql.c:799
	#1  0x000000000040a178 in db_query (con=0x8a7aa0, 
	    query=0x8acf68 "CREATE TABLE sbtest1 (\nid INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,\nk INTEGER UNSIGNED DEFAULT '0' NOT NULL,\nc CHAR(120) DEFAULT '' NOT NULL,\npad CHAR(60) DEFAULT '' NOT NULL,\nPRIMARY KEY (id)\n) /*! E"...) at db_driver.c:473
	#2  0x0000000000410d12 in sb_lua_db_query (L=0x89d910) at script_lua.c:610
	#3  0x0000000000418005 in luaD_precall (L=L@entry=0x89d910, func=func@entry=0x8a7c80, nresults=nresults@entry=0) at ldo.c:319
	#4  0x0000000000426fbf in luaV_execute (L=L@entry=0x89d910, nexeccalls=2, nexeccalls@entry=1) at lvm.c:587
	#5  0x000000000041897d in luaD_call (L=0x89d910, func=0x89dd50, nResults=<optimized out>) at ldo.c:377
	#6  0x00000000004171b9 in luaD_rawrunprotected (L=L@entry=0x89d910, f=f@entry=0x413c70 <f_call>, ud=ud@entry=0x7fffffffdd80)
	    at ldo.c:116
	#7  0x0000000000418aba in luaD_pcall (L=L@entry=0x89d910, func=func@entry=0x413c70 <f_call>, u=u@entry=0x7fffffffdd80, old_top=128, 
	    ef=<optimized out>) at ldo.c:461
	#8  0x000000000041569b in lua_pcall (L=0x89d910, nargs=nargs@entry=0, nresults=nresults@entry=1, errfunc=errfunc@entry=0) at lapi.c:817
	#9  0x00000000004110df in sb_lua_cmd_prepare () at script_lua.c:511
	#10 0x0000000000404a0c in main (argc=<optimized out>, argv=<optimized out>) at sysbench.c:1199

**Comment by akopytov** [comment]
Should be fixed now. Thank you!
