### ISSUE TITLE
Megabit vs MeBibit

### ISSUE THREAD

**Issue by xypron** [akopytov/sysbench#30]
The prefix M refers to mega defined as 10^6.
The prefix Mi refers to mebi defined as 2^20.

The code has the following constant:
static const double megabyte = 1024.0 * 1024.0;

Please, do not output Mb where you mean Mib.

See IEC 80000-13:200 or read https://en.wikipedia.org/wiki/Binary_prefix.

Best regards

Heinrich Schuchardt

**Comment by akopytov** [comment]
Thanks. This has already been reported a few times, and there's an open issue for it here: https://github.com/akopytov/sysbench/issues/12.

It's on my short-term TODO to fix this.
