### ISSUE TITLE
macOS Homebrew: flag --with-postgresql does not exist

### ISSUE THREAD

**Issue by martin-juul** [akopytov/sysbench#302]
```
brew install sysbench --with-postgresql
Error: invalid option: --with-postgresql
```

the [formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/sysbench.rb) doesn't have it, though it preconfigures sysbench with mysql support.

**Comment by akopytov** [comment]
I guess this should be reported to the Homebrew formula maintainer. There's nothing I can do to fix it.
