### ISSUE TITLE
Benchmark Stored Procedure with sysbench

### ISSUE THREAD

**Issue by lsadehaan** [akopytov/sysbench#304]
Hi, I am trying to benchmark a MySQL stored procedure using sysbench and a custom lua script.

I get the following error:
FATAL: `thread_run' function failed: ./testSP.lua:31: SQL error, errno = 2014, state = 'HY000': Commands out of sync; you can't run this command now

The script is very basic and just calls a stored procedure as follows:
	con:query("CALL `testschema`.`test_sp`('12345', 'FooBar', '2019-05-04 03:29:27');")

Do I need to do something to "end off" the SP call before doing the next one?
Is there any documentation of the sysbench specific Lua functions?

**Comment by bystro** [comment]
https://www.percona.com/blog/2019/04/25/creating-custom-sysbench-scripts/

**Comment by haocoder** [comment]
@lsadehaan hi, I encounter the same problem using sysbench-1.0. Did you solved it?

**Comment by haocoder** [comment]
Unfortunatel, according to https://www.percona.com/blog/2019/04/25/creating-custom-sysbench-scripts/, it still have same problem, @akorotkov , is there any advice or examples  to test mysql stored procedure with sysbench1.0?

**Comment by lsadehaan** [comment]
> @lsadehaan hi, I encounter the same problem using sysbench-1.0. Did you solved it?

No, I didn't solve it. Instead I used a different benchmarking tool - something very basic. I think it might be easiest to write a small python script to just call the SP in a loop.

**Comment by haocoder** [comment]
It's a sysbench bug,  as https://dev.mysql.com/doc/refman/8.0/en/commands-out-of-sync.html described, I modify function mysql_drv_query() in drv_mysql.c by putting mysql_store_result() and mysql_free_result() in a while loop, it works.
`mysql_drv_query() {
   ......
  do{
     mysql_store_result();
     ....
     mysql_free_result();
  }while(!mysql_next_result(conn));
 ....
}`

**Comment by akopytov** [comment]
This is fixed in `master` (to be released as sysbench 2.0) and here's the commit message:

> SQL API: add multiple result sets API
> 
> MySQL may return multiple result sets from a call to a stored
> procedure (the CALL statement), or when multiple queries are specified
> in a single client request. The application is supposed to process those
> multiple result sets one by one with calls to `mysql_next_result()`, or
> its prepared statements counterpart, `mysql_stmt_next_result()`.
> 
> Additionally, there is the `mysql_more_results()` call which allows the
> application to check if more result sets are available and works for
> both regular queries and prepared statements API.
> 
> One way to handle multiple results in sysbench would be consuming all
> result sets silently in the MySQL driver, but that would make it
> impossible for scripts to get access to individual result sets returned
> by a stored procedure.
> 
> Now sysbench exposes those MySQL client API calls to the SQL API, so it
> is up to the script authors to handle multiple result sets when either
> stored procedures are used in a benchmark script, or multiple queries
> are passed to `sql_connection:query()`:
> 
> - sql_connection:next_result()
> - sql_connection:more_results()
> - sql_statement:next_results()
> 
> Here is an example how multiple results can be handled in a benchmark
> script:
> 
> ```lua
>    local rs = con:query([[CALL p1("foo")]])
>    while rs ~= nil do
>       -- handle the result set
>       rs = con:next_result()
>    end
> ```
> 
> Here is a prepared statement example:
> 
> ```lua
>    stmt = con:prepare("CALL p1(?)")
>    param = stmt:bind_create(sysbench.sql.type.CHAR, 10)
>    stmt:bind_param(param)
>    param:set("bar")
>    rs = stmt:execute()
> 
>    while rs ~= nil do
>       rs = stmt:next_result()
>    end
> ```
