### ISSUE TITLE
Reliability of Reported Latencies for MySQL Queries

### ISSUE THREAD

**Issue by Velsheda** [akopytov/sysbench#305]
Hi!

Currently, I am using sysbench to investigate on SQL query latencies in different setups. There are several contraints forcing me to choose a rather odd DB setup that yields really low values in terms of throughput, so please do not be surprised about the absolute values of the benchmark evaluation, they are not an issue for me. 

This is the output produced by sysbench during the tests:
```
sysbench 1.0.11 (using system LuaJIT 2.1.0-beta3)

Running the test with following options:
Number of threads: 1
Target transaction rate: 100/sec
Initializing random number generator from seed (1).


Initializing worker threads...

Time limit exceeded, exiting...
Done.

SQL statistics:
    queries performed:
        read:                            8680
        write:                           0
        other:                           1240
        total:                           9920
    transactions:                        620    (30.94 per sec.)
    queries:                             9920   (495.03 per sec.)
    ignored errors:                      0      (0.00 per sec.)
    reconnects:                          0      (0.00 per sec.)

General statistics:
    total time:                          20.0378s
    total number of events:              620

Latency (ms):
         min:                                 47.84
         avg:                               7115.40
         max:                              14258.73
         95th percentile:                  13550.80
         sum:                            4411545.46

Threads fairness:
    events (avg/stddev):           620.0000/0.00
    execution time (avg/stddev):   4411.5455/0.00
```
What seems suspicious to me are the latency and execution time values. Particularly the latency sum of 4400s is much higher than it should be possible for a (single-threaded) application running on my four-core machine for 20s. How to read this kind of output? Can I rely on the precision of the latencies reported by sysbench in oltp mode?

Thanks in advance for any hints!

**Comment by akopytov** [comment]
Hi!

Latency reports in the bounded rate mode (the `--rate` option) got broken in 1.0.8 and fixed again in 1.0.16. Here's the commit: https://github.com/akopytov/sysbench/commit/bb8c3b04c58ceb0ac74f2e4ff5421d526d873ed0
