### ISSUE TITLE
sysbench for alpine linux

### ISSUE THREAD

**Issue by Anjali05** [akopytov/sysbench#307]
Is there a sysbench apk package which can be used in alpine linux?

**Comment by akopytov** [comment]
Currently, there are no automated apk builds for sysbench releases. Changing that would require updating Alpine Linux images to recent version in [packpack-docker-images](https://github.com/packpack/packpack-docker-images/tree/master/alpine/3.6) and adding support for Alpine Linux in [.travis.yml](https://github.com/akopytov/sysbench/blob/master/.travis.yml).

I'm also not sure if [packagecloud](https://packagecloud.io/) repositories support APK.

**Comment by akopytov** [comment]
Apparently APK is not a supported package type in packagecloud: https://packagecloud.io/docs#which_types_of_packages

So, making those packages available is anothe problem to solve in addition to building them.

I think filing a feature request for Alpine Linux to provide sysbench APK in their own repositories would also make sense.

**Comment by Anjali05** [comment]
> Apparently APK is not a supported package type in packagecloud: https://packagecloud.io/docs#which_types_of_packages
> 
> So, making those packages available is another problem to solve in addition to building them.
> 
> I think filing a feature request for Alpine Linux to provide sysbench APK in their own repositories would also make sense.

Thanks!

**Comment by Anjali05** [comment]
@akopytov Is there any wiki that explains what a particular benchmark is doing and explains the output? For eg, in the CPU test I don't really get what the eps(events per second) is and also the time does not change for my tests. So  I am not sure if the benchmark run to a particular time by default.

**Comment by carlocorradini** [comment]
Any update? 😥
