### ISSUE TITLE
sysbench with ssl options

### ISSUE THREAD

**Issue by mirrorspurs** [akopytov/sysbench#308]
Hi,
Recently i've been trying to use sysbench to test the performance of mysql with ssl authentications and some problems make me confused. 
1. In my opinion, if i want to use sysbench to test mysql-ssl performance, first of all i need to run mysql_ssl_setup and start the mysqld service on server side, then utilize sysbench with mysql-ssl-ca, mysql-ssl-key and mysql-ssl-cert options to realize the test on client side,  is that right?
2.  when i run the .lua in the directory /oltp_legacy, i only need to configure the mysql-ssl-ca options like:
**sysbench /usr/sysbench/share/sysbench/tests/include/oltp_legacy/insert.lua --ta
bles=10 --table-size=100 --mysql-host=127.0.0.1 --mysql-port=3307 --mysql-user=user1 --db-driver=mysql --mysql-ssl-ca=/root/mysql-5.7.26/install/data/cacert.pem --mysql-db=sbtest prepare**,
i can test the performance correctly. However, when i use the .lua which isn't in the directory /oltp_legacy, the answer is:

**sysbench /usr/sysbench/share/sysbench/oltp_read_write.lua --tables=10 --table-s
ize=100 --mysql-host=127.0.0.1 --mysql-port=3307 --mysql-user=user1 --db-driver=mysql --mysql-ssl-ca=/root/mysql-5.7.26/install/data/cacert.pem --mysql-db=sbtest prepare**
**sysbench 1.0.17 (using bundled LuaJIT 2.1.0-beta2)

invalid option: --mysql-ssl-ca=/root/mysql-5.7.26/install/data/cacert.pem**,
which makes me confused. i wanna know how can i test the oltp_read_write.lua with mysql-ssl options?

I would keep waiting for your response and really appreciate your help, thank you~!

**Comment by akopytov** [comment]
sysbench 1.0 does not have the `--mysql-ssl-ca` option, and legacy scripts ignore unknown options for compatibility reasons (don't use the legacy scripts, by the way).

`--mysql-ssl-ca`, `--mysql-ssl-cert` and `--mysql-ssl-key` are only available in sysbench 1.1. Which is the `master` branch in Git. You can either build it from source, or use binary packages from the `sysbench-prereleases` repo in packagecloud.

If you do need to use sysbench 1.0, the SSL client key, client certificate and the CA certificate are hard-coded to the following files in the current directory:
```
client-key.pem
client-cert.pem
cacert.pem
```

**Comment by mirrorspurs** [comment]
I am so grateful for your help! 

But i still have a question, when the ssl function on mysql server is on, and i wanna test the performance under ssl connection, do i need to assign the '-mysql-ssl=on' option explicitly?  

In my opinion, i can start up the ssl function on server side and execute following commands:
**sysbench /usr/local/share/sysbench/oltp_read_write.lua --tables=100 --table-size=1000 --threads=8 --mysql-db=sbtest --mysql-user=root --time=300 --mysql-password=xxx --mysql-host=xxx.xxx.xxx.xxx --mysql-port=3306 prepare**, which indicates that this test is through ssl connection. 
Then i shut down the ssl function on server side and execute the same commands mentioned above, which indicates that this test is not through ssl connection. 
I wonder whether my viewpoint is correct and really wish to get your help, thanks again with best kind regards.

**Comment by akopytov** [comment]
sysbench enforces SSL, but only if the client library supports it. You can read more about enforcing SSL connections here: https://dev.mysql.com/doc/refman/en/c-api-encrypted-connections.html

If the client library does not define `MYSQL_OPT_SSL_MODE`, sysbench will try to use SSL if `--mysql-ssl` is specified, but will not enforce it, i.e. fall back to unencrypted connections if SSL is not supported by the server.

**Comment by mirrorspurs** [comment]
According to your response, sysbench 1.0 will look for client-key.pem client-cert.pem and cacert.pem in the current directory when --mysql-ssl=on, but i don't have client-key.pem and client-cert.pem because the server is not under my control. So now can i test the performance with ssl?

**Comment by akopytov** [comment]
You don't need control over server to use SSL on the client side. It's all documented at https://dev.mysql.com/doc/refman/5.7/en/using-encrypted-connections.html#using-encrypted-connections-client-side-configuration

**Comment by codeTranMan** [comment]
sysbench version 1.0.17

sysbench /usr/share/sysbench/tests/include/oltp_legacy/oltp.lua --mysql-ssl=on --db-driver=mysql --mysql-host=xxx.xxx.xxx.xxx --mysql-port=3307 --mysql-user=root --mysql-password=root --mysql-db=test3307 --oltp-tables-count=10 --oltp-table-size=10 --threads=4 --time=60 --report-interval=10 run

while the threads > 3 :
FATAL: error 2026: SSL connection error: SSL_CTX_new failed
(last message repeated 1 times)
FATAL: `thread_run' function failed: /usr/share/sysbench/tests/include/oltp_legacy/oltp.lua:43: Failed to connect to the database

how to solve this problem？
