### ISSUE TITLE
Does the skip_trx work correctly？

### ISSUE THREAD

**Issue by cyckax** [akopytov/sysbench#309]
Hi,

when I test mysql use oltp_read_write.lua, and I set the --skip_trx=on. This option means Don't start explicit transactions and execute all queries in the AUTOCOMMIT mode. But I find the lat 95% is about 550ms, and qps more than 30000,tps more than 8000. I check the slow query log and the log said one delete command or update command only takes 0.1s, so does the skip_trx work correctly？

**Comment by akopytov** [comment]
Yes,`--skip-trx` works with `oltp_read_write.lua`. You can look at how it is implemented here: https://github.com/akopytov/sysbench/blob/1.0/src/lua/oltp_read_write.lua#L44-L65
