### ISSUE TITLE
Bit vs Byte

### ISSUE THREAD

**Issue by xypron** [akopytov/sysbench#31]
The code confuses me concerning bits and bytes:

    log_text(LOG_NOTICE, "Read %sb  Written %sb  Total transferred %sb  "
             "(%sb/sec)",
             sb_print_value_size(s1, sizeof(s1), bytes_read),

Please, consistently use B for byte and b for bit.

Best regards

Heinrich Schuchardt

**Comment by akopytov** [comment]
Fixed in 1.0 with https://github.com/akopytov/sysbench/pull/32.
