### ISSUE TITLE
Latency computation correctness

### ISSUE THREAD

**Issue by pramodc** [akopytov/sysbench#311]
Hello,
I need some help in understanding how the latency is being measured by sysbench. I am running sysbench (1.1.0-faaff4f) with single thread and I am seeing QPS of 4150.  I expected average latency to be 1/4150 = 0.24ms. However the average latency reported is 3.85ms. Is my expectation wrong? Can you please explain how the latency is being computed in sysbench? Below is a snippet of my run. I appreciate your help. Thanks!

```
 sysbench --db-driver=mysql --report-interval=3 --warmup-time=120 --mysql-storage-engine=innodb --table-size=5000000 --tables=32 --rand-type=uniform --db-ps-mode=disable --threads=1 --time=120 --mysql-
host=mysql80 --mysql-port=3306 --mysql-user=sbtest --mysql-password=xxx oltp_read_only run
sysbench 1.1.0-faaff4f (using bundled LuaJIT 2.1.0-beta3)
...
[ 117s ] thds: 1 tps: 258.32 qps: 4133.04 (r/w/o: 3616.41/0.00/516.63) lat (ms,95%): 4.10 err/s: 0.00 reconn/s: 0.00
SQL statistics:
    queries performed:
        read:                            435780
        write:                           0
        other:                           62255
        total:                           498035
    transactions:                        31128  (259.39 per sec.)
    queries:                             498035 (4150.16 per sec.)
    ignored errors:                      0      (0.00 per sec.)
    reconnects:                          0      (0.00 per sec.)

Throughput:
    events/s (eps):                      259.3919
    time elapsed:                        120.0039s
    total number of events:              31128

Latency (ms):
         min:                                    3.35
         avg:                                    3.85
         max:                                  208.35
         95th percentile:                        4.03
         sum:                               119904.93

Threads fairness:
    events (avg/stddev):           31127.0000/0.00
    execution time (avg/stddev):   119.9049/0.00
```

**Comment by pramodc** [comment]
It looks like latency reported is for the transactions as opposed queries. Is there a option to report for queries?

**Comment by akopytov** [comment]
That's correct, sysbench measures latency for execution units called "events". What makes up a single event is defined by each particular Lua script. Most oltp_* scripts define event as a single transactions. One exception to that rule is oltp_point_select which was specifically implemented to evaluate simple SELECT statements in AUTOCOMMIT (i.e. single-statement transactions) mode. You can also implement your own Lua scripts. It should be fairly straightforward, especially if you use existing scripts as examples.
