### ISSUE TITLE
Custom Lua script for Postgres DML

### ISSUE THREAD

**Issue by pinakesh** [akopytov/sysbench#315]
Hi Team,

Please can you provide sample LUA script for DML operation on postgres like simple queries as below :-

select count(*) from table;
insert into table_name values(100,200,..);
update table_name set col1=something where coln=something_else;

I checked this link https://www.percona.com/blog/2019/04/25/creating-custom-sysbench-scripts/ but it gives details only about MySql like driver initialization as drv = sysbench.sql.driver() and opening connection as con = drv:connect(), etc.

I dont know what will be the equivalent functions/keywords/syntax for Postgres.

Thanks

**Comment by stedounet** [comment]
It will work the same way (for the most part), all you have to do is to change parameters when calling sysbench :
`--db-driver=pgsql --pgsql-host=192.168.56.40 --pgsql-password=sbtest --pgsql-user=sbtest --pgsql-port=5432`

**Comment by akopytov** [comment]
Right, like @stedounet said, the `sysbench.sql.driver()` call returns a default driver, which is defined by the command line option `--db-driver` (which in turn defaults to "mysql"). 

You can also override the command line option in your script by passing the driver name: 
```lua
drv = sysbench.sql.driver("pgsql")
```
