### ISSUE TITLE
cannot build sysbench on mips64el

### ISSUE THREAD

**Issue by xieyanker** [akopytov/sysbench#318]
Hello, I need to build the sysbench on mips64el arch,but it seems that the platform is not supported. Is there exist any idea to build it on mips64el? 
```shell
mkdir tmp
tar -C . -cf - ck | tar -xf - -C tmp/
chmod -R u+w tmp
cd tmp/ck &&                        \
CC="gcc -std=gnu99"                          \
CFLAGS="-O3 -funroll-loops -ggdb3  -D_GNU_SOURCE "      \
LDFLAGS="-L/usr/local/lib"                \
  ./configure  \
  --prefix=/root/xujingsong/sysbench/third_party/concurrency_kit && \
make && \
make install
Detecting operating system.......success [linux]
Detecting machine architecture...failed  [unsupported]
```

```shell
Linux master2 3.10.0-862.9.1.ns7_4.37.mips64el #1 SMP PREEMPT Tue Feb 26 19:23:39 CST 2019 mips64el mips64el mips64el GNU/Linux
```

**Comment by akopytov** [comment]
This is a ConcurrencyKit limitation: https://github.com/concurrencykit/ck/issues/80

**Comment by sbahra** [comment]
@akopytov For MIPS, you can always just enable the GCC built-in port. That will be sub-optimal but might be with-in acceptable range and still correct. This falls back to using compiler built-ins. What do you think?

**Comment by akopytov** [comment]
@sbahra Compiler built-ins look like an acceptable option to me. Thanks for reminding me. I'm going to implement it for mips64el.

**Comment by akopytov** [comment]
@xieyanker can you try if building the latest git works for you?

**Comment by xieyanker** [comment]
@akopytov Thanks for your help, I rebuild from the latest code, but still not work.

```shell
mkdir tmp
tar -C . -cf - ck | tar -xf - -C tmp/
chmod -R u+w tmp
cd tmp/ck &&                        \
CC="gcc -std=gnu99"                          \
CFLAGS="-O3 -funroll-loops -ggdb3  -D_GNU_SOURCE "      \
LDFLAGS="-L/usr/local/lib"                \
  ./configure --use-cc-builtins \
  --prefix=/root/xujingsong/sysbench/third_party/concurrency_kit && \
make && \
make install
Detecting operating system.......success [linux]
Detecting machine architecture...failed  [unsupported]
```

**Comment by akopytov** [comment]
@xieyanker right, sorry, this is not as easy as I thought. I would suggest reporting this to ConcurrencyKit. I'm happy to merge the fix as soon as it is available.

**Comment by sbahra** [comment]
Committed an improvement to master now.

Up until now, configure profile would be used for platforms without official coverage (on which manual validation of generated code was also performed). However, I have committed a fix for this. You should now see a different behavior @xieyanker.

Can you try again? Does sysbench behave as expected?

**Comment by xieyanker** [comment]
@sbahra @akopytov Thanks for your help, I have successfully built it.
```shell
root@master1:[/root/xujingsong/sysbench]sysbench --version
sysbench 1.1.0-74f3b6b
```
But it seems that the `third_party` of the `sysbench` has not been updated for a long time, I re-pull the latest code from the https://github.com/concurrencykit/ck.git.

**Comment by zzsuki** [comment]
i am facing the same problem as u did. can u tell me how can u solved this situation.
