### ISSUE TITLE
TLS control options for postgres

### ISSUE THREAD

**Issue by pramodc** [akopytov/sysbench#326]
Is there a command line option to control to the TLS mode when connecting to postgres? Unlike --mysql-ssl, pgsql-ssl don't seem to be present.

**Comment by akopytov** [comment]
Right, there are no options to control TLS for the PostgreSQL driver. As usual, patches are welcome :)

**Comment by christianricci** [comment]
Alexey are planning to merge this request at any point? if not, do you see a problem with this request?
