### ISSUE TITLE
differences between lua scripts in /usr/share/sysbench and /usr/share/sysbench/tests/include/oltp_legacy

### ISSUE THREAD

**Issue by junli0411** [akopytov/sysbench#331]
what's the differences between the scripts in /usr/share/sysbench and /usr/share/sysbench/tests/include/oltp_legacy ?  
which one should we use ?

**Comment by akopytov** [comment]
You should use the ones in `/usr/share/sysbench`. The legacy ones are only used for regression testing purposes.
