### ISSUE TITLE
RHEL/CentOS Installing script:flaw fix

### ISSUE THREAD

**Issue by chengyuqi** [akopytov/sysbench#332]
Hi ，
i was learning the install in centos7.7 and i found the function detect_os in the install script  has a bug.
notice line 65:dist=`cat /etc/redhat-release | awk '{ print $3 }' | awk -F '.' '{ print $1 }'`

here is output
[admin@localhost ~]$ cat /etc/redhat-release
CentOS Linux release 7.7.1908 (Core)
[admin@localhost ~]$ cat /etc/redhat-release | awk '{ print $3 }' | awk -F '.' '{ print $1 }'
release
[admin@localhost ~]$ cat /etc/redhat-release | awk '{ print $4 }' | awk -F '.' '{ print $1 }'
7

so,we should change print $3 to print $4 to get the corrected dist

**Comment by akopytov** [comment]
I've tried the packagecloud install script and it works fine for me in a Centos 7.7 Docker container:
```console
[root@908402a044da /]# cat /etc/redhat-release
CentOS Linux release 7.7.1908 (Core)
[root@908402a044da /]# curl -s https://packagecloud.io/install/repositories/akopytov/sysbench/script.rpm.sh | sudo bash
Detected operating system as centos/7.
Checking for curl...
Detected curl...
Downloading repository file: https://packagecloud.io/install/repositories/akopytov/sysbench/config_file.repo?os=centos&dist=7&source=script
done.
...
```

In any case, you can use the `os` and `dist` variables to override automatic detection:
```console
# export os=el dist=7
# curl ...
```

**Comment by chengyuqi** [comment]
got it.
i mean if all the previous conditions are not met, the condition [-e /etc/redhat-release] and ["${os_hint}" = "centos"] just met, the value of variable dist will be wrong and script gonna exit incorrectly.
we can avoid this problem by changing print $3 to print $4.

**Comment by akopytov** [comment]
Probably. But that script is not even mine. It is provided by packagecloud.io.
