### ISSUE TITLE
Port sysbench to RISCV

### ISSUE THREAD

**Issue by kirana1996** [akopytov/sysbench#333]
Hello,
We are porting sysbench to RISCV (HiFive Unleashed) that has yocto(linux) on it.
There are too many changes involved. Can someone please send the porting instructions or documents if any on this?

Thanks,

**Comment by akopytov** [comment]
I don't think porting to RISC-V is possible, because LuaJIT does not support RISC-V as far as I know.

**Comment by kirana1996** [comment]
Any idea when the RISCV port for LuaJIT can be available?

Thanks!

**Comment by akopytov** [comment]
I don't have any ideas, but this question should be directed to the LuaJIT project, not to me.

**Comment by TUT-jiayou** [comment]
@kirana1996 HI, Have you made any progress recently about porting riscv

**Comment by dictcp** [comment]
you may check my attempt to run sysbench on risc-v at
https://github.com/dictcp/sysbench
