### ISSUE TITLE
 oltp-test-mode=nontrx do not work

### ISSUE THREAD

**Issue by seanlook** [akopytov/sysbench#34]
I use the following command to mysql oltp benchmark:
```
./bin/sysbench --test=./share/tests/db/oltp.lua \
--mysql-host=10.0.201.36 --mysql-port=8066 --mysql-user=ecuser --mysql-password=ecuser \
--mysql-db=dbtest1a --oltp-tables-count=10 --oltp-table-size=500000 \
--report-interval=10 --rand-init=on --max-requests=0 \
--oltp-test-mode=nontrx --oltp-nontrx-mode=update_key --oltp-read-only=off \
--max-time=120 --num-threads=128 \
run
```

After checking general log, I saw no difference between `oltp-test-mode=nontrx` and `oltp-test-mode=complex`. Both of them have `BGEIN/COMMIT` command sent. 

I set `oltp-nontrx-mode` to `update_key`, but update-non-key queries also show up in the general log. So I search keyword `nontrx` in the sysbench source code(0.5), no result found.

Maybe I misunderstand the `--oltp-test-mode=nontrx --oltp-nontrx-mode=update_key` options, would you correct me?

**Comment by akopytov** [comment]
sysbench 0.5 does not support the `--oltp-test-mode` and `--oltp-nontrx-mode` options. Documenting all supported options is of course on my TODO. The only reason I'm delaying it now is that a lot of things will change for 1.0, so spending time on documenting 0.5 wouldn't make sense.

I think `update_index.lua` is supposed to be a replacement for those options. It issues autocommit UPDATEs against a secondary index column. Is that what you were looking for?

Hint: you can use `--mysql-dry-run --mysql-debug` to check queries that sysbench would send to the server with a specific script and options combination, there's no need to resort to the general log.

**Comment by seanlook** [comment]
Thanks for your reply and your great sysbench!

When the version 1.0 will be released? I can't wait to try it.

**Comment by akopytov** [comment]
I don't have an ETA for 1.0 at the moment. But you can use the 1.0 branch. Just keep in mind it is a work-in-progress, so it may not be compatible with any previous of future releases.
