### ISSUE TITLE
[Question] How to dump queries?

### ISSUE THREAD

**Issue by zhangysh1995** [akopytov/sysbench#361]
Hi, I now know how to run the tests, but I'm curious about the queries actually executed, anyway to export the queries?

**Comment by zhangysh1995** [comment]
I tried with MySQL general log and it works. However, this is slightly complex than I expect for sysbench.

**Comment by akopytov** [comment]
You can use `--mysql-debug` to dump all MySQL API calls, and the output will include all SQL queries being sent to the client API. If even that is too complex, modifying the Lua scripts to print all queries in addition to executing them should also be an easy task.
