### ISSUE TITLE
Query: Does sysbench performs data integrity during "oltp_read_write" test ?

### ISSUE THREAD

**Issue by neekhraashish** [akopytov/sysbench#365]
Hi Guys,

I have a query regarding sysbench "oltp_read_write" test which we use for MySQL and PostgreSQL databases. During "run" phase, does it checks data integrity as well? Just like it does validation when running "fileio" ?

Any response is much appreciated.

Thanks.

**Comment by grooverdan** [comment]
No data integrity checks are done. That's what the database does. Errors are counted (except for `--mysql-ignore-errors` list). There's no `foreign` key constraints on tables. as visible in [source code](https://github.com/akopytov/sysbench/blob/master/src/lua/oltp_common.lua#L193).

**Comment by neekhraashish** [comment]
Thanks, appreciate for your response.
