### ISSUE TITLE
FATAL: `sysbench.cmdline.call_command' function failed: (not a string)

### ISSUE THREAD

**Issue by cyckax** [akopytov/sysbench#396]
Hi,

When I tried to use sysbench 1.0.20 & 1.0.17 to test mysql 5.7.32, I use this command:
./sysbench --mysql-host=1.1.1.1 --mysql-port=3350 --mysql-user=sysbench --mysql-password=***--mysql-db=sbtest --tables=50 --table_size=100000 --rand-type=uniform --threads=32 --time=1800 --report-interval=1 --percentile=99  --skip_trx=off --db-ps-mode=disable --mysql-ignore-errors=all ./lua/oltp_read_write.lua prepare 

and sysbench report : `sysbench.cmdline.call_command' function failed: (not a string)

**Comment by cyckax** [comment]
sry

**Comment by ahdong2007** [comment]
> Hi,
> 
> When I tried to use sysbench 1.0.20 & 1.0.17 to test mysql 5.7.32, I use this command: ./sysbench --mysql-host=1.1.1.1 --mysql-port=3350 --mysql-user=sysbench --mysql-password=***--mysql-db=sbtest --tables=50 --table_size=100000 --rand-type=uniform --threads=32 --time=1800 --report-interval=1 --percentile=99 --skip_trx=off --db-ps-mode=disable --mysql-ignore-errors=all ./lua/oltp_read_write.lua prepare
> 
> and sysbench report : `sysbench.cmdline.call_command' function failed: (not a string)

May I ask, I have encountered the same problem. How did you solve it and what was the cause?
