### ISSUE TITLE
sysbench on windows

### ISSUE THREAD

**Issue by shruthism** [akopytov/sysbench#41]
Hi, 

I want to run sysbench on windows. I dont have visual studio.

Is there any method to do sysbench ?

**Comment by akopytov** [comment]
I think compiling from source with Visual Studio is the only option. mingw may or may not work -- I never tried it. If you will, I'm interested in the results.

**Comment by Marc-T** [comment]
Hi shruthism, 

You can try visual studio, there is a community version : https://www.visualstudio.com/en-us/products/visual-studio-community-vs.aspx

Check if you are elligible to the free licence : https://www.visualstudio.com/support/legal/mt171547

I also made some regular builds of sysbench for windows that you can download on my blog : [Sysbench builds](http://mysql.on.windows.free.fr/index.php/category/sysbench/)

**Comment by shruthism** [comment]
Hi,

I got below error.

[image: Inline image 2]

**Comment by karatihh** [comment]
can we run it from subsystem linux on windows?
