### ISSUE TITLE
error while execution

### ISSUE THREAD

**Issue by shruthism** [akopytov/sysbench#42]
PFA screenshot of the error.

The c compiler identification is unknown

![error](https://cloud.githubusercontent.com/assets/17595933/14808630/8954786c-0ba4-11e6-8228-e922e8b39c42.png)

**Comment by akopytov** [comment]
I'm not sure if VS2008 is supported. Can you try with a newer version, preferably the latest available?

**Comment by shruthism** [comment]
Dear Sir,

This performance test, i am doing as a part of my project. So please help.

* Please find below attached sysbench.sln file and
* other files (will share in google drive)
I got executing still step

In the sysbench directory, execute cmake -G "Visual Studio 9 2008"

Otherwise can you provide sysbench.exe file which would help in doing
tests.

--------------------------------------------------------------------

* there is no VCbuild.exe in the latest version of visual studio.

* Below step i am not able to understand.

Open sysbench.sln in Explorer and build Relwithdebinfo target.

Alternatively, from the command line, issue
vcbuild /useenv sysbench.sln "Relwithdebinfo|Win32"

Thanks,
shruthi


* Please let me know how to execute and view CPU, memory, file IO

Microsoft Visual Studio Solution File, Format Version 11.00
# Visual Studio 2010
Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "ALL_BUILD", "ALL_BUILD.vcxproj", "{AF27F23A-0561-3B63-9093-9313DE806FD6}"
	ProjectSection(ProjectDependencies) = postProject
		{5C1F0EF7-614A-3E5A-AADC-E1E249AF36B8} = {5C1F0EF7-614A-3E5A-AADC-E1E249AF36B8}
		{C23A075E-DF7E-341A-A429-2972AA68D8AC} = {C23A075E-DF7E-341A-A429-2972AA68D8AC}
		{A0566DBA-613C-3B11-8D13-4E14394BE659} = {A0566DBA-613C-3B11-8D13-4E14394BE659}
		{06E5729E-3E82-3213-9313-FC3079C40BB5} = {06E5729E-3E82-3213-9313-FC3079C40BB5}
		{F325A574-C203-305D-8B59-72955C854209} = {F325A574-C203-305D-8B59-72955C854209}
		{6DB6753C-FB7C-3C99-9D6F-35A42C0EB43E} = {6DB6753C-FB7C-3C99-9D6F-35A42C0EB43E}
		{5257E6F5-1397-3AA7-980D-BC3DE05DE098} = {5257E6F5-1397-3AA7-980D-BC3DE05DE098}
		{8895328D-1FDF-3F01-9354-3F411343F24A} = {8895328D-1FDF-3F01-9354-3F411343F24A}
		{E761444B-A0DA-3893-8503-16F3E24143A9} = {E761444B-A0DA-3893-8503-16F3E24143A9}
		{056DF784-6295-35B3-9E63-2806D9C853BB} = {056DF784-6295-35B3-9E63-2806D9C853BB}
	EndProjectSection
EndProject
Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "ZERO_CHECK", "ZERO_CHECK.vcxproj", "{5C1F0EF7-614A-3E5A-AADC-E1E249AF36B8}"
	ProjectSection(ProjectDependencies) = postProject
	EndProjectSection
EndProject
Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "lua", "scripting\lua\src\lua.vcxproj", "{C23A075E-DF7E-341A-A429-2972AA68D8AC}"
	ProjectSection(ProjectDependencies) = postProject
		{5C1F0EF7-614A-3E5A-AADC-E1E249AF36B8} = {5C1F0EF7-614A-3E5A-AADC-E1E249AF36B8}
	EndProjectSection
EndProject
Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "sbcpu", "tests\cpu\sbcpu.vcxproj", "{A0566DBA-613C-3B11-8D13-4E14394BE659}"
	ProjectSection(ProjectDependencies) = postProject
		{5C1F0EF7-614A-3E5A-AADC-E1E249AF36B8} = {5C1F0EF7-614A-3E5A-AADC-E1E249AF36B8}
	EndProjectSection
EndProject
Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "sbfileio", "tests\fileio\sbfileio.vcxproj", "{06E5729E-3E82-3213-9313-FC3079C40BB5}"
	ProjectSection(ProjectDependencies) = postProject
		{5C1F0EF7-614A-3E5A-AADC-E1E249AF36B8} = {5C1F0EF7-614A-3E5A-AADC-E1E249AF36B8}
	EndProjectSection
EndProject
Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "sbmemory", "tests\memory\sbmemory.vcxproj", "{F325A574-C203-305D-8B59-72955C854209}"
	ProjectSection(ProjectDependencies) = postProject
		{5C1F0EF7-614A-3E5A-AADC-E1E249AF36B8} = {5C1F0EF7-614A-3E5A-AADC-E1E249AF36B8}
	EndProjectSection
EndProject
Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "sbmutex", "tests\mutex\sbmutex.vcxproj", "{6DB6753C-FB7C-3C99-9D6F-35A42C0EB43E}"
	ProjectSection(ProjectDependencies) = postProject
		{5C1F0EF7-614A-3E5A-AADC-E1E249AF36B8} = {5C1F0EF7-614A-3E5A-AADC-E1E249AF36B8}
	EndProjectSection
EndProject
Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "sbmysql", "drivers\mysql\sbmysql.vcxproj", "{5257E6F5-1397-3AA7-980D-BC3DE05DE098}"
	ProjectSection(ProjectDependencies) = postProject
		{5C1F0EF7-614A-3E5A-AADC-E1E249AF36B8} = {5C1F0EF7-614A-3E5A-AADC-E1E249AF36B8}
	EndProjectSection
EndProject
Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "sbscript", "scripting\sbscript.vcxproj", "{8895328D-1FDF-3F01-9354-3F411343F24A}"
	ProjectSection(ProjectDependencies) = postProject
		{5C1F0EF7-614A-3E5A-AADC-E1E249AF36B8} = {5C1F0EF7-614A-3E5A-AADC-E1E249AF36B8}
	EndProjectSection
EndProject
Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "sbthreads", "tests\threads\sbthreads.vcxproj", "{E761444B-A0DA-3893-8503-16F3E24143A9}"
	ProjectSection(ProjectDependencies) = postProject
		{5C1F0EF7-614A-3E5A-AADC-E1E249AF36B8} = {5C1F0EF7-614A-3E5A-AADC-E1E249AF36B8}
	EndProjectSection
EndProject
Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "sysbench", "sysbench.vcxproj", "{056DF784-6295-35B3-9E63-2806D9C853BB}"
	ProjectSection(ProjectDependencies) = postProject
		{5C1F0EF7-614A-3E5A-AADC-E1E249AF36B8} = {5C1F0EF7-614A-3E5A-AADC-E1E249AF36B8}
		{C23A075E-DF7E-341A-A429-2972AA68D8AC} = {C23A075E-DF7E-341A-A429-2972AA68D8AC}
		{A0566DBA-613C-3B11-8D13-4E14394BE659} = {A0566DBA-613C-3B11-8D13-4E14394BE659}
		{06E5729E-3E82-3213-9313-FC3079C40BB5} = {06E5729E-3E82-3213-9313-FC3079C40BB5}
		{F325A574-C203-305D-8B59-72955C854209} = {F325A574-C203-305D-8B59-72955C854209}
		{6DB6753C-FB7C-3C99-9D6F-35A42C0EB43E} = {6DB6753C-FB7C-3C99-9D6F-35A42C0EB43E}
		{5257E6F5-1397-3AA7-980D-BC3DE05DE098} = {5257E6F5-1397-3AA7-980D-BC3DE05DE098}
		{8895328D-1FDF-3F01-9354-3F411343F24A} = {8895328D-1FDF-3F01-9354-3F411343F24A}
		{E761444B-A0DA-3893-8503-16F3E24143A9} = {E761444B-A0DA-3893-8503-16F3E24143A9}
	EndProjectSection
EndProject
Global
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|Win32 = Debug|Win32
		Release|Win32 = Release|Win32
		MinSizeRel|Win32 = MinSizeRel|Win32
		RelWithDebInfo|Win32 = RelWithDebInfo|Win32
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
		{AF27F23A-0561-3B63-9093-9313DE806FD6}.Debug|Win32.ActiveCfg = Debug|Win32
		{AF27F23A-0561-3B63-9093-9313DE806FD6}.Release|Win32.ActiveCfg = Release|Win32
		{AF27F23A-0561-3B63-9093-9313DE806FD6}.MinSizeRel|Win32.ActiveCfg = MinSizeRel|Win32
		{AF27F23A-0561-3B63-9093-9313DE806FD6}.RelWithDebInfo|Win32.ActiveCfg = RelWithDebInfo|Win32
		{5C1F0EF7-614A-3E5A-AADC-E1E249AF36B8}.Debug|Win32.ActiveCfg = Debug|Win32
		{5C1F0EF7-614A-3E5A-AADC-E1E249AF36B8}.Debug|Win32.Build.0 = Debug|Win32
		{5C1F0EF7-614A-3E5A-AADC-E1E249AF36B8}.Release|Win32.ActiveCfg = Release|Win32
		{5C1F0EF7-614A-3E5A-AADC-E1E249AF36B8}.Release|Win32.Build.0 = Release|Win32
		{5C1F0EF7-614A-3E5A-AADC-E1E249AF36B8}.MinSizeRel|Win32.ActiveCfg = MinSizeRel|Win32
		{5C1F0EF7-614A-3E5A-AADC-E1E249AF36B8}.MinSizeRel|Win32.Build.0 = MinSizeRel|Win32
		{5C1F0EF7-614A-3E5A-AADC-E1E249AF36B8}.RelWithDebInfo|Win32.ActiveCfg = RelWithDebInfo|Win32
		{5C1F0EF7-614A-3E5A-AADC-E1E249AF36B8}.RelWithDebInfo|Win32.Build.0 = RelWithDebInfo|Win32
		{C23A075E-DF7E-341A-A429-2972AA68D8AC}.Debug|Win32.ActiveCfg = Debug|Win32
		{C23A075E-DF7E-341A-A429-2972AA68D8AC}.Debug|Win32.Build.0 = Debug|Win32
		{C23A075E-DF7E-341A-A429-2972AA68D8AC}.Release|Win32.ActiveCfg = Release|Win32
		{C23A075E-DF7E-341A-A429-2972AA68D8AC}.Release|Win32.Build.0 = Release|Win32
		{C23A075E-DF7E-341A-A429-2972AA68D8AC}.MinSizeRel|Win32.ActiveCfg = MinSizeRel|Win32
		{C23A075E-DF7E-341A-A429-2972AA68D8AC}.MinSizeRel|Win32.Build.0 = MinSizeRel|Win32
		{C23A075E-DF7E-341A-A429-2972AA68D8AC}.RelWithDebInfo|Win32.ActiveCfg = RelWithDebInfo|Win32
		{C23A075E-DF7E-341A-A429-2972AA68D8AC}.RelWithDebInfo|Win32.Build.0 = RelWithDebInfo|Win32
		{A0566DBA-613C-3B11-8D13-4E14394BE659}.Debug|Win32.ActiveCfg = Debug|Win32
		{A0566DBA-613C-3B11-8D13-4E14394BE659}.Debug|Win32.Build.0 = Debug|Win32
		{A0566DBA-613C-3B11-8D13-4E14394BE659}.Release|Win32.ActiveCfg = Release|Win32
		{A0566DBA-613C-3B11-8D13-4E14394BE659}.Release|Win32.Build.0 = Release|Win32
		{A0566DBA-613C-3B11-8D13-4E14394BE659}.MinSizeRel|Win32.ActiveCfg = MinSizeRel|Win32
		{A0566DBA-613C-3B11-8D13-4E14394BE659}.MinSizeRel|Win32.Build.0 = MinSizeRel|Win32
		{A0566DBA-613C-3B11-8D13-4E14394BE659}.RelWithDebInfo|Win32.ActiveCfg = RelWithDebInfo|Win32
		{A0566DBA-613C-3B11-8D13-4E14394BE659}.RelWithDebInfo|Win32.Build.0 = RelWithDebInfo|Win32
		{06E5729E-3E82-3213-9313-FC3079C40BB5}.Debug|Win32.ActiveCfg = Debug|Win32
		{06E5729E-3E82-3213-9313-FC3079C40BB5}.Debug|Win32.Build.0 = Debug|Win32
		{06E5729E-3E82-3213-9313-FC3079C40BB5}.Release|Win32.ActiveCfg = Release|Win32
		{06E5729E-3E82-3213-9313-FC3079C40BB5}.Release|Win32.Build.0 = Release|Win32
		{06E5729E-3E82-3213-9313-FC3079C40BB5}.MinSizeRel|Win32.ActiveCfg = MinSizeRel|Win32
		{06E5729E-3E82-3213-9313-FC3079C40BB5}.MinSizeRel|Win32.Build.0 = MinSizeRel|Win32
		{06E5729E-3E82-3213-9313-FC3079C40BB5}.RelWithDebInfo|Win32.ActiveCfg = RelWithDebInfo|Win32
		{06E5729E-3E82-3213-9313-FC3079C40BB5}.RelWithDebInfo|Win32.Build.0 = RelWithDebInfo|Win32
		{F325A574-C203-305D-8B59-72955C854209}.Debug|Win32.ActiveCfg = Debug|Win32
		{F325A574-C203-305D-8B59-72955C854209}.Debug|Win32.Build.0 = Debug|Win32
		{F325A574-C203-305D-8B59-72955C854209}.Release|Win32.ActiveCfg = Release|Win32
		{F325A574-C203-305D-8B59-72955C854209}.Release|Win32.Build.0 = Release|Win32
		{F325A574-C203-305D-8B59-72955C854209}.MinSizeRel|Win32.ActiveCfg = MinSizeRel|Win32
		{F325A574-C203-305D-8B59-72955C854209}.MinSizeRel|Win32.Build.0 = MinSizeRel|Win32
		{F325A574-C203-305D-8B59-72955C854209}.RelWithDebInfo|Win32.ActiveCfg = RelWithDebInfo|Win32
		{F325A574-C203-305D-8B59-72955C854209}.RelWithDebInfo|Win32.Build.0 = RelWithDebInfo|Win32
		{6DB6753C-FB7C-3C99-9D6F-35A42C0EB43E}.Debug|Win32.ActiveCfg = Debug|Win32
		{6DB6753C-FB7C-3C99-9D6F-35A42C0EB43E}.Debug|Win32.Build.0 = Debug|Win32
		{6DB6753C-FB7C-3C99-9D6F-35A42C0EB43E}.Release|Win32.ActiveCfg = Release|Win32
		{6DB6753C-FB7C-3C99-9D6F-35A42C0EB43E}.Release|Win32.Build.0 = Release|Win32
		{6DB6753C-FB7C-3C99-9D6F-35A42C0EB43E}.MinSizeRel|Win32.ActiveCfg = MinSizeRel|Win32
		{6DB6753C-FB7C-3C99-9D6F-35A42C0EB43E}.MinSizeRel|Win32.Build.0 = MinSizeRel|Win32
		{6DB6753C-FB7C-3C99-9D6F-35A42C0EB43E}.RelWithDebInfo|Win32.ActiveCfg = RelWithDebInfo|Win32
		{6DB6753C-FB7C-3C99-9D6F-35A42C0EB43E}.RelWithDebInfo|Win32.Build.0 = RelWithDebInfo|Win32
		{5257E6F5-1397-3AA7-980D-BC3DE05DE098}.Debug|Win32.ActiveCfg = Debug|Win32
		{5257E6F5-1397-3AA7-980D-BC3DE05DE098}.Debug|Win32.Build.0 = Debug|Win32
		{5257E6F5-1397-3AA7-980D-BC3DE05DE098}.Release|Win32.ActiveCfg = Release|Win32
		{5257E6F5-1397-3AA7-980D-BC3DE05DE098}.Release|Win32.Build.0 = Release|Win32
		{5257E6F5-1397-3AA7-980D-BC3DE05DE098}.MinSizeRel|Win32.ActiveCfg = MinSizeRel|Win32
		{5257E6F5-1397-3AA7-980D-BC3DE05DE098}.MinSizeRel|Win32.Build.0 = MinSizeRel|Win32
		{5257E6F5-1397-3AA7-980D-BC3DE05DE098}.RelWithDebInfo|Win32.ActiveCfg = RelWithDebInfo|Win32
		{5257E6F5-1397-3AA7-980D-BC3DE05DE098}.RelWithDebInfo|Win32.Build.0 = RelWithDebInfo|Win32
		{8895328D-1FDF-3F01-9354-3F411343F24A}.Debug|Win32.ActiveCfg = Debug|Win32
		{8895328D-1FDF-3F01-9354-3F411343F24A}.Debug|Win32.Build.0 = Debug|Win32
		{8895328D-1FDF-3F01-9354-3F411343F24A}.Release|Win32.ActiveCfg = Release|Win32
		{8895328D-1FDF-3F01-9354-3F411343F24A}.Release|Win32.Build.0 = Release|Win32
		{8895328D-1FDF-3F01-9354-3F411343F24A}.MinSizeRel|Win32.ActiveCfg = MinSizeRel|Win32
		{8895328D-1FDF-3F01-9354-3F411343F24A}.MinSizeRel|Win32.Build.0 = MinSizeRel|Win32
		{8895328D-1FDF-3F01-9354-3F411343F24A}.RelWithDebInfo|Win32.ActiveCfg = RelWithDebInfo|Win32
		{8895328D-1FDF-3F01-9354-3F411343F24A}.RelWithDebInfo|Win32.Build.0 = RelWithDebInfo|Win32
		{E761444B-A0DA-3893-8503-16F3E24143A9}.Debug|Win32.ActiveCfg = Debug|Win32
		{E761444B-A0DA-3893-8503-16F3E24143A9}.Debug|Win32.Build.0 = Debug|Win32
		{E761444B-A0DA-3893-8503-16F3E24143A9}.Release|Win32.ActiveCfg = Release|Win32
		{E761444B-A0DA-3893-8503-16F3E24143A9}.Release|Win32.Build.0 = Release|Win32
		{E761444B-A0DA-3893-8503-16F3E24143A9}.MinSizeRel|Win32.ActiveCfg = MinSizeRel|Win32
		{E761444B-A0DA-3893-8503-16F3E24143A9}.MinSizeRel|Win32.Build.0 = MinSizeRel|Win32
		{E761444B-A0DA-3893-8503-16F3E24143A9}.RelWithDebInfo|Win32.ActiveCfg = RelWithDebInfo|Win32
		{E761444B-A0DA-3893-8503-16F3E24143A9}.RelWithDebInfo|Win32.Build.0 = RelWithDebInfo|Win32
		{056DF784-6295-35B3-9E63-2806D9C853BB}.Debug|Win32.ActiveCfg = Debug|Win32
		{056DF784-6295-35B3-9E63-2806D9C853BB}.Debug|Win32.Build.0 = Debug|Win32
		{056DF784-6295-35B3-9E63-2806D9C853BB}.Release|Win32.ActiveCfg = Release|Win32
		{056DF784-6295-35B3-9E63-2806D9C853BB}.Release|Win32.Build.0 = Release|Win32
		{056DF784-6295-35B3-9E63-2806D9C853BB}.MinSizeRel|Win32.ActiveCfg = MinSizeRel|Win32
		{056DF784-6295-35B3-9E63-2806D9C853BB}.MinSizeRel|Win32.Build.0 = MinSizeRel|Win32
		{056DF784-6295-35B3-9E63-2806D9C853BB}.RelWithDebInfo|Win32.ActiveCfg = RelWithDebInfo|Win32
		{056DF784-6295-35B3-9E63-2806D9C853BB}.RelWithDebInfo|Win32.Build.0 = RelWithDebInfo|Win32
	EndGlobalSection
	GlobalSection(ExtensibilityGlobals) = postSolution
	EndGlobalSection
	GlobalSection(ExtensibilityAddIns) = postSolution
	EndGlobalSection
EndGlobal
