### ISSUE TITLE
--warmup-time doesnt work for oltp

### ISSUE THREAD

**Issue by ligeng0197** [akopytov/sysbench#467]
**command:**
sysbench \
--db-driver=pgsql \
--report-interval=2 \
--oltp-table-size=250000 \
--oltp-tables-count=150 \
--threads=64 \
--warmup-time=100 \
--time=10 \
--pgsql-host=localhost \
--pgsql-port=15432 \
--pgsql-user=dell \
--pgsql-password=Secretpassword@123 \
--pgsql-db=sysbench \
/usr/share/sysbench/tests/include/oltp_legacy/oltp.lua \
run

**and result is:**
sysbench 1.0.20 (using bundled LuaJIT 2.1.0-beta2)

Running the test with following options:
Number of threads: 64
Report intermediate results every 2 second(s)
Initializing random number generator from current time

Initializing worker threads...

Threads started!

[ 2s ] thds: 64 tps: 1304.46 qps: 26173.05 (r/w/o: 18332.82/5223.82/2616.41) lat (ms,95%): 57.87 err/s: 0.00 reconn/s: 0.00
[ 4s ] thds: 64 tps: 1348.34 qps: 26979.80 (r/w/o: 18893.26/5389.36/2697.18) lat (ms,95%): 58.92 err/s: 0.00 reconn/s: 0.00
[ 6s ] thds: 64 tps: 1384.05 qps: 27686.03 (r/w/o: 19380.22/5537.70/2768.10) lat (ms,95%): 54.83 err/s: 0.00 reconn/s: 0.00
[ 8s ] thds: 64 tps: 1325.20 qps: 26475.42 (r/w/o: 18527.74/5297.28/2650.39) lat (ms,95%): 58.92 err/s: 0.00 reconn/s: 0.00
[ 10s ] thds: 64 tps: 1341.31 qps: 26847.18 (r/w/o: 18798.82/5365.74/2682.62) lat (ms,95%): 56.84 err/s: 0.00 reconn/s: 0.00
SQL statistics:
    queries performed:
        read:                            188664
        write:                           53904
        other:                           26952
        total:                           269520
    transactions:                        13476  (1340.96 per sec.)
    queries:                             269520 (26819.14 per sec.)
    ignored errors:                      0      (0.00 per sec.)
    reconnects:                          0      (0.00 per sec.)

General statistics:
    total time:                          10.0459s
    total number of events:              13476

Latency (ms):
         min:                                   25.12
         avg:                                   47.59
         max:                                   71.23
         95th percentile:                       57.87
         sum:                               641351.61

Threads fairness:
    events (avg/stddev):           210.5625/0.66
    execution time (avg/stddev):   10.0211/0.01

there is no warm up time and all is closed in about 10 seconds.

**Comment by rawen554** [comment]
The problem is that you using release version 1.0.20, and warmup time feature is not released yet, but in master.
