### ISSUE TITLE
sys bench release tag request

### ISSUE THREAD

**Issue by ScrumpyJack** [akopytov/sysbench#48]
Could you tag a release of sysbench to help with packaging?

`git tag -a v1.0 -m "my first release tag 1.0"`

https://help.github.com/articles/creating-releases/

thanks

**Comment by akopytov** [comment]
This is a duplicate of #1 I guess. I understand the important of release tags, but a more general issue is that there's no releases to tag yet. I'm going to create regular tagged and versioned releases starting from sysbench 1.0, please be patient.
