### ISSUE TITLE
Cross-compile aarch64 failed

### ISSUE THREAD

**Issue by garyfcg** [akopytov/sysbench#499]
Hi All,

How to fix the below error?

./autogen.sh
./configure --build=aarch64-linux-gnu --host=aarch64 CC=/tool/gcc_linaro/gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-gcc --without-mysql
make

The below issue:
Making all in third_party/luajit
make[1]: Entering directory '/workspace/opensource/sysbench/third_party/luajit'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/workspace/opensource/sysbench/third_party/luajit'
Making all in third_party/concurrency_kit
make[1]: Entering directory '/workspace/opensource/sysbench/third_party/concurrency_kit'
rm -rf tmp
mkdir tmp
tar -C . -cf - ck | tar -xf - -C tmp/
chmod -R u+w tmp
cd tmp/ck &&                        \
CC="/tool/gcc_linaro/gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-gcc"                          \
CFLAGS="-O3 -funroll-loops  -D_GNU_SOURCE -I/usr/local/include -DCK_MD_CACHELINE=128"      \
LDFLAGS="-L/usr/local/lib"                \
  ./configure  \
  --prefix=/workspace/opensource/sysbench/third_party/concurrency_kit && \
make && \
make install
Detecting operating system.......success [linux]
Detecting machine architecture...success [x86_64]
Finding dirname command..........success [/usr/bin/dirname]
Determining build directory......success [/workspace/opensource/sysbench/third_party/concurrency_kit/tmp/ck]
Finding gzip tool................success [/bin/gzip]
Finding suitable compiler........failed  [update compiler]
Makefile:498: recipe for target 'lib/libck.a' failed
make[1]: *** [lib/libck.a] Error 1
make[1]: Leaving directory '/workspace/opensource/sysbench/third_party/concurrency_kit'
Makefile:478: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by garyfcg** [comment]
Follow the below step, can fix.
1. Downloaded sysbench_0.5.orig.tar.gz from http://repo.percona.com/apt/pool/main/s/sysbench/
2. Unrar, then:
./autogen.sh
./configure --build=aarch64-linux-gnu --host=aarch64 CC=/tool/gcc_linaro/gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-gcc --without-mysql CFLAGS="-static"
 make
3. Compiled failed:
undefined reference to `rpl_malloc'
sb_options.o: In function `new_option':
/home/tater/work/sysbench/sysbench-0.5/sysbench/sb_options.c:404: undefined reference to `rpl_malloc'
sb_options.o: In function `new_value':
/home/tater/work/sysbench/sysbench-0.5/sysbench/sb_options.c:392: undefined reference to `rpl_malloc'
sb_logger.o: In function `oper_handler_init':
/home/tater/work/sysbench/sysbench-0.5/sysbench/sb_logger.c:497: undefined reference to `rpl_malloc'
/home/tater/work/sysbench/sysbench-0.5/sysbench/sb_logger.c:498: undefined reference to `rpl_malloc'
db_driver.o:/home/tater/work/sysbench/sysbench-0.5/sysbench/db_driver.c:721: more undefined references to `rpl_malloc' follow
collect2: ld returned 1 exit status

4. Delected "$as_echo "#define malloc rpl_malloc" >>confdefs.h" from configure file
5.  configure again, then make.

The finial file:
 file ./sysbench/sysbench
./sysbench/sysbench: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, BuildID[sha1]=1c3dec688f51a20ab36c65834465295336504d5f, with debug_info, not stripped

**Comment by silentswords** [comment]
Hi,
If i want to use the latest TAG(version 1.0.20).
what should i do?

Thanks
