### ISSUE TITLE
cannot open oltp on macosx

### ISSUE THREAD

**Issue by yydzero** [akopytov/sysbench#5]
Encounter following error when run oltp test on macosx 10.9. Looks like lua scripts are not installed properly.

Libtoolized with: libtoolize (GNU libtool) 2.4.2
Automade with: automake (GNU automake) 1.14.1
Configured with: autoconf (GNU Autoconf) 2.69

± |0.5 ✗| → sysbench --test=oltp --db-driver=pgsql --pgsql-user=gpadmin prepare
sysbench 0.5:  multi-threaded system evaluation benchmark

PANIC: unprotected error in call to Lua API (cannot open oltp: No such file or directory)

**Comment by akopytov** [comment]
With sysbench 0.5 you need to pass a path to a Lua script as an argument to the `--test` option, e.g.:

```
./sysbench ---test=tests/db/oltp.lua ...
```

Unfortunately, this is not properly documented (yet).
