### ISSUE TITLE
sysbench scaling issue

### ISSUE THREAD

**Issue by atishp04** [akopytov/sysbench#51]
It can be run by both limiting request or run time.
Run command for sysbench by limiting requests:
 ./sysbench --test=tests/db/oltp.lua --oltp-table-size=1000000 --mysql-db=test --mysql-user=root --mysql-password=mysql --oltp-test-mode=complex --oltp-read-only=off --oltp-reconnect=on *--max-requests=10000*--num-threads=256 run

Hi,
I am trying to setup sysbench for one of our server with 256 cores.
However, it does not scale up. The more threads I add, the lesser is transactions per sec.

It's not a server scaling issue as other benchmarks such as TPCC/hackbench scale properly.

Here are things I tried
----------------------------------------------------------------------------------------------------------
Run command for sysbench by limiting requests:
 ./sysbench --test=tests/db/oltp.lua --oltp-table-size=1000000 --mysql-db=test --mysql-user=root --mysql-password=mysql --oltp-test-mode=complex --oltp-read-only=off --oltp-reconnect=on *--max-requests=10000*--num-threads=64 run

Run command for sysbench by limiting time:
./sysbench --test=tests/db/oltp.lua --oltp-table-size=1000000 --mysql-db=test --mysql-user=root --mysql-password=mysql --oltp-test-mode=complex --oltp-read-only=off --oltp-reconnect=on *--max-time=60 --max-requests=0*--num-threads=64 run*

--max-time=60
Threads
16 transactions:                        89778  (1496.01 per sec.)
32                        transactions: 81403  (1356.09 per sec.)
64                        transactions: 63868  (1063.43 per sec.)

--max-requests=10000

Threads
32                        transactions: 10002  (1113.30 per sec.)
128                       transactions: 10000  (300.74 per sec.)
256                       transactions: 10000  (201.37 per sec.) 

Can you please point out what's wrong ? Do I need to enable something in the compiler ?

Here are my gcc version:
gcc version 4.4.7 20120313 (Red Hat 4.4.7-4.0.16) (GCC) 

Regards,
Atish

**Comment by akopytov** [comment]
Hello,

You did not specify the sysbench version, but my guess is that you are hitting scalability issues with random numbers generator, which is a known problem with sysbench 0.5.

Can you try the 1.0 branch in the same git repository and let me know if it fixes the scalability issues you are observing?

**Comment by atishp04** [comment]
Hi,
Yes it was 0.5. I switched to 1.0 branch and results looked all same.

---------------------------------------------------------------------------------------------------------------------
 ./sysbench --test=tests/db/oltp.lua --oltp-table-size=1000000 --mysql-db=test --mysql-user=root --mysql-password=mysql --max-time=60 --oltp-test-mode=complex --oltp-read-only=off --max-requests=0 --num-threads=256 run
sysbench 1.0:  multi-threaded system evaluation benchmark
--------------------------------------------------------------------------------------------------------------

Number of threads:      -------------------- Transactions per sec
8                                                             55538(925.40 per sec.)
16                                                           57945 (965.43 per sec.)
32                                                           57221 (953.04 per sec.)
64                                                           49218 (818.69 per sec.)
128                                                         22805 (379.09 per sec.)
256                                                         15507 (256.41 per sec)

Should I try 0.4 version ?

Regards,
Atish

**Comment by akopytov** [comment]
OK, there's an easy way to check if it's a sysbench scalability issue or not. You can add the `--mysql-dry-run` option and repeat the tests. The option makes sysbench do all the work required to generate queries, but do not actually send them to the server. If scalability is better in this mode, then server is the bottleneck.

**Comment by atishp04** [comment]
Thanks. Dry-run scales as per expected. 
I dont see the server scaling issue in TPCC. So I thought it might not be a server issue.
Is there any configuration in mysql that I should tweak to run it correctly ?

Regards,
Atish

**Comment by akopytov** [comment]
Thanks for letting me know, I'm closing the issue. As to tuning the server, that is a very broad question. MySQL is known to have suboptimal scaIability on systems with high numbers of cores and  write-intensive workloads. I'd suggest using `PERFORMANCE_SCHEMA` to identify the source of contention in the server.
