### ISSUE TITLE
Unknown database 'sbtest'

### ISSUE THREAD

**Issue by simonxiaoss** [akopytov/sysbench#58]
I am running on Ubuntu 1604. 
Server1: **MariaDb**: **10.1.16-MariaDB**, the IP is 192.168.4.169

Server2: the IP is 192.168.4.168
**sysbench**, **0.5**, cloned from https://github.com/akopytov/sysbench

```
1. git clone https://github.com/akopytov/sysbench
2. apt install libtool libmysqlclient-dev -o Acquire::ForceIPv4=true
3. cd sysbench
4. ./autogen.sh && ./configure && make && make install

5. From server2, I can connect to the MariaDb on Server 1 (192.168.4.168) by MySQL client tool and execute sql commands for example, SHOW DATABASES;
```

**The issue:** 
When run sysbench, error reported:
```
lisa@ubuntuClient:~/benchmark/mariadb/sysbench/sysbench# sysbench --test=/root/bt/mysql/data  --mysql-user=lisa --mysql-password=lisapassword
sysbench 0.5:  multi-threaded system evaluation benchmark

FATAL: unable to connect to MySQL server, aborting...
FATAL: error 1049: Unknown database 'sbtest'
FATAL: failed to execute function `prepare': ...riadb/sysbench/sysbench/sysbench
```

**The sysbench command is:** 
`sysbench --test=/root/benchmark/mariadb/sysbench/sysbench/sysbench/tests/db/oltp.lua prepare --mysql-host=192.168.4.169 --mysql-user=lisa --mysql-password=lisapassword`

**Comment by akopytov** [comment]
You have to create the database that sysbench wll use (`sbtest` by default) and grant privileges to it:

``` sql
CREATE DATABASE sbtest;
CREATE USER sbtest@localhost;
GRANT ALL PRIVILEGES ON sbtest.* TO sbtest@localhost
```

**Comment by Cazaimi** [comment]
I have written a read_only script of my own. I am trying to benchmark a live server. As a result, I do not have other privileges. Also, the DB is already present, and I am giving the following command: 
`./script_publish.lua --mysql-host=<my-IP-here> --mysql-user=<my-username-here> --mysql-password=<my-pass> --mysql-socket=/tmp/mysql3307.sock --mysql-port=3307 --report-interval=1 --threads=32 --histogram --mysql-db=<servicesdb> run `
 
and it gives me the following error:
`FATAL: unable to connect to MySQL server on socket '/tmp/mysql3307.sock', aborting...
FATAL: error 2002: Can't connect to local MySQL server through socket '/tmp/mysql3307.sock' (2)
`

**Comment by akopytov** [comment]
@Cazaimi sysbench assumes `--mysql-host=localhost` if the `--mysql-socket` option is present. If your server host is not localhost, just remove the `--mysql-socket` option.

**Comment by Cazaimi** [comment]
@akopytov, that solved the issue. Much thanks!

**Comment by harshisree** [comment]
I am getting below error while connecting to Maxscale on remote host to run sysbench:
FATAL: error 1049: Unknown database 'sbtest'
But I am able to access sbtest database through Maxscale connection with same credentials on same remote host.
