### ISSUE TITLE
the results of the io test when i use sysbench 1.0

### ISSUE THREAD

**Issue by way2questions** [akopytov/sysbench#72]
this is the results:
ysbench --test=fileio --num-threads=8 --file-total-size=64G --file-test-mode=rndrw run
sysbench 1.0:  multi-threaded system evaluation benchmark

Running the test with following options:
Number of threads: 8
Initializing random number generator from current time

Extra file open flags: 0
128 files, 512MiB each
64GiB total file size
Block size 16KiB
Number of IO requests: 10000
Read/Write ratio for combined random IO test: 1.50
Periodic FSYNC enabled, calling fsync() each 100 requests.
Calling fsync() at the end of test, Enabled.
Using synchronous I/O mode
Doing random r/w test
Initializing worker threads...

Threads started!

File operations:
    reads/s:                      8259.22
    writes/s:                     5499.26
    fsyncs/s:                     17610.85

Throughput:
    read, MiB/s:                  129.05
    written, MiB/s:               85.93

General statistics:
    total time:                          0.7268s
    total number of events:              10000
    total time taken by event execution: 1.7759s
    response time:
         min:                                  0.00ms
         avg:                                  0.18ms
         max:                                  1.98ms
         approx.  95 percentile:               0.54ms

Threads fairness:
    events (avg/stddev):           1250.0000/50.66
    execution time (avg/stddev):   0.2220/0.01

it is different from the sysbench 0.5,i want to know how can i get the value of the iops? could you help me?is there any docs?

**Comment by akopytov** [comment]
How different is it from 0.5?

**Comment by way2questions** [comment]
when i use 0.5 to test,the result shows "  588.01 Requests/sec executed",then i can know the value of the iops,but when i use 1.0,it has changed,i can not find the information,i just find this:
File operations:
    reads/s:                      8259.22
    writes/s:                     5499.26
    fsyncs/s:                     17610.85
how can i know the value of the iops,thanks

**Comment by akopytov** [comment]
Oh, I see the problem now. So in sysbench 0.5 reports the sum of read and write operations as "Requests". I changed that in 1.0 to report them separately, because in my opinion, the composite read/write metric is not representative as IOPS. To get IOPS, you probably want to use either a write-only test (`--file-test-mode=rndwr`) or a read-only one (`--file-test-mode=rndrd`), and then use either writes/s or reads/s value as IOPS.

**Comment by way2questions** [comment]
thank you very much,You did me a big favor,

**Comment by akopytov** [comment]
You are welcome.
