### ISSUE TITLE
PATH_MAX / DATA_PATH undefined

### ISSUE THREAD

**Issue by Marc-T** [akopytov/sysbench#74]
Hi Alexey,

I can't compile sysbench in Visual Studio 2015 since this commit 16ba86827fca12e27e2bf535e13d82e7ff36d636

PATH_MAX and DATA_PATH are undefined.

How can we keep compatibility with M$ ?

Thank you

**Comment by akopytov** [comment]
Hi Marc,

I just pushed a commit that hopefully fixes this specific problem. 

But in general, more invasive and most likely WIndows-incompatible changes are coming up (see the concurrency_kit branch). I suspect that the amount of efforts to port ConcurrencyKit to Visual Studio are non-trivial. On the other hand, I have to fix some scalability issues with sysbench that require a state-of-the-art concurrency primitives and algorithms that are not that easy to implement from scratch. So Windows is becoming increasingly hard to support, but I'd like to hear your opinion.

**Comment by Marc-T** [comment]
Alexey,

Thank you for the fix !

It's too bad to loose compatibility with Windows, it's not as if the product had never been compatible. I understand that it demand efforts to maintain it, and it will be easier for you to drop compatibility. And there is not a lot of demand for this feature...

Maybe i could help to maintain windows compatibility :
- alert where there is breaking changes
- If these changes are within reach, maybe I could handle them and make pull requests.

Maybe it's not worth the shot and i will stay with the last "windows-compatible" version of Sysbench.
- For me it does the job.
- at worst, i could fork the project and pull commits (Fix / minor imrovements) when needed.

Story of my *Windows MySQL DBA's* life.

Thank you anyway :)

**Comment by akopytov** [comment]
Thanks for the feedback. I guess trivial issues with Windows compatibility such as this one could be caught by Windows CI services similar to Travis and adding one is on my TODO. As to the more complex changes like importing external projects, I agree, let's try and see if keeping Windows support is worth the effort.
