### ISSUE TITLE
Sysbench oltp oracle support

### ISSUE THREAD

**Issue by tommytarget** [akopytov/sysbench#8]
I've been struggling in compiling and running sysbench against oracle database because of lack of support and document. But one thing that is really blocking me is that sysbench 0.5 doesn't seems to support oracle driver any more. In common.lua, 'oracle' is no longer a driver option so I can't even run sysbench preparation. Is downgrading to 0.4 the only option for me? Thanks!

**Comment by akopytov** [comment]
Yes, I don't use the Oracle driver myself, and there's not much interest in the community. But pull requests are always welcome.

The good thing about 0.5 is that Lua scripts are easy to modify and adjust when needed without having to recompile anything.

Downgrading to 0.4 is also an option.
