### ISSUE TITLE
sb_rand_uniq(1, oltp_table_size) generate duplicate value

### ISSUE THREAD

**Issue by miao606** [akopytov/sysbench#96]
sysbench 0.5 git version on centos 7, the oltp_table_size in the test script is 1 billion.

**Comment by akopytov** [comment]
Indeed, the current implementation of sb_rand_uniq() is naive. It does not guarantee any uniqueness, it just reduced the probability of generating a unique number under some circumstances. 

I'm going to re-implement it based on ideas from http://preshing.com/20121224/how-to-generate-a-sequence-of-unique-random-integers/

**Comment by akopytov** [comment]
Indeed, the current implementation of sb_rand_uniq() is naive. It does not guarantee any uniqueness, it just reduced the probability of generating a unique number under some circumstances. 

I'm going to re-implement it based on ideas from http://preshing.com/20121224/how-to-generate-a-sequence-of-unique-random-integers/

**Comment by Marcus9530** [comment]
Hi, may I ask which version this issue was fixed to? I'm having this problem on version 1.0.20
`sysbench 1.0.20 (using bundled LuaJIT 2.1.0-beta2)`
