### ISSUE TITLE
Memory test got huge diff between v1.0 and V0.4.12

### ISSUE THREAD

**Issue by euroford** [akopytov/sysbench#97]
Hi,

My computer has Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz, 8GB 2133MHz DDR4 DIMM x 2, Debian 9 testing OS, Linux emind-pc 4.8.0-1-amd64 #1 SMP Debian 4.8.7-1 (2016-11-13) x86_64 GNU/Linux.

I run the same command:
sysbench --num-threads=4 --test=memory --memory-total-size=20G --memory-block-size=4K --memory-oper=read --memory-access-mode=rnd run

got huge different  results:
0.4.12 said:
Operations performed: 5242880 (9592744.87 ops/sec)
20480.00 MB transferred (37471.66 MB/sec)
1.0 said:
Operations performed: 5242880 (650506.28 ops/sec)
20480.00 MiB transferred (2541.04 MiB/sec)

Which is the true story?

[sysbench-v1.0-memory-test-read-rnd.txt](https://github.com/akopytov/sysbench/files/665307/sysbench-v1.0-memory-test-read-rnd.txt)
[sysbench-v0.4.12-memory-test-read-rnd.txt](https://github.com/akopytov/sysbench/files/665308/sysbench-v0.4.12-memory-test-read-rnd.txt)

**Comment by akopytov** [comment]
The 1.0 story is closer to reality because of commit 8753cb93be4c0b81a20b704ced91e7a422da52b1.
