### ISSUE TITLE
check db_query() return value

### ISSUE THREAD

**Issue by dcongee** [akopytov/sysbench#98]
hello !

我想在自定义的Lua脚本中，判断db_query()函数的返回值，例如：
   rs=db_query("select count(*) from person_info where cisno='295098644'")
  if(rs ~= nil)
   then
  print(rs)
  end
但是，返回结果总是等于nil。还有其他函数可以判断SQL 的执行结果吗？
谢谢！

THIS ENGLISH：
I want to custom the Lua script, judge db_query () function return values, such as:
   rs=db_query("select count(*) from person_info where cisno='295098644'")
  if(rs ~= nil)
   then
  print(rs)
  end
However, return the result is always equal to nil.
There are other functions can be judged SQL execution result?
THANK YOU！

**Comment by akopytov** [comment]
Hi,

This functionality has been requested a number of times before. In particular, in #13. So I'm closing this one as a duplicate. Thanks!
